const app=document.querySelector('#app'), title=document.querySelector('#page-title');let data,view='command';
const fmt=n=>new Intl.NumberFormat('ko-KR').format(n||0);const risk=x=>`<span class="badge ${x}">${x}</span>`;
async function api(p){const r=await fetch(p);if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
async function load(){try{data=await api('/api/dashboard');document.querySelector('#mode').textContent=`${data.mode} 모드 · ${data.as_of}`;render()}catch(e){app.innerHTML=`<div class="card fail">데이터를 불러오지 못했습니다: ${e.message}</div>`}}
function command(){let k=data.kpi;return `<div class="grid kpis"><div class="card metric"><span class="label">현재 구독자</span><strong>${fmt(k.current)}</strong><div class="progress"><b style="width:${Math.max(1,k.current/k.target*100)}%"></b></div></div><div class="card metric"><span class="label">100만까지 남음</span><strong>${fmt(k.gap)}</strong></div><div class="card metric"><span class="label">100일 필요 성장</span><strong>${fmt(k.required_daily)}<small>/일</small></strong></div><div class="card metric"><span class="label">오늘 제작 목표</span><strong>5편</strong><em>품질 통과만 게시</em></div></div><div class="grid two" style="margin-top:16px"><div class="card hero"><p class="eyebrow">TODAY'S ORDERS</p><h2>오늘은 많이 만들되,<br>다르게 실험합니다.</h2><ol class="actions">${data.today_actions.map(x=>`<li>${x}</li>`).join('')}</ol></div><div class="card"><h2>운영 경보</h2>${data.alerts.map(a=>`<div class="alert ${a.severity}">${a.message}</div>`).join('')}<h2 style="margin-top:22px">제작 현황</h2><div class="pipeline"><span class="on">후보 ${data.topics.length}</span><span>대기 ${data.jobs.filter(j=>j.status==='queued').length}</span><span>생성 ${data.jobs.filter(j=>j.status==='generating').length}</span><span class="fail">차단 ${data.qc.blocking.length}</span></div></div></div>${topicTable(data.topics,'오늘 우선 소재 TOP5')}`}
function topicTable(items,heading='오늘 제작 후보 TOP20'){return `<div class="card" style="margin-top:16px"><h2>${heading} <span class="badge demo">DEMO — 외부 연결 전</span></h2><table class="table"><thead><tr><th>점수</th><th>소재 / 훅 A·B</th><th>분류</th><th>근거</th><th>위험</th></tr></thead><tbody>${items.map(t=>`<tr><td class="score">${t.score}</td><td><b>${t.title}</b><div class="hook"><span>A ${t.hook_a}</span><span>B ${t.hook_b}</span></div></td><td>${t.category}</td><td>${t.evidence_count}개</td><td>${risk(t.risk)}</td></tr>`).join('')}</tbody></table></div>`}
async function topics(){let d=await api('/api/topics');app.innerHTML=topicTable(d.items)}
function factory(){return `<div class="card"><h2>하루 5편 제작 대기열</h2>${data.jobs.map(j=>`<div class="alert"><b>#${j.id} ${j.topic_slug}</b> · ${j.status}<div class="pipeline"><span>체크포인트 ${j.checkpoint}</span><span>시도 ${j.attempts}</span><span>비용 ${fmt(j.cost)} credits</span></div></div>`).join('')}</div>`}
async function quality(){let d=await api('/api/qc');app.innerHTML=`<div class="grid kpis"><div class="card metric"><span class="label">게시 가능</span><strong>${data.qc.publishable?'YES':'NO'}</strong></div><div class="card metric"><span class="label">통과 검사</span><strong>${data.qc.passed}/${data.qc.total}</strong></div><div class="card metric"><span class="label">차단 사유</span><strong>${data.qc.blocking.length}</strong></div></div><div class="card" style="margin-top:16px"><h2>자동 품질 검사</h2><table class="table"><tbody>${d.items.map(q=>`<tr><td>${q.passed?'✅':'⛔'}</td><td><b>${q.name}</b></td><td>${q.measured}</td><td>기준 ${q.threshold}</td></tr>`).join('')}</tbody></table></div>`}
async function signals(){let d=await api('/api/competitors'),y=await api('/api/youtube-live');let f=y.feed;app.innerHTML=`<div class="card"><h2>브링이슈 공개 피드 <span class="badge ${f.source_mode==='LIVE'?'low':'high'}">${f.source_mode}</span></h2><p>${f.channel||'연결 오류'} · 수집 ${f.collected_at||'-'}</p><table class="table"><thead><tr><th>게시일</th><th>영상</th><th>상태</th></tr></thead><tbody>${(f.videos||[]).slice(0,8).map(v=>`<tr><td>${v.published.slice(0,10)}</td><td><a href="${v.url}" target="_blank"><b>${v.title}</b></a></td><td><span class="badge low">LIVE</span></td></tr>`).join('')}</tbody></table><p>OAuth: 업로드 ${y.oauth.upload_ready?'연결':'미연결'} · 댓글 ${y.oauth.comments_ready?'연결':'권한 필요'} · Analytics ${y.oauth.analytics_ready?'연결':'권한 필요'}</p></div><div class="card" style="margin-top:16px"><h2>경쟁 포맷 레이더 <span class="badge demo">DEMO</span></h2><table class="table"><thead><tr><th>채널</th><th>형식</th><th>빈도</th><th>신호</th></tr></thead><tbody>${d.items.map(x=>`<tr><td><b>${x.channel}</b></td><td>${x.format}</td><td>${x.frequency}</td><td>${x.signal}</td></tr>`).join('')}</tbody></table></div>`}
async function report(){let d=await api('/api/report');app.innerHTML=`<div class="grid two"><div class="card hero"><p class="eyebrow">ONE MILLION GAP</p><h2>${fmt(d.kpi.gap)}명 남았습니다.</h2><p>현재 속도 비율 ${d.kpi.pace_ratio} · 하루 필요 ${fmt(d.kpi.required_daily)}명</p></div><div class="card"><h2>오늘의 경영 판단</h2><ol class="actions">${d.today_actions.map(x=>`<li>${x}</li>`).join('')}</ol></div></div><div class="card" style="margin-top:16px"><h2>판단 원칙</h2><p>${d.principle}</p><p>첫 3초 유지율 → 평균 시청비율 → 반복/공유 → 구독전환 → 편당 비용 순으로 병목을 찾습니다. 성과가 낮으면 주제를 바로 버리지 않고 훅, 길이, 게시시간, 품질을 분리해 원인을 검증합니다.</p></div>`}
async function blog(){let b=await api('/api/blog');app.innerHTML=`<div class="grid kpis"><div class="card metric"><span class="label">브랜드</span><strong>${b.brands.length}</strong></div><div class="card metric"><span class="label">키워드 후보</span><strong>${b.keywords.length}</strong></div><div class="card metric"><span class="label">검수 대기</span><strong>${b.posts.filter(p=>p.status==='review').length}</strong></div><div class="card metric"><span class="label">예약 발행</span><strong>${b.posts.filter(p=>p.status==='scheduled').length}</strong></div></div><div class="grid two" style="margin-top:16px"><div class="card"><h2>키워드 레이더 <span class="badge demo">${b.mode}</span></h2><table class="table"><thead><tr><th>점수</th><th>키워드</th><th>검색의도</th><th>경쟁</th></tr></thead><tbody>${b.keywords.map(k=>`<tr><td class="score">${k.score}</td><td><b>${k.keyword}</b></td><td>${k.intent}</td><td>${k.competition}</td></tr>`).join('')}</tbody></table></div><div class="card"><h2>블로그 제작 파이프라인</h2>${b.posts.map(p=>`<div class="alert"><b>${p.title}</b><div class="pipeline"><span class="on">${p.status}</span><span>근거 ${p.evidence_count}</span><span>중복 ${p.duplicate_pct}%</span></div></div>`).join('')}</div></div><div class="card" style="margin-top:16px"><h2>자동화 순서</h2><div class="pipeline"><span class="on">브랜드</span><span>키워드</span><span>검색의도</span><span>근거수집</span><span>초안</span><span>사실·중복검수</span><span>승인</span><span>예약발행</span><span>순위·문의보고</span></div><p>블로그와 YouTube 학습 데이터는 브랜드별로 분리하고, 비용·캘린더·알림만 공통으로 사용합니다.</p></div>`}
function calendar(){return `<div class="card"><h2>통합 콘텐츠 캘린더</h2><table class="table"><thead><tr><th>일정</th><th>채널</th><th>콘텐츠</th><th>상태</th></tr></thead><tbody>${data.jobs.map((j,i)=>`<tr><td>${i<5?'오늘':'대기'}</td><td><span class="module-tag youtube">YouTube</span></td><td>${j.topic_slug}</td><td><span class="badge">${j.status}</span></td></tr>`).join('')}</tbody></table></div>`}
const titles={command:'Marketing OS 통합 지휘실',calendar:'콘텐츠 캘린더',topics:'오늘 제작할 TOP20',factory:'쇼츠 제작 공장',quality:'품질 게이트',signals:'채널·트렌드 레이더',report:'100만 달성 보고서',blog:'블로그 스튜디오'};
async function render(){title.textContent=titles[view];if(view==='command')app.innerHTML=command();if(view==='calendar')app.innerHTML=calendar();if(view==='factory')app.innerHTML=factory();if(view==='topics')await topics();if(view==='quality')await quality();if(view==='signals')await signals();if(view==='report')await report();if(view==='blog')await blog()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()});load();
