from pathlib import Path
import json
p=Path('database.rules.json');rules=json.loads(p.read_text(encoding='utf-8'))
project=rules['rules']['rndControl']['projects']['$id'];access="auth != null && root.child('crmCompany/access').child(auth.uid).child('enabled').val() === true && root.child('crmCompany/access').child(auth.uid).child('email').val() === auth.token.email && (root.child('crmCompany/access').child(auth.uid).child('role').val() === 'admin' || root.child('crmCompany/access').child(auth.uid).child('role').val() === 'member')";admin="root.child('crmCompany/access').child(auth.uid).child('role').val() === 'admin'"
project['.write']=False
project['$field']={'.write':access+" && ($field === 'id' || $field === 'title' || $field === 'revision' || $field === 'updatedBy' || $field === 'updatedAt' || $field === 'operationId' || $field === 'currentTRL' || $field === 'targetTRL' || $field === 'items' || $field === 'trl')"}
for field in ['history','assessments']:
 project[field]={'$index':{'.write':access+' && newData.exists() && !data.exists()', '.validate':"newData.hasChildren()"}}
required=['id','hypothesis','question','comparison','population','period','metrics','analysis','success','stop','reviewerUid']
def present(keys):return 'newData.hasChildren('+json.dumps(keys)+')'
def scalar_immutable():return {'.validate':'!data.exists() || newData.val() === data.val()'}
def fixed_object(fields):return {'.validate':present(fields),'$field':{'.validate':'newData.isString() || newData.isNumber() || newData.isBoolean()'},**{k:scalar_immutable() for k in fields}}
review="(auth.uid === newData.child('plan/reviewerUid').val() || "+admin+")"
selfcheck="newData.child('selfReview').val() === (auth.uid === data.child('authorUid').val()) && (auth.uid !== data.child('authorUid').val() || (newData.child('selfReviewReason').isString() && newData.child('selfReviewReason').val().length > 0))"
exp={'.write':access+' && newData.exists()', '.validate':present(['id','plan','authorUid','status','planVersion'])+" && newData.child('id').val() === $record && ((!data.exists() && newData.child('status').val() === 'draft' && newData.child('authorUid').val() === auth.uid && !newData.child('frozenPlan').exists() && !newData.child('approvedBy').exists() && !newData.child('startedAt').exists() && !newData.child('dataset').exists() && ((!newData.child('parentExperimentId').exists() && newData.child('planVersion').val() === 1) || (newData.child('parentExperimentId').exists() && newData.child('planVersion').val() > 1))) || (data.exists() && ((newData.child('status').val() === data.child('status').val()) || (data.child('status').val() === 'draft' && newData.child('status').val() === 'approved' && "+review+" && newData.child('approvedBy').val() === auth.uid && "+selfcheck+") || (data.child('status').val() === 'approved' && newData.child('status').val() === 'running') || (data.child('status').val() === 'running' && newData.child('status').val() === 'closed')))) && (newData.child('status').val() === 'draft' || newData.hasChildren(['frozenPlan','approvedBy','approvedAt','selfReview'])) && ((newData.child('status').val() !== 'running' && newData.child('status').val() !== 'closed') || newData.child('startedAt').isString()) && (newData.child('status').val() !== 'closed' || newData.hasChildren(['dataset','outcome','result','closedAt']))"}
exp['.write'] += " && (!data.exists() || data.child('status').val() !== 'draft' || newData.child('status').val() !== 'draft' || auth.uid === data.child('authorUid').val() || "+admin+")"
parent="newData.parent().parent().child('experiments').child(newData.child('parentExperimentId').val())"
exp['.validate']+=" && (!newData.child('parentExperimentId').exists() || (newData.hasChildren(['parentExperimentId','rootExperimentId','parentPlanVersion','changeReason','appliesTo']) && "+parent+".child('frozenPlan').exists() && ("+parent+".child('status').val() === 'approved' || "+parent+".child('status').val() === 'running' || "+parent+".child('status').val() === 'closed') && newData.child('parentPlanVersion').val() === "+parent+".child('planVersion').val() && newData.child('planVersion').val() === "+parent+".child('planVersion').val() + 1 && newData.child('rootExperimentId').val() === ("+parent+".child('rootExperimentId').exists() ? "+parent+".child('rootExperimentId').val() : "+parent+".child('id').val()) && newData.child('plan/hypothesis').val() === "+parent+".child('plan/hypothesis').val() && newData.child('plan/frameworkVersion').val() === "+parent+".child('plan/frameworkVersion').val() && newData.child('changeReason').isString() && newData.child('changeReason').val().length > 0 && newData.child('appliesTo').isString() && newData.child('appliesTo').val().length > 0))"
for k in ['parentExperimentId','rootExperimentId','parentPlanVersion','changeReason','appliesTo']:
 exp[k]=scalar_immutable()
 exp['.write']+=" && (!data.child('"+k+"').exists() || newData.child('"+k+"').exists())"
for k in ['id','authorUid','planVersion']:exp[k]=scalar_immutable()
exp['plan']={'.validate':"(newData.parent().child('status').val() === 'draft' ? "+present(['id','hypothesis'])+" : "+present(required)+")",'$field':{'.validate':"newData.isString() && (newData.parent().parent().child('status').val() === 'draft' || newData.val().length > 0) && (!data.exists() || newData.val() === data.val() || (data.parent().parent().child('status').val() === 'draft' && newData.parent().parent().child('status').val() === 'draft' && (auth.uid === data.parent().parent().child('authorUid').val() || "+admin+")))"}}
for k in ['id','hypothesis','frameworkVersion']:exp['plan'][k]=scalar_immutable()
exp['frozenPlan']={'.validate':present(required),'$field':{'.validate':"newData.val() === newData.parent().parent().child('plan').child($field).val() && (!data.exists() || newData.val() === data.val())"}}
exp['plan']['.validate']+=" && newData.child('id').val() === newData.parent().child('id').val() && newData.child('hypothesis').val().matches(/^H[0-7]$/)"
exp['frozenPlan']['.validate']+=" && (!newData.parent().child('plan/frameworkVersion').exists() || newData.child('frameworkVersion').exists())"
for k in ['approvedBy','approvedAt','selfReview','selfReviewReason','startedAt','closedAt','result','outcome']:exp[k]=scalar_immutable()
exp['dataset']=fixed_object(['version','url','sampleUnits']);exp['dataset']['.validate']+=" && newData.child('version').isString() && newData.child('version').val().length > 0 && newData.child('url').isString() && newData.child('url').val().matches(/^https?:\\/\\/.+/) && newData.child('sampleUnits').isNumber() && newData.child('sampleUnits').val() > 0 && newData.child('sampleUnits').val() % 1 === 0"
exp['outcome']['.validate']+=" && (newData.val() === 'supported' || newData.val() === 'not_supported' || newData.val() === 'inconclusive' || newData.val() === 'aborted')"
exp['status']={'.validate':True}
for k in ['approvedBy','approvedAt','selfReview','selfReviewReason','startedAt','closedAt','result','outcome','dataset','frozenPlan']:
 exp['.write']+=" && (!data.child('"+k+"').exists() || newData.child('"+k+"').exists())"
exp['$field']={'.validate':False}
lookup="newData.parent().parent().child('experiments').child(newData.child('experimentId').val())"
ev={'.write':access+' && newData.exists()', '.validate':present(['id','experimentId','claim','limitations','source','outcome','authorUid','reviewerUid','status'])+" && newData.child('id').val() === $record && ((!data.exists() && newData.child('status').val() === 'review' && newData.child('authorUid').val() === auth.uid && ("+lookup+".child('status').val() === 'closed' || (newData.child('experimentId').val() === '' && (newData.child('evidenceType').val() === 'literature' || newData.child('evidenceType').val() === 'simulation' || newData.child('evidenceType').val() === 'assumption')))) || (data.exists() && (newData.child('status').val() === data.child('status').val() || (data.child('status').val() === 'review' && newData.child('status').val() === 'approved' && (auth.uid === data.child('reviewerUid').val() || "+admin+") && newData.child('approvedBy').val() === auth.uid && "+selfcheck+")))) && (newData.child('status').val() !== 'approved' || newData.hasChildren(['approvedBy','approvedAt','selfReview']))"}
for k in ['id','experimentId','claim','limitations','outcome','authorUid','reviewerUid','approvedBy','approvedAt','selfReview','selfReviewReason']:ev[k]=scalar_immutable()
ev['source']=fixed_object(['version','url','sampleUnits']);
for k in ['version','url','sampleUnits']:ev['source'][k]['.validate']+=" && newData.val() === newData.parent().parent().parent().parent().child('experiments').child(newData.parent().parent().child('experimentId').val()).child('dataset/"+k+"').val()"
ev['status']={'.validate':True}
for k in ['approvedBy','approvedAt','selfReview','selfReviewReason']:
 ev['.write']+=" && (!data.child('"+k+"').exists() || newData.child('"+k+"').exists())"
ev['$field']={'.validate':False}
dec={'.write':access+' && newData.exists() && !data.exists() && '+admin,'.validate':present(['id','action','reason','evidenceIds','decidedBy','at'])+" && newData.child('id').val() === $record && newData.child('decidedBy').val() === auth.uid && newData.child('reason').isString() && newData.child('reason').val().length > 0 && newData.child('evidenceIds').hasChildren() && (newData.child('action').val() === 'continue' || newData.child('action').val() === 'revise' || newData.child('action').val() === 'stop' || newData.child('action').val() === 'hold')",'evidenceIds':{'$index':{'.validate':"newData.isString() && newData.parent().parent().parent().parent().child('evidence').child(newData.val()).child('status').val() === 'approved'"}}}
project['research']={'experiments':{'$record':exp},'evidence':{'$record':ev},'decisions':{'$record':dec},'history':{'$index':{'.write':access+' && newData.exists() && !data.exists()', '.validate':present(['type','targetId','actorUid','at','sequence'])+" && newData.child('actorUid').val() === auth.uid"}},'$other':{'.write':False}}
hyp={'.write':access+' && newData.exists() && !data.exists()', '.validate':present(['id','projectId','frameworkVersion','code','statement','scope','status','reviewerUid','createdBy'])+" && newData.child('projectId').val() === $id && newData.child('id').val() === $record && newData.child('id').val() === $id + '-' + newData.child('frameworkVersion').val() + '-' + newData.child('code').val() && newData.child('code').isString() && newData.child('code').val().matches(/^H[0-7]$/) && newData.child('status').val() === 'NOT_TESTED' && newData.child('createdBy').val() === auth.uid && newData.child('statement').isString() && newData.child('statement').val().length > 0"}
project['research']['hypotheses']={'$record':hyp}
href="newData.parent().parent().child('hypotheses').child(newData.child('hypothesisId').val())"
ha={'.write':access+' && newData.exists() && !data.exists()', '.validate':present(['id','hypothesisId','projectId','frameworkVersion','status','reason','evidenceIds','sources','assessedBy','at'])+" && newData.child('id').val() === $record && newData.child('projectId').val() === $id && newData.child('assessedBy').val() === auth.uid && "+href+".exists() && newData.child('frameworkVersion').val() === "+href+".child('frameworkVersion').val() && (auth.uid === "+href+".child('reviewerUid').val() || "+admin+") && (newData.child('status').val() === 'SUPPORTED' || newData.child('status').val() === 'NOT_SUPPORTED' || newData.child('status').val() === 'INCONCLUSIVE') && newData.child('reason').isString() && newData.child('reason').val().length > 0 && newData.child('evidenceIds').hasChildren() && newData.child('sources').hasChildren()"}
rbase="newData.parent().parent().parent().parent()"
ebase=rbase+".child('evidence').child(newData.val())"
hbase=rbase+".child('hypotheses').child(newData.parent().parent().child('hypothesisId').val())"
expbase=rbase+".child('experiments').child("+ebase+".child('experimentId').val())"
ha['evidenceIds']={'$index':{'.validate':ebase+".child('status').val() === 'approved' && "+expbase+".child('plan/hypothesis').val() === "+hbase+".child('code').val() && "+expbase+".child('plan/frameworkVersion').val() === "+hbase+".child('frameworkVersion').val()"}}
ha['sources']={'$index':{'.validate':present(['evidenceId','version'])+" && newData.child('version').val() === newData.parent().parent().parent().parent().child('evidence').child(newData.child('evidenceId').val()).child('source/version').val()"}}
project['research']['hypothesisAssessments']={'$record':ha}
ds={'.write':access+' && newData.exists() && !data.exists()', '.validate':present(['id','projectId','experimentId','planRevision','planHash','version','population','selectionRule','exclusions','periodStart','periodEnd','unitType','unitIds','sampleUnits','rowCount','fileCount','versionRefs','frozenBy','frozenAt','manifestHash'])+" && newData.child('id').val() === $record && newData.child('projectId').val() === $id && newData.child('frozenBy').val() === auth.uid && newData.child('manifestHash').isString() && newData.child('manifestHash').val().matches(/^[a-f0-9]{64}$/) && newData.child('sampleUnits').isNumber() && newData.child('sampleUnits').val() > 0 && newData.child('rowCount').isNumber() && newData.child('rowCount').val() >= 0 && newData.child('fileCount').isNumber() && newData.child('fileCount').val() > 0 && newData.child('selectionRule').isString() && newData.child('selectionRule').val().length > 0 && newData.child('exclusions').isString() && newData.child('exclusions').val().length > 0 && newData.parent().parent().child('experiments').child(newData.child('experimentId').val()).child('status').val() === 'running' && newData.child('planRevision').val() === newData.parent().parent().child('experiments').child(newData.child('experimentId').val()).child('planVersion').val()"}
ds['versionRefs']={'$index':{'.validate':present(['versionId','artifactId','providerFileId','sha256','sizeBytes','verifiedAt'])+" && newData.child('sha256').isString() && newData.child('sha256').val().matches(/^[a-f0-9]{64}$/) && newData.child('sizeBytes').isNumber() && newData.child('sizeBytes').val() > 0"}}
project['research']['datasetSnapshots']={'$record':ds}
for k in ['datasetSnapshotId','manifestHash']:
 exp['dataset'][k]=scalar_immutable()
 ev['source'][k]=scalar_immutable()
 ev['source'][k]['.validate']+=" && newData.val() === newData.parent().parent().parent().parent().child('experiments').child(newData.parent().parent().child('experimentId').val()).child('dataset/"+k+"').val()"
 exp['dataset']['.validate']+=" && (!data.child('"+k+"').exists() || newData.child('"+k+"').exists())"
 ev['source']['.validate']+=" && (!newData.parent().parent().parent().child('experiments').child(newData.parent().child('experimentId').val()).child('dataset/"+k+"').exists() || newData.child('"+k+"').exists())"
snapshotRef="newData.parent().parent().parent().child('datasetSnapshots').child(newData.child('datasetSnapshotId').val())"
exp['dataset']['.validate']+=" && (!newData.child('datasetSnapshotId').exists() || ("+snapshotRef+".exists() && newData.child('manifestHash').val() === "+snapshotRef+".child('manifestHash').val() && "+snapshotRef+".child('experimentId').val() === newData.parent().child('id').val() && "+snapshotRef+".child('planRevision').val() === newData.parent().child('planVersion').val() && newData.child('version').val() === "+snapshotRef+".child('version').val() && newData.child('sampleUnits').val() === "+snapshotRef+".child('sampleUnits').val()))"
eb="newData.parent().parent().child('evidence').child(newData.child('targetEvidenceId').val())"
db="newData.parent().parent().child('datasetSnapshots').child(newData.child('datasetSnapshotId').val())"
prior="newData.parent().child(newData.child('priorApprovalId').val())"
public={'.write':access+' && '+admin+' && newData.exists() && !data.exists()', '.validate':present(['id','targetEvidenceId','evidenceId','experimentId','datasetSnapshotId','manifestHash','bundleHash','audience','action','reason','permissionConfirmed','sensitivity','sourceRevision','sequence','approvedBy','at'])+" && newData.child('id').val() === $record && newData.child('approvedBy').val() === auth.uid && newData.child('targetEvidenceId').val() === newData.child('evidenceId').val() && newData.child('audience').val() === 'review' && newData.child('reason').isString() && newData.child('reason').val().length > 0 && newData.child('bundleHash').isString() && newData.child('bundleHash').val().matches(/^[a-f0-9]{64}$/) && newData.child('sequence').val() === newData.parent().parent().parent().child('revision').val() && newData.child('sourceRevision').val() === newData.child('sequence').val() - 1 && ((newData.child('action').val() === 'allow' && newData.child('permissionConfirmed').val() === true && newData.child('sensitivity').val() === 'cleared' && "+eb+".child('status').val() === 'approved' && newData.child('experimentId').val() === "+eb+".child('experimentId').val() && newData.child('datasetSnapshotId').val() === "+eb+".child('source/datasetSnapshotId').val() && newData.child('manifestHash').val() === "+db+".child('manifestHash').val()) || (newData.child('action').val() === 'revoke' && newData.child('permissionConfirmed').val() === false && newData.child('sensitivity').val() === 'revoked' && "+prior+".child('action').val() === 'allow' && "+prior+".child('targetEvidenceId').val() === newData.child('targetEvidenceId').val() && "+prior+".child('bundleHash').val() === newData.child('bundleHash').val()))"}
project['research']['disclosureApprovals']={'$record':public}
for k in ['evidenceType','sourceDescription','measurementConfirmed']:
 ev[k]=scalar_immutable()
 ev['.write']+=" && (!data.child('"+k+"').exists() || newData.child('"+k+"').exists())"
ev['.validate']+=" && (data.exists() || newData.hasChildren(['evidenceType','sourceDescription','measurementConfirmed'])) && (newData.child('evidenceType').val() !== 'measured' || (newData.child('measurementConfirmed').val() === true && newData.child('source/datasetSnapshotId').exists() && newData.child('sourceDescription').isString() && newData.child('sourceDescription').val().length > 0))"
for k in ['version','url','sampleUnits']:
 ev['source'][k]['.validate']="(!data.exists() || newData.val() === data.val()) && (newData.parent().parent().child('experimentId').val() === '' || newData.val() === newData.parent().parent().parent().parent().child('experiments').child(newData.parent().parent().child('experimentId').val()).child('dataset/"+k+"').val())"
for k in ['claimKind','metricResultRefs']:
 ev[k]=scalar_immutable()
 ev['.write']+=" && (!data.child('"+k+"').exists() || newData.child('"+k+"').exists())"
ev['metricResultIds']={'$index':{'.validate':"(!data.exists() || newData.val() === data.val()) && newData.parent().parent().parent().parent().child('metricResults').child(newData.val()).child('experimentId').val() === newData.parent().parent().child('experimentId').val() && newData.parent().parent().parent().parent().child('metricResults').child(newData.val()).child('resultSnapshotId').val() === newData.parent().parent().child('source/datasetSnapshotId').val() && newData.parent().parent().parent().parent().child('metricResults').child(newData.val()).child('percent').isNumber()"}}
ev['.write']+=" && (!data.child('metricResultIds').exists() || newData.child('metricResultIds').exists())"
ev['metricResultIds']['$index']['.validate'] = ev['metricResultIds']['$index']['.validate'].replace('!data.exists()', '(!data.exists() && !data.parent().parent().exists())')
ev['metricResultIds']['$index']['.validate'] = "$index.matches(/^(0|[1-9][0-9]?)$/) && " + ev['metricResultIds']['$index']['.validate']
ev['.write'] += ''.join(" && (!data.child('metricResultIds/%d').exists() || newData.child('metricResultIds/%d').exists())" % (i,i) for i in range(100))
ev['.validate']+=" && (newData.child('evidenceType').val() !== 'measured' || newData.child('claimKind').val() !== 'improvement' || newData.child('metricResultIds').hasChildren())"
m={'.write':access+' && newData.exists() && !data.exists()', '.validate':present(['id','projectId','experimentId','planRevision','name','unit','baseline','result','direction','calculatorVersion','inputMethod','baselineSnapshotId','baselineManifestHash','resultSnapshotId','resultManifestHash','baselineLocator','resultLocator','method','limitations','recordedBy','at'])+" && newData.child('id').val() === $record && newData.child('projectId').val() === $id && newData.child('recordedBy').val() === auth.uid && newData.child('baseline').isNumber() && newData.child('baseline').val() >= 0 && newData.child('result').isNumber() && newData.child('result').val() >= 0 && newData.child('calculatorVersion').val() === 'improvement-v1' && (newData.child('direction').val() === 'lower_better' || newData.child('direction').val() === 'higher_better') && ((newData.child('baseline').val() === 0 && !newData.child('percent').exists() && newData.child('calculationReason').isString()) || (newData.child('baseline').val() > 0 && newData.child('percent').isNumber() && newData.child('percent').val() === (newData.child('direction').val() === 'lower_better' ? newData.child('baseline').val() - newData.child('result').val() : newData.child('result').val() - newData.child('baseline').val()) / newData.child('baseline').val() * 100))"}
for prefix in ['baseline','result']:
 ref="newData.parent().parent().child('datasetSnapshots').child(newData.child('"+prefix+"SnapshotId').val())"
 m['.validate']+=" && "+ref+".exists() && "+ref+".child('experimentId').val() === newData.child('experimentId').val() && "+ref+".child('planRevision').val() === newData.child('planRevision').val() && "+ref+".child('manifestHash').val() === newData.child('"+prefix+"ManifestHash').val()"
project['research']['metricResults']={'$record':m}
context_fields=['id','version','projectId','sourceRevision','frozenBy','frozenAt','frozenAtEpochMs','sourceUpdatedAt','fetchedAt','testMode','reason','manifestHash','snapshotJSON','customerIdsJSON','buildingIdsJSON']
context_checks=[present(context_fields),"newData.child('id').val() === $context", "newData.child('version').val() === 1", "newData.child('projectId').val() === $id", "newData.child('sourceRevision').isNumber() && newData.child('sourceRevision').val() === newData.parent().parent().child('revision').val() - 1", "newData.child('frozenBy').val() === auth.uid", "newData.child('testMode').val() === false", "newData.child('sourceUpdatedAt').isString() && newData.child('sourceUpdatedAt').val() === root.child('crmShared/data/updatedAt').val()", "newData.child('frozenAtEpochMs').isNumber() && newData.child('frozenAtEpochMs').val() >= now - 300000 && newData.child('frozenAtEpochMs').val() <= now + 300000", "newData.child('manifestHash').isString() && newData.child('manifestHash').val().matches(/^[a-f0-9]{64}$/)", "newData.child('reason').isString() && newData.child('reason').val().length > 0 && newData.child('reason').val().length <= 2000 && newData.child('reason').val().matches(/.*[^ ].*/)", "newData.child('snapshotJSON').isString() && newData.child('snapshotJSON').val().length <= 2097152"]
for field in ['frozenAt','fetchedAt','customerIdsJSON','buildingIdsJSON']:
 context_checks.append("newData.child('"+field+"').isString() && newData.child('"+field+"').val().length > 0")
project['crmContexts']={'$context':{'.write':access+' && newData.exists() && !data.exists()', '.validate':' && '.join('('+check+')' for check in context_checks),'$other':{'.validate':False},**{field:{} for field in context_fields}}}
exec(Path('follow-up-rules.py').read_text(encoding='utf-8'))
install_follow_up_rules(project, access, admin)
rnd="root.child('rndAccess').child(auth.uid)"
crm="root.child('crmCompany/access').child(auth.uid)"
extra=" && "+rnd+".child('enabled').val() === true && "+rnd+".child('email').val() === auth.token.email && "+rnd+".child('role').val() === "+crm+".child('role').val()"
def protect(node):
 for k,v in node.items():
  if isinstance(v,dict):protect(v)
  elif k in ['.read','.write'] and isinstance(v,str) and 'rndAccess' not in v:node[k]='('+v+')'+extra
protect(rules['rules']['rndControl'])
admin_access="auth != null && "+crm+".child('enabled').val() === true && "+crm+".child('email').val() === auth.token.email && "+admin
rules['rules']['rndAccess']={'.read':admin_access,'.write':False,'$uid':{'.read':"auth != null && auth.uid === $uid && "+crm+".child('enabled').val() === true && "+crm+".child('email').val() === auth.token.email",'.write':admin_access+' && newData.exists()', '.validate':present(['enabled','email','role','approvedBy','approvedAt','reason'])+" && newData.child('enabled').isBoolean() && newData.child('email').val() === root.child('crmCompany/access').child($uid).child('email').val() && newData.child('role').val() === root.child('crmCompany/access').child($uid).child('role').val() && newData.child('approvedBy').val() === auth.uid && newData.child('approvedAt').isString() && newData.child('reason').isString() && newData.child('reason').val().length > 0",'$other':{'.validate':False},**{k:{} for k in ['enabled','email','role','approvedBy','approvedAt','reason','auditId']}}}
grant_rule=rules['rules']['rndAccess']['$uid']
event="root.child('rndAccessAudit').child($uid).child(newData.child('auditId').val())"
grant_rule['.validate']+=" && newData.child('auditId').isString() && newData.child('auditId').val() !== data.child('auditId').val() && "+event+".child('actorUid').val() === auth.uid && "+event+".child('kind').val() === 'approval-attempt'"
for field in ['enabled','email','role','approvedBy','approvedAt','reason','auditId']:
 grant_rule['.validate']+=" && "+event+".child('after/"+field+"').val() === newData.child('"+field+"').val() && "+event+".child('before/"+field+"').val() === data.child('"+field+"').val()"
audit_current="root.child('rndAccess').child($uid)"
audit_rule={'.write':admin_access+' && !data.exists() && newData.exists()', '.validate':present(['id','targetUid','kind','committed','after','expectedETag','actorUid','at','eventHash'])+" && newData.child('id').val() === $event && newData.child('targetUid').val() === $uid && newData.child('actorUid').val() === auth.uid && newData.child('kind').val() === 'approval-attempt' && newData.child('committed').val() === false && newData.child('eventHash').isString() && newData.child('eventHash').val().matches(/^[a-f0-9]{64}$/) && newData.child('expectedETag').isString() && newData.child('at').isString() && newData.child('after/approvedBy').val() === auth.uid && newData.child('after/enabled').isBoolean() && newData.child('after/reason').isString() && newData.child('after/reason').val().length > 0 && newData.child('after/email').val() === root.child('crmCompany/access').child($uid).child('email').val() && newData.child('after/role').val() === root.child('crmCompany/access').child($uid).child('role').val()"}
for field in ['enabled','email','role','approvedBy','approvedAt','reason','auditId']:
 audit_rule['.validate']+=" && newData.child('before/"+field+"').val() === "+audit_current+".child('"+field+"').val()"
rules['rules']['rndAccessAudit']={'.read':admin_access,'.write':False,'$uid':{'$event':audit_rule}}
visit_binding = "(!data.exists() || newData.child('projectId').val() === data.child('projectId').val())"
visits = rules['rules']['rndControl']['visits']['$id']
if visit_binding not in visits['.validate']:
 visits['.validate'] += ' && ' + visit_binding
visit_fields = ['buildingId','operator','reason','serviceScope','costBasis','evidenceUrl','date']
visit_checks = [present(visit_fields + ['minutes','costs'])]
for field in visit_fields:
 visits['.validate'] = visits['.validate'].replace(" && (newData.child('"+field+"').val().matches(/.*\\S.*/))", '')
 visit_checks.append("newData.child('"+field+"').isString() && newData.child('"+field+"').val().length > 0")
 visit_checks.append("newData.child('"+field+"').val().matches(/.*[^ ].*/)")
for group, fields in [('minutes',['travel','check','work','report','contact','other']),('costs',['labor','transport','materials','outsourcing'])]:
 for field in fields:
  visit_checks.append("newData.child('"+group+"/"+field+"').isNumber() && newData.child('"+group+"/"+field+"').val() >= 0")
visit_sum = ' + '.join("newData.child('minutes/"+field+"').val()" for field in ['travel','check','work','report','contact','other'])
visit_checks.append('('+visit_sum+") >= newData.child('totalMinutes').val() - 0.01 && ("+visit_sum+") <= newData.child('totalMinutes').val() + 0.01")
visit_checks.append("newData.child('evidenceUrl').val().matches(/^https?:\\/\\/.+/)")
visit_checks.append("!newData.child('restorationSourceRevision').exists() || (newData.child('restorationSourceRevision').isNumber() && newData.child('restorationSourceRevision').val() >= 0 && newData.child('restorationSourceRevision').val() % 1 === 0)")
for check in visit_checks:
 if check not in visits['.validate']:
  visits['.validate'] += ' && ('+check+')'
p.write_text(json.dumps(rules,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
