import {describe,it,expect} from 'vitest';
import {createHash} from 'node:crypto';
import {compileCSVImportPublication,createCSVImportRootUpdater} from '../src/rnd/csv-import-transaction.js';
const digest=(value:unknown):string=>createHash('sha256').update(JSON.stringify(value,(_key,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.keys(item).sort().map(key=>[key,item[key]])):item)).digest('hex');
const actor={uid:'u',email:'u@example.test',role:'member' as const},id='11111111-1111-4111-8111-111111111111';
function audit(){const body={kind:'BRING_RND_CSV_IMPORT_AUDIT',version:1,id,projectId:'p',projectRevision:1,status:'LOCAL_DRAFTS_RECORDED',cloudVisitWrites:false,publishedByUID:actor.uid,publishedByEmail:actor.email,publishedByRole:actor.role,publishedAt:'2026-09-17T00:00:00.000Z',sourceSHA256:'a'.repeat(64),importJobSHA256:'b'.repeat(64)};return{...body,integritySHA256:digest(body)};}
const initial=()=>({crmCompany:{access:{u:{enabled:true,email:actor.email,role:'member',mustChangePassword:false}},other:{keep:true}},rndAccess:{u:{enabled:true,email:actor.email,role:'member'}},rndControl:{projects:{p:{id:'p',revision:1}},visits:{keep:{id:'keep'}},other:{original:true}},unrelated:{keep:'company'}});
const compile=(value=audit())=>compileCSVImportPublication({actor,audit:value,digest,validateAudit:async input=>structuredClone(input) as Record<string,unknown>});
describe('trusted CSV ImportJob publication updater',()=>{
 it('appends only immutable audit and preserves all company/project/visit data',async()=>{const publication=await compile(),update=createCSVImportRootUpdater(publication),root=initial(),before=structuredClone(root),next=update(root);expect(next?.rndControl).toEqual({...root.rndControl,importJobs:{[id]:audit()}});expect(next?.crmCompany).toEqual(root.crmCompany);expect(next?.unrelated).toEqual(root.unrelated);expect(root).toEqual(before);});
 it('rechecks current CRM/RND grants and project revision inside every retry',async()=>{const update=createCSVImportRootUpdater(await compile());for(const source of ['crm','rnd'])for(const patch of [{enabled:false},{email:'other@example.test'},{role:'viewer'},{role:'admin'},{mustChangePassword:true}]){const root=initial();Object.assign(source==='crm'?root.crmCompany.access.u:root.rndAccess.u,patch);expect(update(root)).toBeUndefined();}const root=initial();root.rndControl.projects.p.revision=2;expect(update(root)).toBeUndefined();expect(update(null)).toBeUndefined();});
 it('acknowledges exact existing audit without rewriting newer project/other state and rejects collisions',async()=>{const update=createCSVImportRootUpdater(await compile()),next=update(initial())!;expect(update(next)).toEqual(next);const root=structuredClone(next) as any;root.rndControl.projects.p.revision=5;root.unrelated.newer=true;expect(update(root)).toEqual(root);root.rndControl.importJobs[id].status='SHARED_VISITS_APPLIED';expect(update(root)).toBeUndefined();});
 it('accepts only private compiled handles and freezes actor/payload before async validator',async()=>{const inputActor={...actor},inputAudit=audit();let release:(value:Record<string,unknown>)=>void=()=>{};const pending=compileCSVImportPublication({actor:inputActor,audit:inputAudit,digest,validateAudit:input=>new Promise(resolve=>{release=()=>resolve(input as Record<string,unknown>);})});inputActor.uid='other';inputAudit.projectId='other';release({});const handle=await pending;expect(createCSVImportRootUpdater(handle)(initial())).toBeDefined();expect(()=>createCSVImportRootUpdater({...handle})).toThrow(/compiled/);await expect(compile({...audit(),publishedByUID:'other'})).rejects.toThrow();});
});
