import {it,expect} from 'vitest';
import {requireCSVImportPublisher,authenticateCSVImportCallable,CSVImportAuthorizationError} from '../src/rnd/csv-import-auth.js';
const token={uid:'u',email:'u@example.test',authTime:1000},account={uid:'u',email:token.email,disabled:false,tokensValidAfterTime:new Date(900000).toISOString()},grant={enabled:true,email:token.email,role:'member'};
it('CSV publication accepts matching approved members/admins using current stored role',()=>{for(const role of ['member','admin'])expect(requireCSVImportPublisher({token,account,crm:{...grant,role},rnd:{...grant,role}})).toEqual({uid:'u',email:token.email,authTime:1000,role,mustChangePassword:false});});
it('CSV publication rejects invalid account/login and revoked time with typed authentication errors',()=>{for(const patch of [{token:{...token,uid:123}},{token:{...token,authTime:NaN}},{token:{...token,authTime:0}},{token:{...token,authTime:1000.5}},{account:{...account,disabled:true}},{account:{...account,disabled:undefined}},{account:{...account,uid:'other'}},{account:{...account,email:'other@example.test'}},{account:{...account,tokensValidAfterTime:'invalid'}},{account:{...account,tokensValidAfterTime:new Date(1001000).toISOString()}}])expect(()=>requireCSVImportPublisher({token,account,crm:grant,rnd:grant,...patch})).toThrow(expect.objectContaining({code:'unauthenticated'}));});
it('CSV publication rejects missing/disabled/foreign/viewer/mixed/password-change approvals',()=>{for(const patch of [{crm:null},{rnd:null},{crm:{...grant,enabled:false}},{rnd:{...grant,enabled:false}},{crm:{...grant,email:'other@example.test'}},{rnd:{...grant,email:'other@example.test'}},{crm:{...grant,role:'viewer'}},{rnd:{...grant,role:'admin'}},{crm:{...grant,mustChangePassword:true}},{rnd:{...grant,mustChangePassword:true}}])expect(()=>requireCSVImportPublisher({token,account,crm:grant,rnd:grant,...patch})).toThrow(expect.objectContaining({code:'permission-denied'}));});
it('CSV callable captures verified auth_time before awaited account reads and ignores role claims',async()=>{const auth={uid:'u',token:{email:token.email,auth_time:1000,role:'admin'}},reads:string[]=[];let release:(value:unknown)=>void=()=>{};const pending=authenticateCSVImportCallable(auth,{getAccount:uid=>{reads.push(uid);return new Promise(resolve=>release=resolve);},getApprovals:async uid=>{reads.push(uid);return{crm:grant,rnd:grant};}});auth.uid='other';auth.token.email='other@example.test';auth.token.auth_time=2000;release(account);expect(await pending).toEqual({uid:'u',email:token.email,authTime:1000,role:'member',mustChangePassword:false});expect(reads).toEqual(['u','u']);});
it('CSV callable missing verified context refuses before account queries',async()=>{let reads=0;const options={getAccount:async()=>{reads++;return account;},getApprovals:async()=>{reads++;return{crm:grant,rnd:grant};}};for(const auth of [undefined,{uid:'u',token:{}},{uid:'../u',token:{email:token.email,auth_time:1000}}])await expect(authenticateCSVImportCallable(auth,options)).rejects.toBeInstanceOf(CSVImportAuthorizationError);expect(reads).toBe(0);});
it('CSV callable preserves service outages and permits equality at revoked/login timestamp boundary',async()=>{const outage=Error('account service unavailable');await expect(authenticateCSVImportCallable({uid:'u',token:{email:token.email,auth_time:1000}},{getAccount:async()=>{throw outage;},getApprovals:async()=>({crm:grant,rnd:grant})})).rejects.toBe(outage);expect(requireCSVImportPublisher({token,account:{...account,tokensValidAfterTime:new Date(1000000).toISOString()},crm:grant,rnd:grant}).authTime).toBe(1000);});
