import {describe,it,expect} from 'vitest';
import {createRestoreRootUpdater,runRestoreRootTransaction} from '../src/rnd/restore-transaction.js';
const actor={uid:'a',email:'a@example.test'},operationId='11111111-1111-4111-8111-111111111111';
const old={projects:{p:{id:'p',title:'Existing'}}},next={...old,projects:{...old.projects,q:{id:'q'}},restoreApprovals:{[operationId]:{id:operationId,actorUid:'a'}}};
const hash=(value:unknown)=>JSON.stringify(value);const mutation={value:next,operationId,audit:next.restoreApprovals[operationId],contentSHA256:hash(next)};
const initial=()=>({crmCompany:{access:{a:{enabled:true,email:actor.email,role:'admin'}}},rndAccess:{a:{enabled:true,email:actor.email,role:'admin'}},rndControl:old,other:{keep:true}});
describe('trusted server restore transaction updater',()=>{
 it('preserves unrelated company data and applies compiled mutation only from matching snapshot',()=>{const root=initial(),before=JSON.stringify(root);const update=createRestoreRootUpdater({actor,mutation,expectedSnapshotSHA256:hash(old),digest:hash});const result=update(root);expect(result?.rndControl).toEqual(next);expect(result?.other).toEqual(root.other);expect(JSON.stringify(root)).toBe(before);expect(update({...root,rndControl:{...old,changed:true}})).toBeUndefined();});
 it('rechecks CRM/R&D approvals inside every transaction retry and rejects revocation/mismatch',()=>{const update=createRestoreRootUpdater({actor,mutation,expectedSnapshotSHA256:hash(old),digest:hash});for(const field of ['crmCompany','rndAccess']){const root=initial();if(field==='crmCompany')root.crmCompany.access.a.enabled=false;else root.rndAccess.a.enabled=false;expect(update(root)).toBeUndefined();}const root=initial();root.rndAccess.a.role='member';expect(update(root)).toBeUndefined();root.rndAccess.a.role='admin';root.crmCompany.access.a.email='other@example.test';expect(update(root)).toBeUndefined();});
 it('accepts exact applied result idempotently but rejects altered acknowledgement state and forged actor',()=>{const update=createRestoreRootUpdater({actor,mutation,expectedSnapshotSHA256:hash(old),digest:hash});const applied={...initial(),rndControl:next};expect(update(applied)).toEqual(applied);expect(update({...applied,rndControl:{...next,changed:true}})).toBeUndefined();expect(()=>createRestoreRootUpdater({actor:{...actor,uid:'other'},mutation,expectedSnapshotSHA256:hash(old),digest:hash})).toThrow(/actor/);});
});

it('transaction adapter retains a warm root listener until commit and releases only its own listener',async()=>{const calls:string[]=[];let own:unknown;const root={on:(_event:string,callback:()=>void)=>{calls.push('listen');own=callback;queueMicrotask(callback);},off:(_event:string,callback:unknown)=>{expect(callback).toBe(own);calls.push('release');},transaction:async()=>{calls.push('commit');return{committed:true,snapshot:{val:()=>next}};}};const result=await runRestoreRootTransaction(root as never,()=>initial());expect(result.committed).toBe(true);expect(calls).toEqual(['listen','commit','release']);});

it('transaction adapter releases listener when commit fails',async()=>{const calls:string[]=[];const root={on:(_event:string,callback:()=>void)=>queueMicrotask(callback),off:()=>calls.push('release'),transaction:async()=>{throw Error('network failure');}};await expect(runRestoreRootTransaction(root as never,()=>initial())).rejects.toThrow('network failure');expect(calls).toEqual(['release']);});
it('applies original restore compiler with dual approvals and exact snapshot CAS',async()=>{const {createRequire}=await import('node:module'),{createHash}=await import('node:crypto'),require=createRequire(import.meta.url),compile=require('../../desktop-crm/src/rnd-control/original-restore-mutation.js').createOriginalRestoreMutation,fingerprint=require('../../desktop-crm/src/rnd-control/repository.js').researchFingerprint,{createProject}=await import(new URL('../../desktop-crm/src/rnd-control/portfolio.mjs',import.meta.url).href),sha=(x:string)=>createHash('sha256').update(x).digest('hex'),digest=(x:unknown)=>sha(fingerprint(x)),at=new Date().toISOString(),metadata={projects:[createProject('restored','Original restored draft')],visits:[],importJobs:[],restoredImportAudits:[],selectedId:'restored'},archivalMetadataJSON='{}',preparation={kind:'BRING_RND_ORIGINAL_RESTORE_PREPARATION',version:1,derivedByUID:actor.uid,derivedAt:at,sourceZipSHA256:'a'.repeat(64),mappingSHA256:'b'.repeat(64),metadata,metadataSHA256:sha(JSON.stringify(metadata)),archivalMetadataJSON,archivalMetadataSHA256:sha(archivalMetadataJSON),additionalCollectionCount:0,additionalMetadataDisposition:'NONE',databaseWrites:false,cloudWrites:false,restoreReady:false,originVerified:false},snapshot={actorUid:actor.uid,etag:'current',value:old,contentSHA256:digest(old)},approval={kind:'BRING_RND_ORIGINAL_RESTORE_APPROVAL',version:1,approved:true,actorUid:actor.uid,operationId,at,reason:'Reviewed original restore',preparedSHA256:sha(JSON.stringify(preparation)),snapshotSHA256:snapshot.contentSHA256},compiled=await compile({snapshot,preparation,approval}),update=createRestoreRootUpdater({actor,mutation:compiled,expectedSnapshotSHA256:snapshot.contentSHA256,digest}),root=initial(),result=update(root);expect(result?.rndControl).toEqual(compiled.value);expect(result?.other).toEqual(root.other);expect(update(result)).toEqual(result);const revoked=initial();revoked.rndAccess.a.enabled=false;expect(update(revoked)).toBeUndefined();expect(update({...initial(),rndControl:{...old,changed:true}})).toBeUndefined();});
