import {it,expect} from 'vitest';import {createRestoreApprovalSession,createRestoreSessionUpdater,createRestoreSessionStoreUpdater} from '../src/rnd/restore-session.js';
const actor={uid:'a',email:'a@example.test',authTime:1000},id='11111111-1111-4111-8111-111111111111',digest=(v:unknown)=>JSON.stringify(v);const old={projects:{}},audit={id,actorUid:'a'},value={projects:{q:{id:'q'}},restoreApprovals:{[id]:audit}},mutation={value,operationId:id,audit,contentSHA256:digest(value)};
function harness(){let now=1000;const session=createRestoreApprovalSession({actor,mutation,expectedSnapshotSHA256:digest(old),now});const root={crmCompany:{access:{a:{enabled:true,email:actor.email,role:'admin'}}},rndAccess:{a:{enabled:true,email:actor.email,role:'admin'}},rndControl:old,rndRestoreSessions:{a:{[id]:session}},other:{keep:true}};return{root,session,update:createRestoreSessionUpdater({actor,sessionId:id,digest,now:()=>now}),advance:()=>{now=session.expiresAt;}};}
it('approval session commits restore and consumption atomically, preserving stored request and unrelated data',()=>{const h=harness(),result=h.update(h.root);expect(result?.rndControl).toEqual(value);expect((result?.rndRestoreSessions as any).a[id].state).toBe('COMMITTED');expect(h.root.rndRestoreSessions.a[id].state).toBe('PENDING');expect(h.update(result)).toEqual(result);});
it('expired and other-user approval sessions cannot commit',()=>{const h=harness();h.advance();expect(h.update(h.root)).toBeUndefined();const other=createRestoreSessionUpdater({actor:{uid:'other',email:'other@example.test',authTime:1000},sessionId:id,digest,now:()=>1000});expect(other(h.root)).toBeUndefined();});
it('permission revocation and snapshot changes refuse session execution without consumption',()=>{const h=harness();h.root.rndAccess.a.enabled=false;expect(h.update(h.root)).toBeUndefined();h.root.rndAccess.a.enabled=true;expect(h.update({...h.root,rndControl:{...old,changed:true}})).toBeUndefined();expect(h.session.state).toBe('PENDING');});

it('committed approval never reapplies after its restored data is replaced or rolled back',()=>{const h=harness(),committed=h.update(h.root)!;expect(h.update({...committed,rndControl:old})).toBeUndefined();expect(h.update({...committed,rndControl:{...value,changed:true}})).toBeUndefined();});

it('a new Firebase login of the same user cannot consume a prior login approval',()=>{const h=harness(),otherLogin=createRestoreSessionUpdater({actor:{...actor,authTime:1001},sessionId:id,digest,now:()=>1000});expect(otherLogin(h.root)).toBeUndefined();});
it('committed sessions keep a compact receipt and immutable audit instead of a duplicate company snapshot',()=>{const h=harness(),result=h.update(h.root)!,receipt=(result.rndRestoreSessions as any).a[id];expect(receipt.mutation).toBeUndefined();expect(receipt.audit).toEqual(audit);expect(receipt.contentSHA256).toBe(digest(value));expect(h.update(result)).toEqual(result);const revoked=structuredClone(result) as any;revoked.rndAccess.a.enabled=false;expect(h.update(revoked)).toBeUndefined();});
it('session storage prunes expired pending and day-old receipts while retaining fresh approvals',()=>{const h=harness(),time=90000000,update=createRestoreSessionStoreUpdater({session:createRestoreApprovalSession({actor,mutation,expectedSnapshotSHA256:digest(old),now:time}),now:()=>time});const second='22222222-2222-4222-8222-222222222222';const expired={...h.session,id:second};const owner={[second]:expired};const result=update(owner);expect(result).toHaveProperty(id);expect(result).not.toHaveProperty(second);expect(owner[second]).toEqual(expired);});
it('storage refuses overwrite, excessive pending requests and oversized metadata atomically',()=>{const h=harness(),update=createRestoreSessionStoreUpdater({session:h.session,now:()=>1000});expect(update({[id]:h.session})).toBeUndefined();const owner:any={};for(let i=0;i<20;i++){const key=`00000000-0000-4000-8000-${String(i).padStart(12,'0')}`;owner[key]={...h.session,id:key};}expect(update(owner)).toBeUndefined();const huge=structuredClone(h.session);(huge.mutation.value as any).padding='x'.repeat(32*1024*1024);expect(createRestoreSessionStoreUpdater({session:huge,now:()=>1000})(null)).toBeUndefined();});
it('store cleanup retains recent receipts and fresh pending requests, removes day-old receipts, and never changes durable audit',()=>{const h=harness(),applied=h.update(h.root)!,committed=(applied.rndRestoreSessions as any).a[id],time=90000000,newId='22222222-2222-4222-8222-222222222222',freshId='33333333-3333-4333-8333-333333333333',recentId='44444444-4444-4444-8444-444444444444';const incoming={...h.session,id:newId,createdAt:time,expiresAt:time+600000},fresh={...h.session,id:freshId,createdAt:time-1,expiresAt:time-1+600000},recent={...committed,id:recentId,createdAt:time-100,expiresAt:time-100+600000,committedAt:time-99,audit:{...audit,id:recentId}};const result=createRestoreSessionStoreUpdater({session:incoming,now:()=>time})({[id]:committed,[freshId]:fresh,[recentId]:recent});expect(Object.keys(result!)).toEqual([freshId,recentId,newId]);expect(result![freshId]).toEqual(fresh);expect(result![recentId]).toEqual(recent);expect((applied.rndControl as any).restoreApprovals[id]).toEqual(audit);});
it('session store optimistic retries use immutable source and current clock',()=>{const h=harness();let time=1000;const update=createRestoreSessionStoreUpdater({session:h.session,now:()=>time}),result=update(null) as any;result[id].mutation.value.changed=true;expect((update(null) as any)[id].mutation.value.changed).toBeUndefined();time=h.session.expiresAt;expect(update(null)).toBeUndefined();});
it('storage includes incoming request in the total count and combined byte quota',()=>{const h=harness(),applied=h.update(h.root)!,base=(applied.rndRestoreSessions as any).a[id],owner:any={};for(let i=0;i<199;i++){const key=`00000000-0000-4000-8000-${String(i).padStart(12,'0')}`;owner[key]={...base,id:key,audit:{...audit,id:key}};}const update=createRestoreSessionStoreUpdater({session:h.session,now:()=>1000});expect(Object.keys(update(owner)!)).length(200);const extra='99999999-9999-4999-8999-999999999999';owner[extra]={...base,id:extra,audit:{...audit,id:extra}};expect(update(owner)).toBeUndefined();const huge=structuredClone(h.session);(huge.mutation.value as any).padding='x'.repeat(17*1024*1024);const other='22222222-2222-4222-8222-222222222222';expect(createRestoreSessionStoreUpdater({session:huge,now:()=>1000})({[other]:{...huge,id:other}})).toBeUndefined();});
it('root approval storage rechecks live dual grants and snapshot before adding server session atomically',async()=>{const {createRestoreSessionRootStoreUpdater}=await import('../src/rnd/restore-session.js'),h=harness(),root=structuredClone(h.root);delete (root as any).rndRestoreSessions;const update=createRestoreSessionRootStoreUpdater({actor,session:h.session,digest,now:()=>1000}),stored=update(root);expect((stored?.rndRestoreSessions as any).a[id]).toEqual(h.session);expect(stored?.rndControl).toEqual(root.rndControl);expect(stored?.other).toEqual(root.other);expect(update(stored)).toBeUndefined();expect(update({...root,rndControl:{changed:true}})).toBeUndefined();for(const field of ['crmCompany','rndAccess']){const revoked=structuredClone(root);if(field==='crmCompany')revoked.crmCompany.access.a.enabled=false;else revoked.rndAccess.a.enabled=false;expect(update(revoked)).toBeUndefined();}expect(()=>createRestoreSessionRootStoreUpdater({actor:{...actor,authTime:1001},session:h.session,digest,now:()=>1000})).toThrow(/binding/);});
