import {it,expect} from 'vitest';
import {mkdtemp,cp,mkdir,readFile,writeFile,rm,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {fileURLToPath,pathToFileURL} from 'node:url';
const run=promisify(execFile),source=new URL('../',import.meta.url);
async function fixture(){const folder=await mkdtemp(join(tmpdir(),'bring-rnd-package-'));await mkdir(join(folder,'scripts'));await cp(new URL('scripts/',source),join(folder,'scripts'),{recursive:true});await mkdir(join(folder,'lib/rnd'),{recursive:true});await cp(new URL('lib/rnd/runtime/',source),join(folder,'lib/rnd/runtime'),{recursive:true});await cp(new URL('lib/rnd/csv-runtime/',source),join(folder,'lib/rnd/csv-runtime'),{recursive:true});await cp(new URL('lib/rnd/original-runtime/',source),join(folder,'lib/rnd/original-runtime'),{recursive:true});return folder;}
it('uploaded Functions package validates its runtime without the CRM checkout',async()=>{const folder=await fixture();try{const result=await run(process.execPath,[join(folder,'scripts/verify-rnd-runtime.mjs')],{cwd:folder});expect(result.stdout).toMatch(/PASS verified/);}finally{await rm(folder,{recursive:true,force:true});}});
it('isolated Functions source compiles and loads its packaged restore runtime and CSV runtimes without desktop sources',async()=>{const folder=await fixture();try{
 await cp(new URL('src/',source),join(folder,'src'),{recursive:true});for(const name of ['package.json','tsconfig.json'])await cp(new URL(name,source),join(folder,name));
 await symlink(fileURLToPath(new URL('node_modules/',source)),join(folder,'node_modules'),process.platform==='win32'?'junction':'dir');
 const pkg=JSON.parse(await readFile(join(folder,'package.json'),'utf8'));expect(pkg.scripts['gcp-build']).toBe('tsc -p tsconfig.json && node scripts/verify-rnd-runtime.mjs && node scripts/verify-csv-runtime.mjs && node scripts/verify-original-runtime.mjs');
 await run(process.execPath,[fileURLToPath(new URL('node_modules/typescript/lib/tsc.js',source)),'-p',join(folder,'tsconfig.json')],{cwd:folder});
 await run(process.execPath,[join(folder,'scripts/verify-rnd-runtime.mjs')],{cwd:folder});
 const csvProof=await run(process.execPath,[join(folder,'scripts/verify-csv-runtime.mjs')],{cwd:folder});expect(csvProof.stdout).toMatch(/PASS verified 9 packaged CSV/);
 const originalProof=await run(process.execPath,[join(folder,'scripts/verify-original-runtime.mjs')],{cwd:folder});expect(originalProof.stdout).toMatch(/PASS verified 21 packaged original restore/);
 const originalCompiler=pathToFileURL(join(folder,'lib/rnd/original-runtime/rnd-control/original-restore-mutation.js')).href;const originalResult=await run(process.execPath,['--input-type=module','-e',`import {createOriginalRestoreMutation} from ${JSON.stringify(originalCompiler)};try{await createOriginalRestoreMutation({snapshot:null,preparation:null,approval:null});throw Error('invalid approval accepted');}catch(error){if(error.message==='invalid approval accepted')throw error;console.log('PASS rejected');}`],{cwd:folder});expect(originalResult.stdout).toMatch(/PASS rejected/);
 const url=pathToFileURL(join(folder,'lib/rnd/restore-runtime.js')).href;const result=await run(process.execPath,['--input-type=module','-e',`import {createServerRestoreRuntime} from ${JSON.stringify(url)};console.log(createServerRestoreRuntime().digest({projects:{}}));`],{cwd:folder});expect(result.stdout.trim()).toMatch(/^[0-9a-f]{64}$/);
 const csvUrl=pathToFileURL(join(folder,'lib/rnd/csv-import-runtime.js')).href;const csvResult=await run(process.execPath,['--input-type=module','-e',`import {createServerCSVRuntime} from ${JSON.stringify(csvUrl)};const runtime=createServerCSVRuntime();console.log(runtime.digest({projects:{}}));try{await runtime.validateAudit({});throw Error('invalid audit accepted');}catch(error){if(error.message==='invalid audit accepted')throw error;}`],{cwd:folder});expect(csvResult.stdout.trim()).toMatch(/^[0-9a-f]{64}$/);
 }finally{await rm(folder,{recursive:true,force:true});}},20000);
it('packaged runtime verification refuses altered, missing and uninventoried dependencies',async()=>{for(const kind of ['altered','missing','uninventoried']){const folder=await fixture();try{const file=join(folder,'lib/rnd/runtime/shared-restore-preview.js');if(kind==='altered')await writeFile(file,'module.exports={}');if(kind==='missing')await rm(file);if(kind==='uninventoried'){const manifestFile=join(folder,'lib/rnd/runtime/SOURCE_MANIFEST.json'),manifest=JSON.parse(await readFile(manifestFile,'utf8'));delete manifest.files['shared-restore-preview.js'];await writeFile(manifestFile,JSON.stringify(manifest));}await expect(run(process.execPath,[join(folder,'scripts/verify-rnd-runtime.mjs')],{cwd:folder})).rejects.toThrow();}finally{await rm(folder,{recursive:true,force:true});}}});
it('original runtime inventory rejects altered, missing and uninventoried compiler dependencies',async()=>{for(const kind of ['altered','missing','uninventoried']){const folder=await fixture();try{const file=join(folder,'lib/rnd/original-runtime/core.js');if(kind==='altered')await writeFile(file,'module.exports={}');if(kind==='missing')await rm(file);if(kind==='uninventoried'){const manifestFile=join(folder,'lib/rnd/original-runtime/SOURCE_MANIFEST.json'),manifest=JSON.parse(await readFile(manifestFile,'utf8'));delete manifest.files['core.js'];await writeFile(manifestFile,JSON.stringify(manifest));}await expect(run(process.execPath,[join(folder,'scripts/verify-original-runtime.mjs')],{cwd:folder})).rejects.toThrow();}finally{await rm(folder,{recursive:true,force:true});}}});
