import {it,expect} from 'vitest';
import {prepareOriginalApprovalSession} from '../src/rnd/original-approval.js';
import {createServerRestoreRuntime} from '../src/rnd/restore-runtime.js';
import {createHash} from 'node:crypto';
const actor={uid:'a',email:'a@example.test',authTime:1000,role:'admin' as const,mustChangePassword:false as const};
async function fixture(){const runtime=createServerRestoreRuntime(new URL('../lib/rnd/runtime/',import.meta.url)),{createProject}=await import(new URL('../../desktop-crm/src/rnd-control/portfolio.mjs',import.meta.url).href),now=Date.now(),at=new Date(now).toISOString(),sha=(x:string)=>createHash('sha256').update(x).digest('hex'),metadata={projects:[createProject('restored','Recovered')],visits:[],importJobs:[],restoredImportAudits:[],selectedId:'restored'},preparation={kind:'BRING_RND_ORIGINAL_RESTORE_PREPARATION',version:1,derivedByUID:actor.uid,derivedAt:at,metadata,metadataSHA256:sha(JSON.stringify(metadata)),sourceZipSHA256:'a'.repeat(64),mappingSHA256:'b'.repeat(64),archivalMetadataJSON:'{}',archivalMetadataSHA256:sha('{}'),additionalCollectionCount:0,additionalMetadataDisposition:'NONE',databaseWrites:false,cloudWrites:false,restoreReady:false,originVerified:false},value={projects:{},importJobs:{existing:{unchanged:true}}},snapshot={actorUid:actor.uid,etag:'current',value,contentSHA256:runtime.digest(value)};return{runtime,now,preparation,snapshot};}
it('server mints approval and session from trusted fresh preparation and snapshot preserving existing data',async()=>{const f=await fixture(),calls:string[]=[],result=await prepareOriginalApprovalSession({reason:'Reviewed originals',additionalMetadataAction:'NONE'},{authenticate:async()=>{calls.push('auth');return actor;},prepare:async()=>{calls.push('prepare');return f.preparation;},readSnapshot:async()=>{calls.push('snapshot');return f.snapshot;},runtime:f.runtime,now:()=>f.now});expect(calls).toEqual(['auth','prepare','auth','snapshot','auth','auth']);expect(result.actorAuthTime).toBe(actor.authTime);expect(result.mutation.value.importJobs).toEqual(f.snapshot.value.importJobs);expect(result.mutation.audit.kind).toBe('original-restore');expect(result.state).toBe('PENDING');expect(result.expectedSnapshotSHA256).toBe(f.snapshot.contentSHA256);});
it('rejects changed login and unapproved request fields before issuing a session',async()=>{const f=await fixture();let calls=0;await expect(prepareOriginalApprovalSession({reason:'Review',additionalMetadataAction:'NONE'},{authenticate:async()=>({...actor,authTime:++calls===1?1000:1001}),prepare:async()=>f.preparation,readSnapshot:async()=>f.snapshot,runtime:f.runtime,now:()=>f.now})).rejects.toThrow(/login/);calls=0;await expect(prepareOriginalApprovalSession({reason:'Review',additionalMetadataAction:'NONE',approval:{approved:true}},{authenticate:async()=>{calls++;return actor;},prepare:async()=>f.preparation,readSnapshot:async()=>f.snapshot,runtime:f.runtime,now:()=>f.now})).rejects.toThrow(/request/);expect(calls).toBe(0);});
it('server-minted original approval is stored and consumed by the shared atomic session updater',async()=>{const f=await fixture(),{createRestoreSessionStoreUpdater,createRestoreSessionUpdater}=await import('../src/rnd/restore-session.js'),session=await prepareOriginalApprovalSession({reason:'Reviewed originals',additionalMetadataAction:'NONE'},{authenticate:async()=>actor,prepare:async()=>f.preparation,readSnapshot:async()=>f.snapshot,runtime:f.runtime,now:()=>f.now}),owner=createRestoreSessionStoreUpdater({session,now:()=>f.now})(null),grant={enabled:true,email:actor.email,role:'admin'},root={crmCompany:{access:{a:grant}},rndAccess:{a:grant},rndControl:f.snapshot.value,rndRestoreSessions:{a:owner},unrelated:{keep:true}},update=createRestoreSessionUpdater({actor,sessionId:session.id,digest:f.runtime.digest,now:()=>f.now}),result=update(root);expect(result?.rndControl).toEqual(session.mutation.value);expect(result?.unrelated).toEqual(root.unrelated);expect(update(result)).toEqual(result);expect(update({...root,rndAccess:{a:{...grant,enabled:false}}})).toBeUndefined();expect(createRestoreSessionUpdater({actor,sessionId:session.id,digest:f.runtime.digest,now:()=>session.expiresAt})(root)).toBeUndefined();});
