import {compileCSVImportPublication} from '../src/rnd/csv-import-transaction.js';
import {it,expect,vi} from 'vitest';
import {publishCSVImport,CSVImportCommitUncertainError} from '../src/rnd/csv-import-publish.js';
import {createHash} from 'node:crypto';
const digest=(v:unknown)=>createHash('sha256').update(JSON.stringify(v,(_k,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x)).digest('hex');
const actor={uid:'u',email:'u@example.test',role:'member' as const,authTime:1,mustChangePassword:false as const},id='11111111-1111-4111-8111-111111111111';
function fixture(){const job={id,actorUid:'u',actorEmail:actor.email,source:{projectId:'p'}};const body={kind:'BRING_RND_CSV_IMPORT_AUDIT',version:1,id,projectId:'p',projectRevision:1,status:'LOCAL_DRAFTS_RECORDED',cloudVisitWrites:false,publishedByUID:'u',publishedByEmail:actor.email,publishedByRole:'member',importJobSHA256:digest(job),driveReference:{providerFileId:'file'}};const audit={...body,integritySHA256:digest(body)};const state:any={crmCompany:{access:{u:{enabled:true,email:actor.email,role:'member'}}},rndAccess:{u:{enabled:true,email:actor.email,role:'member'}},rndControl:{projects:{p:{id:'p',revision:8}},importJobs:{[id]:audit},visits:{keep:true}},other:{keep:true}};const deps={authenticate:vi.fn(async()=>actor),readAudit:vi.fn(async()=>audit),runtime:{validateJob:async()=>job,validateAudit:async(v:any)=>v,digest} as any,prepare:vi.fn(),transaction:vi.fn(async(update:any)=>{const next=update(state);return{committed:!!next,value:next??state};})};return{job,audit,state,deps};}
it('same owned job replays original audit without new time/Drive preparation or visit changes',async()=>{const f=fixture(),before=structuredClone(f.state);const result=await publishCSVImport({job:f.job,providerFileId:'file',driveToken:'fixture-token'},f.deps);expect(result).toEqual({id,projectId:'p',status:'RECORDED',contentSHA256:digest(f.audit)});expect(f.deps.prepare).not.toHaveBeenCalled();expect(f.state).toEqual(before);});
it('changed job or file rejects before transaction',async()=>{const f=fixture();f.audit.importJobSHA256='changed';await expect(publishCSVImport({job:f.job,providerFileId:'file',driveToken:'fixture-token'},f.deps)).rejects.toThrow();expect(f.deps.transaction).not.toHaveBeenCalled();const g=fixture();await expect(publishCSVImport({job:g.job,providerFileId:'other',driveToken:'fixture-token'},g.deps)).rejects.toThrow();});
it('current grants inside transaction deny replay and uncertain transport is distinguishable',async()=>{const f=fixture();f.state.rndAccess.u.enabled=false;await expect(publishCSVImport({job:f.job,providerFileId:'file',driveToken:'fixture-token'},f.deps)).rejects.toThrow('not committed');const g=fixture();g.deps.transaction.mockRejectedValueOnce(Error('connection lost'));await expect(publishCSVImport({job:g.job,providerFileId:'file',driveToken:'fixture-token'},g.deps)).rejects.toBeInstanceOf(CSVImportCommitUncertainError);});

it('new publication appends only its audit and rejects project race before write',async()=>{const f=fixture();f.deps.readAudit.mockResolvedValueOnce(null as any);delete f.state.rndControl.importJobs;f.state.rndControl.projects.p.revision=1;f.deps.prepare.mockImplementation(async()=>compileCSVImportPublication({actor,audit:f.audit,validateAudit:f.deps.runtime.validateAudit,digest}));let observed:any;f.deps.transaction.mockImplementation(async(update:any)=>{observed=update(f.state);return{committed:!!observed,value:observed??f.state};});await publishCSVImport({job:f.job,providerFileId:'file',driveToken:'fixture-token'},f.deps);expect(observed.rndControl.importJobs[id]).toEqual(f.audit);expect(observed.rndControl.visits).toEqual(f.state.rndControl.visits);expect(observed.other).toEqual(f.state.other);const g=fixture();g.deps.readAudit.mockResolvedValueOnce(null as any);delete g.state.rndControl.importJobs;g.deps.prepare.mockImplementation(async()=>compileCSVImportPublication({actor,audit:g.audit,validateAudit:g.deps.runtime.validateAudit,digest}));await expect(publishCSVImport({job:g.job,providerFileId:'file',driveToken:'fixture-token'},g.deps)).rejects.toThrow('not committed');});

it('same-job concurrent winner is acknowledged using original audit without timestamp overwrite',async()=>{const f=fixture();f.deps.readAudit.mockResolvedValueOnce(null as any);f.deps.prepare.mockImplementation(async()=>{const body={...f.audit,publishedAt:'2026-09-17T00:02:00.000Z'};const {integritySHA256,...fields}=body;return compileCSVImportPublication({actor,audit:{...fields,integritySHA256:digest(fields)},validateAudit:f.deps.runtime.validateAudit,digest});});const result=await publishCSVImport({job:f.job,providerFileId:'file',driveToken:'fixture-token'},f.deps);expect(result.contentSHA256).toBe(digest(f.audit));expect(f.deps.transaction).toHaveBeenCalledTimes(2);expect(f.state.rndControl.importJobs[id]).toEqual(f.audit);});
