import {it,expect,vi} from 'vitest';
import {prepareCSVImportPublication} from '../src/rnd/csv-import-publication.js';
const actor={uid:'u',email:'u@example.test',authTime:1,role:'member' as const,mustChangePassword:false as const};
function fixture(){const job={id:'11111111-1111-4111-8111-111111111111',actorUid:actor.uid,actorEmail:actor.email,source:{projectId:'p',sha256:'a'.repeat(64),sizeBytes:6}};const clear=vi.fn(),connect=vi.fn(async()=>({})),verifyVersion=vi.fn(async()=>({projectId:'p',artifactId:'csv-import-original',versionId:job.id,providerFileId:'file',sha256:'a'.repeat(64),sizeBytes:6,status:'VERIFIED',verifiedAt:'2026-09-17T00:00:00.000Z'}));const dependencies={authenticate:vi.fn(async()=>actor),readVisits:vi.fn(async()=>[]),readProject:vi.fn(async()=>({id:'p',revision:2})),now:()=> '2026-09-17T00:00:00.000Z',runtime:{verifySourceDerivation:vi.fn(async()=>{}),validateJob:vi.fn(async()=>job),companyDrive:()=>({connect,verifyVersion,verifyCSVOriginal:async(input:any)=>({reference:await verifyVersion(input),bytes:new Uint8Array()}),clear}),buildAudit:vi.fn(async(input:any)=>input),validateAudit:vi.fn(),digest:vi.fn()},compile:vi.fn(async(input:any)=>({id:input.audit.job.id,projectId:'p',contentSHA256:'b'.repeat(64)}))};return{job,clear,connect,verifyVersion,dependencies};}
it('server preparation binds verified identity, actual Drive result and server project/time; clears token',async()=>{const f=fixture();const result=await prepareCSVImportPublication({job:f.job,providerFileId:'file',driveToken:'fixture-token'},f.dependencies);expect(result.projectId).toBe('p');expect(f.dependencies.authenticate).toHaveBeenCalledTimes(2);expect(f.dependencies.runtime.buildAudit).toHaveBeenCalledWith(expect.objectContaining({publisher:actor,projectRevision:2,at:'2026-09-17T00:00:00.000Z'}));expect(f.clear).toHaveBeenCalledOnce();});
it('changed approval after Drive verification refuses compilation and clears token',async()=>{const f=fixture();f.dependencies.authenticate.mockResolvedValueOnce(actor).mockResolvedValueOnce({...actor,uid:'other'});await expect(prepareCSVImportPublication({job:f.job,providerFileId:'file',driveToken:'fixture-token'},f.dependencies)).rejects.toThrow();expect(f.dependencies.compile).not.toHaveBeenCalled();expect(f.clear).toHaveBeenCalledOnce();});
it('untrusted fields and source-owner mismatch refuse Drive calls',async()=>{const f=fixture();await expect(prepareCSVImportPublication({job:f.job,providerFileId:'file',driveToken:'fixture-token',publisher:actor},f.dependencies)).rejects.toThrow();expect(f.connect).not.toHaveBeenCalled();const g=fixture();g.job.actorUid='other';await expect(prepareCSVImportPublication({job:g.job,providerFileId:'file',driveToken:'fixture-token'},g.dependencies)).rejects.toThrow();expect(g.connect).not.toHaveBeenCalled();});

it('Drive rejection and project change clear connection without compilation',async()=>{const f=fixture();f.verifyVersion.mockRejectedValueOnce(Error('original changed'));await expect(prepareCSVImportPublication({job:f.job,providerFileId:'file',driveToken:'fixture-token'},f.dependencies)).rejects.toThrow('original changed');expect(f.clear).toHaveBeenCalledOnce();expect(f.dependencies.compile).not.toHaveBeenCalled();const g=fixture();g.dependencies.readProject.mockResolvedValueOnce({id:'p',revision:2}).mockResolvedValueOnce({id:'p',revision:3});await expect(prepareCSVImportPublication({job:g.job,providerFileId:'file',driveToken:'fixture-token'},g.dependencies)).rejects.toThrow('project changed');expect(g.clear).toHaveBeenCalledOnce();expect(g.dependencies.compile).not.toHaveBeenCalled();});
