import {previewVisitImport} from './visit-import.mjs';
import {readMetadataBackup} from './backup.mjs';
import config from './config.mjs';
import {validateVisit,summarizeVisits,timeKeys,costKeys} from './baseline.mjs';
import {createResearchStore,uploadEvidence} from './storage.mjs';
import {hydrateProject} from './archive.mjs';
const $=id=>(window.BringRndHost?.querySelector('#'+id)??document.getElementById(id)),form=$('visitForm');let store=createResearchStore(),token=null,id=crypto.randomUUID(),revision=0,dirty=false;
const bindingNotice=document.createElement('p');bindingNotice.id='baselineProjectBinding';bindingNotice.textContent='신규 기준선은 저장 시 선택된 프로젝트에 연결됩니다.';form.prepend(bindingNotice);const message=text=>$('status').textContent=text;
let evidenceMetadata=null,recordProjectId=undefined;const visitDrafts=new Map();
if(window.bringCRM?.rndList){
 store={getProject:async id=>hydrateProject(await window.bringCRM.rndGet('projects',id)),listVisits:()=>window.bringCRM.rndList('visits'),listProjects:async()=>(await window.bringCRM.rndList('projects')).map(hydrateProject),saveVisit:data=>window.bringCRM.rndSave({collection:'visits',data}),saveProject:async data=>hydrateProject(await window.bringCRM.rndSave({collection:'projects',data}))};
 $('connection').textContent='CRM 로그인 사용 · 공유 저장 확인 필요';$('login').hidden=true;

 const driveButton=document.createElement('button');driveButton.textContent='회사 Drive 연결';driveButton.onclick=async()=>{try{const state=await window.bringCRM.rndConnectDrive();message(`회사 Drive 연결 완료 · ${state.email}`);}catch(error){message(`Drive 연결 실패 · ${error.message}`);}};$('account').after(driveButton);
 $('evidenceFile').parentElement.hidden=true;$('projectFile').parentElement.hidden=true;
}
const publishConnection=()=>window.dispatchEvent(new CustomEvent('rnd-connection',{detail:{store,upload:async(file,onState,context)=>{if(window.bringCRM?.rndUpload){onState('Drive 자료 선택·업로드 중');const result=await window.bringCRM.rndUpload(context);if(result.canceled)throw Error('파일 선택을 취소했습니다');return result;}if(!config.driveOwnershipConfirmed)throw Error('회사 보관권한 확인 필요');return uploadEvidence({file,rootFolderId:config.driveRootFolderId,token,onState});}}}));
window.addEventListener('rnd-request-connection',publishConnection);
setInterval(publishConnection,1500);
form.elements.date.value=new Date().toLocaleDateString('sv-SE');
form.addEventListener('input',()=>dirty=true);window.addEventListener('beforeunload',event=>{if(dirty||visitDrafts.size){event.preventDefault();event.returnValue='';}});
function read(){const f=new FormData(form),v={id,revision};for(const [key,value]of f)v[key]=value;v.revisit=form.elements.revisit.checked;v.minutes=Object.fromEntries(timeKeys.map(k=>[k,f.get(k)]));v.costs=Object.fromEntries(costKeys.map(k=>[k,f.get(k)]));for(const k of [...timeKeys,...costKeys])delete v[k];if(evidenceMetadata)v.evidenceMetadata=evidenceMetadata;v.projectId=recordProjectId===undefined?($("projectPicker")?.value??null):recordProjectId;return v;}
function fill(v){sessionGeneration++;recordProjectId=v.projectId??null;bindingNotice.textContent=`기준선 연결 프로젝트: ${recordProjectId??'미지정'} · 프로젝트 선택을 바꿔도 이 기록의 연결은 유지됩니다.`;evidenceMetadata=v.evidenceMetadata??null;id=v.id||crypto.randomUUID();revision=v.revision??0;for(const el of form.elements){if(!el.name)continue;const value=v.minutes?.[el.name]??v.costs?.[el.name]??v[el.name]??'';if(el.type==='checkbox')el.checked=!!value;else el.value=value;}dirty=true;}
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;const generation=sessionGeneration,inputVersion=window.BringRndInputVersion?.('visitForm');try{const v=validateVisit(read());message('원격 저장 확인 중…');const saved=await store.saveVisit(v);if(generation!==sessionGeneration)return;revision=saved.revision;recordProjectId=saved.projectId??null;bindingNotice.textContent=`기준선 연결 프로젝트: ${recordProjectId??'미지정'} · 이 기록의 연결은 유지됩니다.`;const unchanged=window.BringRndInputVersion?.('visitForm')===inputVersion;dirty=!unchanged;if(unchanged)visitDrafts.delete(saved.id);window.BringRndClearInput?.('visitForm',inputVersion);message(`공유 저장 완료 · ${saved.id} · 버전 ${revision}`);await refresh();}catch(e){if(generation!==sessionGeneration)return;message(`저장되지 않았습니다 · ${e.message} · 입력은 유지됩니다.`);}finally{button.disabled=false;}});
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({kind:'BRING_RND_DRAFT',exportedAt:new Date().toISOString(),visit:read()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rnd-draft-${id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);message('초안 파일 내보내기 완료 · 공유 저장은 아직 아닙니다.');};
$('import').onchange=async event=>{const generation=sessionGeneration;try{const text=await event.target.files[0].text();if(generation!==sessionGeneration)return;const data=JSON.parse(text);if(data.kind==='BRING_RND_METADATA_BACKUP'){const backup=await readMetadataBackup(text);if(generation!==sessionGeneration)return;const shared=await store.listVisits();if(generation!==sessionGeneration)return;const plan=previewVisitImport([...shared,...[...visitDrafts.values()].map(x=>x.data)],backup.visits??[],window.BringRndProject.projectIds());if(!confirm(`기준선 복원 사전 검증 · 신규 ${plan.additions.length}개 · 동일 ID ${plan.conflicts.length}개 유지 · 신규 초안만 불러올까요?`))return;for(const entry of plan.additions)visitDrafts.set(entry.data.id,entry);await refresh();if(generation!==sessionGeneration)return;message(`기준선 초안 ${plan.additions.length}개 복원 · 동일 ID 유지 · 기록별 검토 후 공유 저장하세요.`);return;}if(data.kind!=='BRING_RND_DRAFT'||!data.visit||typeof data.visit!=='object')throw Error('BRING 초안 또는 기준선 포함 백업 형식이 아닙니다');fill(data.visit);message('초안을 불러왔습니다 · 검증 후 공유 저장하세요.');}catch(e){if(generation===sessionGeneration)message(`불러오기 실패 · ${e.message}`);}finally{event.target.value='';}};
async function refresh(){const generation=sessionGeneration;try{const records=await store.listVisits();if(generation!==sessionGeneration)return;const s=summarizeVisits(records);$('summary').textContent=`공유 기록 기준 · 복원 초안 ${visitDrafts.size}개 · ${s.buildings}개 건물 · ${s.visits}회 방문 · ${s.totalMinutes}분 · ${s.totalCost.toLocaleString()}원 (기록 합계)`;$('records').replaceChildren();for(const v of records){const article=document.createElement('article');const label=document.createElement('p');label.textContent=`${v.date} · ${v.buildingId} · ${v.reason} · ${v.totalMinutes}분`;const button=document.createElement('button');button.textContent='기록 열기';button.onclick=()=>{if(dirty&&!confirm('현재 입력을 이 기록으로 바꿀까요?'))return;fill(v);message(`공유 기록 ${v.id} · 버전 ${v.revision}`);};article.append(label,button);$('records').append(article);}for(const entry of visitDrafts.values()){const article=document.createElement('article'),button=document.createElement('button');button.textContent=`복원 초안 ${entry.data.id} · 원본 r${entry.sourceRevision} · 미공유`;button.onclick=()=>{if(dirty&&!confirm('현재 입력을 이 복원 초안으로 바꿀까요?'))return;fill(entry.data);message('복원 기준선 초안 · 검토 후 공유 저장하세요');};article.append(button);$('records').append(article);}}catch(e){if(generation!==sessionGeneration)return;$('summary').textContent=`조회 불가 · ${e.message}`;}}
$('refresh').onclick=refresh;
$('login').onclick=async()=>{if(!config.firebase||!config.workspaceId||!globalThis.firebase){message('승인된 Firebase 시험 환경 설정이 필요합니다.');return;}try{const provider=new firebase.auth.GoogleAuthProvider();if(config.driveRootFolderId&&config.driveOwnershipConfirmed)provider.addScope('https://www.googleapis.com/auth/drive.file');const result=await firebase.auth().signInWithPopup(provider);token=result.credential?.accessToken??null;}catch(e){message(`로그인 실패 · ${e.message}`);}};
$('upload').onclick=async()=>{const button=$('upload');button.disabled=true;try{if(!config.driveOwnershipConfirmed)throw Error('회사 보관권한 확인 필요');const result=await uploadEvidence({file:$('evidenceFile').files[0],rootFolderId:config.driveRootFolderId,token,onState:text=>$('uploadState').textContent=text});form.elements.evidenceUrl.value=result.url;dirty=true;$('uploadState').textContent=`Drive 원본 확인 완료 · ${result.id} · 연구 기록은 별도 저장 필요`;}catch(e){$('uploadState').textContent=`업로드 미완료 · ${e.message}`;}finally{button.disabled=false;}};
if(window.bringCRM?.rndUpload){let pendingVersion=crypto.randomUUID();$('upload').onclick=async()=>{try{const projectId=$('projectPicker').value;const generation=sessionGeneration,artifactId=id;const result=await window.bringCRM.rndUpload({projectId,artifactId,versionId:pendingVersion});if(result.canceled||generation!==sessionGeneration||id!==artifactId)return;evidenceMetadata={driveFileId:result.id,version:result.versionId,hash:result.hash,verifiedAt:result.verifiedAt};form.elements.evidenceUrl.value=result.url;dirty=true;pendingVersion=crypto.randomUUID();$('uploadState').textContent=`Drive 원본 확인 완료 · ${result.id} · 기록 공유 저장 필요`;}catch(error){$('uploadState').textContent=`업로드 실패 · ${error.message}`;}};}
if(config.firebase&&config.workspaceId&&globalThis.firebase){firebase.initializeApp(config.firebase);firebase.auth().onAuthStateChanged(async user=>{store=createResearchStore();$('records').replaceChildren();$('summary').textContent='연구 권한 확인 전';if(!user){token=null;$('connection').textContent='승인 계정 로그인 필요';$('account').textContent='';return;}try{const db=firebase.database();const snap=await db.ref(`rndWorkspaces/${config.workspaceId}/members/${user.uid}`).once('value');const role=snap.val()?.role;store=createResearchStore({db,uid:user.uid,role,workspaceId:config.workspaceId});$('account').textContent=`${user.email} · ${role??'미승인'}`;await store.listVisits();$('connection').textContent='연구 저장소 연결됨';await refresh();}catch(e){$('connection').textContent='연구 권한·연결 확인 필요';message(e.message);}});}

function renderAccessAdmin(state){$('rndAccessAdmin')?.remove();if(!window.bringCRM?.rndAccessAdmin||state.user?.role!=="admin")return;const panel=document.createElement('details');panel.id='rndAccessAdmin';panel.innerHTML='<summary>R&D 접근 승인 관리</summary><form id="rndAccessAdminForm"><label>CRM 사용자 UID<input name="uid" required></label><label>상태<select name="enabled"><option value="true">승인 활성</option><option value="false">승인 취소</option></select></label><label>승인·취소 이유<input name="reason" required></label><button type="button" data-read>현재 승인 조회</button><button>승인 상태 저장</button><label>감사 요청 ID<input name="auditId"></label><button type="button" data-inspect>요청 결과 확인</button></form><p role="status"></p>';const f=panel.querySelector('form'),status=panel.querySelector('p');let approvalVersion=null;f.elements.uid.oninput=()=>{approvalVersion=null;};f.elements.uid.value=state.user.uid;panel.querySelector('[data-read]').onclick=async()=>{try{const value=await window.bringCRM.rndAccessAdmin({action:'get',uid:f.elements.uid.value});approvalVersion={uid:value.uid,etag:value.etag};status.textContent=`CRM ${value.crm?.email??'미승인'} / ${value.crm?.role??'—'} · R&D ${value.rnd?.enabled?'활성':'미승인·취소'} · ${value.rnd?.reason??''} · 감사 ${value.auditLink==='current-approval-linked'?'조회한 승인과 연결 확인':value.auditLink==='audit-mismatch'?'불일치 확인 필요':'과거 기록·감사 연결 없음'}${value.audit?' · '+value.audit.actorUid+' · '+value.audit.at:''}`;}catch(e){status.textContent=e.message;}};panel.querySelector('[data-inspect]').onclick=async()=>{try{const value=await window.bringCRM.rndAccessAdmin({action:'inspect',uid:f.elements.uid.value,auditId:f.elements.auditId.value});status.textContent=`${value.status==='current-approval-linked'?'현재 승인과 연결 확인':'미확정 요청 · 과거 적용 여부는 별도 확인'} · ${value.audit.actorUid} · ${value.audit.at} · ${value.audit.after.reason}`;}catch(error){status.textContent=`요청 조회 실패 · ${error.message}`;}};f.onsubmit=async e=>{e.preventDefault();const inputVersion=window.BringRndInputVersion?.('rndAccessAdminForm');try{if(approvalVersion?.uid!==f.elements.uid.value)throw Error('현재 승인을 먼저 조회하세요');const result=await window.bringCRM.rndAccessAdmin({expectedETag:approvalVersion.etag,action:'save',uid:f.elements.uid.value,enabled:f.elements.enabled.value==='true',reason:f.elements.reason.value});window.BringRndClearInput?.('rndAccessAdminForm',inputVersion);approvalVersion=null;if(result.auditId)f.elements.auditId.value=result.auditId;status.textContent=`승인 상태 저장 완료 · ${result.email} · ${result.role} · ${result.enabled?'활성':'취소'}${result.recoveredByReadback?' · 응답 유실 후 재조회로 확인':''}`;}catch(error){status.textContent=`승인 저장 실패 · ${error.message}`;}};$('connection').closest('section').append(panel);}

let rndSessionIdentity;let sessionGeneration=0;
function observeRndSession(state){const u=state?.user;const identity=JSON.stringify([u?.uid,u?.email,u?.role,!!u?.mustChangePassword]);if(rndSessionIdentity!==undefined&&identity!==rndSessionIdentity){window.dispatchEvent(new CustomEvent('rnd-session-reset',{detail:state}));form.reset();id=crypto.randomUUID();revision=0;dirty=false;evidenceMetadata=null;recordProjectId=undefined;bindingNotice.textContent='신규 기준선은 저장 시 선택된 프로젝트에 연결됩니다.';for(const key of ['records','summary','uploadState'])$(key).replaceChildren();const panel=$('rndAccessAdmin');if(panel){panel.hidden=u?.role!=='admin';panel.querySelector('form').reset();panel.querySelector('[name=uid]').value=u?.uid??'';panel.querySelector('p').textContent='승인 상태 조회 전';}message('로그인 세션 변경 · 이전 초안과 자료 정보 정리 완료');}if(identity!==rndSessionIdentity)renderAccessAdmin(state);rndSessionIdentity=identity;$('account').textContent=`${u?.email??'미로그인'} · ${u?.role??''}`;}
if(window.bringCRM?.onAuthState){let liveStateReceived=false;window.bringCRM.onAuthState(state=>{liveStateReceived=true;observeRndSession(state);});window.bringCRM.authState().then(state=>{if(!liveStateReceived)observeRndSession(state);}).catch(error=>message(`로그인 상태 조회 실패 · ${error.message}`));}

window.BringRndBaselinePending=()=>dirty||visitDrafts.size>0;window.BringRndBaselineDrafts=()=>[...visitDrafts.values()].map(entry=>structuredClone(entry.data));

window.addEventListener('rnd-session-reset',()=>{visitDrafts.clear();sessionGeneration++;$('rndAccessAdmin')?.remove();form.reset();id=crypto.randomUUID();revision=0;dirty=false;evidenceMetadata=null;recordProjectId=undefined;bindingNotice.textContent='신규 기준선은 저장 시 선택된 프로젝트에 연결됩니다.';for(const key of ['records','summary','uploadState'])$(key).replaceChildren();});

const newVisitButton=document.createElement('button');newVisitButton.id='newVisit';newVisitButton.type='button';newVisitButton.textContent='새 기준선 기록';newVisitButton.onclick=()=>{if(dirty&&!confirm('현재 입력을 보관하려면 먼저 초안으로 내보내세요. 새 기준선 기록을 시작할까요?'))return;sessionGeneration++;form.reset();id=crypto.randomUUID();revision=0;dirty=false;evidenceMetadata=null;recordProjectId=undefined;form.elements.date.value=new Date().toLocaleDateString('sv-SE');bindingNotice.textContent='신규 기준선은 저장 시 선택된 프로젝트에 연결됩니다.';window.BringRndClearInput?.('visitForm');$('uploadState').textContent='새 기록 · 자료 선택 전';message('신규 기준선 기록 · 공유 저장 전');};bindingNotice.after(newVisitButton);

if(window.bringCRM?.rndSaveAttempts){const button=document.createElement('button'),output=document.createElement('p');button.id='saveAttemptsRead';output.id='saveAttemptsOutput';output.style.whiteSpace='pre-wrap';button.textContent='이 PC의 저장 작업 기록';button.onclick=async()=>{const generation=sessionGeneration;button.disabled=true;try{const records=await window.bringCRM.rndSaveAttempts();if(generation!==sessionGeneration)return;output.textContent='저장 요청 기록 · 완료 여부는 공유 기록과 별도 확인 · 최근 50개'+String.fromCharCode(10)+'';for(const x of records.slice(-50).reverse()){const row=document.createElement('span'),check=document.createElement('button'),result=document.createElement('span');row.style.display='block';row.textContent=x.at+' · '+x.collection+'/'+x.recordId+' · r'+x.revision+' · '+x.operationId+' ';check.textContent='현재 공유 기록 대조';check.onclick=async()=>{const epoch=sessionGeneration;check.disabled=true;try{const state=await window.bringCRM.rndCheckSaveAttempt({operationId:x.operationId});if(epoch===sessionGeneration)result.textContent=state.message;}catch(error){if(epoch===sessionGeneration)result.textContent='대조 실패 · '+error.message;}finally{check.disabled=false;}};row.append(check,result);output.append(row);}}catch(error){if(generation===sessionGeneration)output.textContent='조회 실패 · '+error.message;}finally{button.disabled=false;}};$('account').after(button,output);window.addEventListener('rnd-session-reset',()=>output.replaceChildren());}
