import {validateVisit,validateVisitLinks} from './baseline.mjs';
import {createArchive,readArchive} from './archive.mjs';
const canonical=value=>JSON.stringify(value,(_key,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.keys(item).sort().map(key=>[key,item[key]])):item);
const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(value))))).map(x=>x.toString(16).padStart(2,'0')).join('');
function inventory(projects){return projects.map(p=>({projectId:p.id,revision:p.revision??0,counts:{items:p.items.length,trl:p.trl.length,history:p.history.length,assessments:p.assessments.length,...Object.fromEntries(Object.entries(p.research??{}).filter(([,v])=>Array.isArray(v)).map(([key,v])=>[key,v.length]))},fileReferences:(p.research?.datasetSnapshots??[]).flatMap(ds=>(ds.versionRefs??[]).map(ref=>({datasetId:ds.id,versionId:ref.versionId,artifactId:ref.artifactId,providerFileId:ref.providerFileId,sha256:ref.sha256,sizeBytes:ref.sizeBytes}))).map(ref=>Object.fromEntries(Object.entries(ref).filter(([,value])=>value!==undefined)))}));}
function checkVisits(visits,projects){if(!Array.isArray(visits))throw Error('기준선 기록 목록 오류');const ids=new Set(visits.map(v=>v?.id)),projectIds=new Set(projects.map(p=>p.id));if(ids.size!==visits.length)throw Error('기준선 중복 ID');for(const v of visits){validateVisit(v);if(!/^[a-zA-Z0-9_-]{1,128}$/.test(v.id)||!Number.isInteger(v.revision??0)||(v.revision??0)<0)throw Error('기준선 ID·revision 오류');if(v.projectId&&!projectIds.has(v.projectId))throw Error('기준선 연결 프로젝트를 먼저 조회하세요');if(v.revisit&&!ids.has(v.originalVisitId))throw Error('재방문 원기록 연결 오류');}return validateVisitLinks(visits);}
export async function createMetadataBackup(projects,selectedId,visits=[]){visits=structuredClone(visits);checkVisits(visits,projects);const archive=createArchive(projects,selectedId);return{kind:'BRING_RND_METADATA_BACKUP',version:2,archive,visits:structuredClone(visits),manifest:{scope:'metadata-only',binaryFilesIncluded:false,generatedAt:archive.exportedAt,visitCount:visits.length,visitsSHA256:await digest(visits),projectCount:projects.length,inventory:inventory(projects),archiveSHA256:await digest(archive)}};}
export async function readMetadataBackup(text){const data=JSON.parse(text);if(data.kind==='BRING_RND_ARCHIVE')return{archive:readArchive(text),verified:false,warning:'과거 메타데이터 보관본 · 해시 manifest 없음'};
 if(data.kind!=='BRING_RND_METADATA_BACKUP'||![1,2].includes(data.version)||data.manifest?.scope!=='metadata-only'||data.manifest.binaryFilesIncluded!==false)throw Error('메타데이터 백업 형식·범위 오류');
 if(await digest(data.archive)!==data.manifest.archiveSHA256)throw Error('백업 메타데이터 해시 불일치 · 복원을 중단했습니다');
 const archive=readArchive(JSON.stringify(data.archive));if(data.manifest.projectCount!==archive.projects.length||canonical(inventory(archive.projects))!==canonical(data.manifest.inventory))throw Error('백업 자료 목록·개수 불일치');
 const visits=data.version===2?checkVisits(data.visits,archive.projects):[];if(data.version===2&&(data.manifest.visitCount!==visits.length||await digest(visits)!==data.manifest.visitsSHA256))throw Error('기준선 기록 해시·개수 불일치');return{archive,visits,verified:true,warning:`메타데이터 해시·목록 확인 · 기준선 ${visits.length}개 · 원본 파일 미포함${data.version===1?' · 과거 파일은 기준선 미포함':''}`};
}
