import {validateVisit,timeKeys,costKeys} from './baseline.mjs';
import {previewVisitImport} from './visit-import.mjs';
export const csvLimits=Object.freeze({bytes:8*1024*1024,records:10000,columns:128,cellCharacters:32768});
const identity=value=>typeof value==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(value);
const required=['buildingId','date','operator','reason','serviceScope','costBasis','evidenceUrl','totalMinutes',...timeKeys,...costKeys];
export const csvVisitFields=Object.freeze(['id',...required,'revision','revisit','originalVisitId','revisitReason','limitations']);
const hex=buffer=>Array.from(new Uint8Array(buffer)).map(byte=>byte.toString(16).padStart(2,'0')).join('');
async function hash(bytes){return hex(await crypto.subtle.digest('SHA-256',bytes));}
function sourceBytes(input){if(!(input instanceof Uint8Array)&&!(input instanceof ArrayBuffer))throw Error('CSV 원본 바이트가 필요합니다');const bytes=input instanceof ArrayBuffer?new Uint8Array(input.slice(0)):new Uint8Array(input);if(!bytes.length||bytes.byteLength>csvLimits.bytes)throw Error('CSV 파일은 8MiB 이하로 선택하세요');return bytes;}
/** Original UTF-8 bytes stay unchanged; BOM and line endings participate in the source hash. */
export async function readCSV(input,{delimiter=','}={}){
 const bytes=sourceBytes(input);if(![',',';','\t'].includes(delimiter))throw Error('CSV 구분자는 쉼표·세미콜론·탭만 가능합니다');let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{throw Error('CSV를 UTF-8로 저장한 뒤 다시 선택하세요');}if(text.includes('\0'))throw Error('CSV에 NUL 문자가 있습니다');
 const records=[];let fields=[],cell='',quoted=false,closed=false,started=false;
 const append=character=>{cell+=character;if(cell.length>csvLimits.cellCharacters)throw Error('CSV 셀 길이 제한 초과');};
 const finishField=()=>{fields.push(cell);if(fields.length>csvLimits.columns)throw Error('CSV 열 수 제한 초과');cell='';closed=false;};
 const finishRecord=()=>{finishField();records.push(fields);if(records.length>csvLimits.records+1)throw Error('CSV 기록 수 제한 초과');fields=[];started=false;};
 for(let index=0;index<text.length;index++){const character=text[index];if(quoted){if(character==='"'){if(text[index+1]==='"'){append('"');index++;}else{quoted=false;closed=true;}}else append(character);continue;}
  if(character===delimiter){finishField();started=true;}else if(character==='\r'||character==='\n'){finishRecord();if(character==='\r'&&text[index+1]==='\n')index++;}else if(closed)throw Error('CSV 닫는 따옴표 뒤에 잘못된 문자가 있습니다');else if(character==='"'){if(cell.length)throw Error('CSV 따옴표는 셀 시작에서 사용하세요');quoted=true;started=true;}else{append(character);started=true;}}
 if(quoted)throw Error('CSV 따옴표가 닫히지 않았습니다');if(started||fields.length||cell.length||closed)finishRecord();if(!records.length)throw Error('CSV 헤더가 없습니다');
 const headers=records.shift().map(value=>value.trim());if(headers.some(value=>!value||/[\u0000-\u001f\u007f]/.test(value))||new Set(headers).size!==headers.length)throw Error('CSV 헤더는 비어 있거나 중복될 수 없습니다');const rows=[];let blankRecords=0;
 records.forEach((fields,index)=>{if(fields.length===1&&!fields[0].trim()){blankRecords++;return;}if(fields.length!==headers.length)throw Error(`CSV 기록 ${index+2}: 헤더와 열 수가 다릅니다`);rows.push({recordNumber:index+2,fields});});
 return{headers,rows,blankRecords,source:{sha256:await hash(bytes),sizeBytes:bytes.byteLength,encoding:'UTF-8',delimiter}};
}
function provenance(source){if(!source||Array.isArray(source)||Object.keys(source).some(key=>!['fileName','ledger','extractedAt'].includes(key))||typeof source.fileName!=='string'||!source.fileName.trim()||source.fileName.length>180||/[\u0000-\u001f\u007f/\\]/.test(source.fileName)||typeof source.ledger!=='string'||!source.ledger.trim()||source.ledger.length>4000||typeof source.extractedAt!=='string'||!Number.isFinite(Date.parse(source.extractedAt))||new Date(source.extractedAt).toISOString()!==source.extractedAt)throw Error('CSV 파일명·출처 원장·ISO 추출 시각이 필요합니다');}
function number(value,field){const text=value.trim();if(!/^(?:\d+(?:\.\d*)?|\.\d+)$/.test(text)||!Number.isFinite(Number(text))||Number(text)>Number.MAX_SAFE_INTEGER)throw Error(`${field}: 빈 값 대신 실제 0 이상의 수치가 필요합니다`);return Number(text);}
/** Preview only: no shared write, approval or source-file mutation. Error rows prevent every application. */
export async function previewBaselineCSV(input){
 const bytes=sourceBytes(input?.bytes),options=structuredClone({...input,bytes:undefined});const {mapping,projectId,projectIds,current,source,units,delimiter=','}=options;provenance(source);if(!units||typeof units!=='object'||Array.isArray(units)||Object.keys(units).length!==2||Object.keys(units).some(key=>!['minutes','costs'].includes(key))||units.minutes!=='min'||units.costs!=='KRW')throw Error('CSV 시간은 분(min), 비용은 원(KRW) 단위임을 명시하세요');if(!identity(projectId)||!Array.isArray(projectIds)||!projectIds.includes(projectId)||!Array.isArray(current))throw Error('CSV 대상 프로젝트를 먼저 조회하거나 선택하세요');
 const parsed=await readCSV(bytes,{delimiter});if(!mapping||typeof mapping!=='object'||Array.isArray(mapping)||Object.keys(mapping).some(key=>!csvVisitFields.includes(key))||Object.values(mapping).some(value=>typeof value!=='string'||!parsed.headers.includes(value))||new Set(Object.values(mapping)).size!==Object.values(mapping).length||required.some(field=>!Object.hasOwn(mapping,field)))throw Error('CSV 필수 열 매핑·중복 열·허용 항목을 확인하세요');
 const columns=new Map(parsed.headers.map((header,index)=>[header,index])),errors=[],incoming=[],seen=new Set(),projectHash=await hash(new TextEncoder().encode(projectId));
 for(const row of parsed.rows){try{const get=key=>Object.hasOwn(mapping,key)?row.fields[columns.get(mapping[key])]:'',id=Object.hasOwn(mapping,'id')?get('id').trim():`csv-${parsed.source.sha256.slice(0,24)}-${projectHash.slice(0,12)}-${row.recordNumber}`;if(!identity(id)||seen.has(id))throw Error('CSV 방문 ID 형식 오류 또는 중복 ID');seen.add(id);
   const visit={id,revision:0,projectId};for(const field of ['buildingId','date','operator','reason','serviceScope','costBasis','evidenceUrl'])visit[field]=get(field).trim();visit.minutes=Object.fromEntries(timeKeys.map(key=>[key,number(get(key),key)]));visit.costs=Object.fromEntries(costKeys.map(key=>[key,number(get(key),key)]));visit.totalMinutes=number(get('totalMinutes'),'totalMinutes');
   if(Object.hasOwn(mapping,'revision')){const raw=get('revision').trim();if(!/^\d+$/.test(raw)||!Number.isSafeInteger(Number(raw)))throw Error('CSV revision 형식 오류');visit.revision=Number(raw);}const revisit=get('revisit').trim().toLowerCase();if(!['','true','false','1','0'].includes(revisit))throw Error('CSV 재방문은 true/false 또는 1/0을 사용하세요');visit.revisit=['true','1'].includes(revisit);for(const field of ['originalVisitId','revisitReason','limitations'])if(Object.hasOwn(mapping,field))visit[field]=get(field).trim();
   const url=new URL(visit.evidenceUrl);if(url.username||url.password)throw Error('CSV 원본 링크에 로그인 정보를 넣을 수 없습니다');incoming.push(validateVisit(visit));
  }catch(error){errors.push({recordNumber:row.recordNumber,message:error.message});}}
 let plan={additions:[],conflicts:[]};if(!errors.length&&incoming.length){try{plan=previewVisitImport(current,incoming,projectIds);}catch(error){errors.push({recordNumber:null,message:error.message});}}
 return{kind:'BRING_RND_CSV_BASELINE_PREVIEW',version:1,scope:'local-visit-drafts',cloudWrites:false,canApply:!errors.length&&incoming.length>0,duplicatePolicy:'KEEP_EXISTING',source:{...parsed.source,...source,mapping,projectId,generatedIdentity:!Object.hasOwn(mapping,'id'),units},totals:{records:parsed.rows.length,blankRecords:parsed.blankRecords,valid:incoming.length,invalid:errors.filter(error=>error.recordNumber!==null).length,new:plan.additions.length,conflicts:plan.conflicts.length},errors,additions:plan.additions,conflicts:plan.conflicts};
}
/** Sanitized export copy only. Never replace original source bytes with this output. */
export function exportSafeCSV(headers,rows){if(!Array.isArray(headers)||!headers.length||!Array.isArray(rows)||rows.some(row=>!Array.isArray(row)||row.length!==headers.length))throw Error('CSV 내보내기 열 수 오류');const cell=value=>{let text=String(value??'');if(/^[\s\u0000-\u0020]*[=+\-@]/.test(text)||/^[\t\r\n]/.test(text))text="'"+text;return'"'+text.replaceAll('"','""')+'"';};return[headers,...rows].map(row=>row.map(cell).join(',')).join('\r\n');}
