const {assertUploadFile}=require('./file-policy');
const crypto=require('node:crypto');
const COMPANY='bringengineering1008@gmail.com';
const ROOT='1A7JZQLNkuSWMrpAbVcse6EoUeUAKoN3S';
function createRndDrive({auth,fetch:request=globalThis.fetch,rootFolderId=ROOT,now=Date.now}){
 let connection=null;let uploadPending=false;
 function actor(){const user=auth()?.user;if(!user?.uid||user.mustChangePassword||!['admin','member'].includes(user.role))throw Error('CRM 로그인·자료 업로드 권한이 필요합니다');return user;}
 async function api(url,options={},token=connection?.token){const response=await request(url,{...options,headers:{Authorization:`Bearer ${token}`,...options.headers},signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error(`Drive 요청 실패 (${response.status})`);return response.json();}
 async function connect(token){const user=actor();if(!token||token.length>12000)throw Error('Drive 인증이 필요합니다');const account=await api('https://www.googleapis.com/oauth2/v3/userinfo',{},token);if(account.email!==COMPANY||account.email_verified!==true)throw Error('지정된 회사 Google 계정으로 연결하세요');const root=await api(`https://www.googleapis.com/drive/v3/files/${rootFolderId}?supportsAllDrives=true&fields=id,mimeType,driveId,owners,capabilities,trashed`,{},token);if(root.trashed||root.mimeType!=='application/vnd.google-apps.folder'||!root.capabilities?.canAddChildren||!root.driveId&&!root.owners?.some(x=>x.emailAddress===COMPANY))throw Error('회사 공용 폴더의 보관권한을 확인할 수 없습니다');if(actor().uid!==user.uid)throw Error('CRM 로그인 세션이 변경되었습니다');connection={token,uid:user.uid,expiresAt:now()+50*60*1000,rootFolderId,driveId:root.driveId??null};return{connected:true,email:COMPANY,rootFolderId,expiresAt:connection.expiresAt};}
 function ready(){const user=actor();if(!connection||connection.uid!==user.uid||connection.expiresAt<=now())throw Error('회사 Drive 재연결이 필요합니다');return user;}
 async function folder(parent,name,guard,token){guard();const escaped=name.replace(/'/g,"\\'");const q=`'${parent}' in parents and name = '${escaped}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false`;const result=await api(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&supportsAllDrives=true&includeItemsFromAllDrives=true&fields=files(id)`,{},token);guard();if(result.files?.length>1)throw Error('중복 R&D 폴더 확인이 필요합니다');if(result.files?.[0])return result.files[0].id;const created=await api('https://www.googleapis.com/drive/v3/files?supportsAllDrives=true&fields=id',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',parents:[parent]})},token);guard();return created.id;}
 async function performUpload({fileName,mimeType,bytes,projectId,artifactId,versionId}){const user=ready(),session=connection,token=session.token;const guard=()=>{if(connection!==session||ready().uid!==user.uid)throw Error('CRM/Drive 세션이 변경되었습니다');};guard();for(const id of [projectId,artifactId,versionId])if(!/^[a-zA-Z0-9_-]{1,128}$/.test(id??''))throw Error('자료 연결 ID가 필요합니다');const buffer=Buffer.isBuffer(bytes)?bytes:Buffer.from(bytes??[]);if(!buffer.length||buffer.length>100*1024*1024)throw Error('파일은 100MiB 이하로 선택하세요');assertUploadFile({fileName,sizeBytes:buffer.length,bytes:buffer});const hash=crypto.createHash('sha256').update(buffer).digest('hex');let parent=connection.rootFolderId;for(const part of ['BRING_RND','objects',projectId,String(new Date(now()).getFullYear()),artifactId])parent=await folder(parent,part,guard,token);
 const q=`'${parent}' in parents and appProperties has { key='rndVersion' and value='${versionId}' } and trashed = false`;const duplicate=await api(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&supportsAllDrives=true&includeItemsFromAllDrives=true&fields=files(id,name,size,webViewLink,appProperties,parents)`,{},token);guard();if(duplicate.files?.length>1)throw Error('중복 자료 버전 확인 필요');if(duplicate.files?.[0]){const file=duplicate.files[0];if(file.appProperties?.sha256!==hash||file.appProperties?.projectId!==projectId||file.appProperties?.artifactId!==artifactId||Number(file.size)!==buffer.length||!file.parents?.includes(parent))throw Error('같은 버전 ID의 자료 연결·크기를 확인할 수 없습니다');let verified;try{verified=await verifyVersion({providerFileId:file.id,versionId,artifactId,sha256:hash,projectId});}catch(error){const failure=Error(`Drive 자료 검증 미완료 · 파일 ID ${file.id} · ${error.message}`);failure.recoveryRecord={projectId,artifactId,versionId,id:file.id,hash,size:buffer.length,status:'UPLOADED_UNVERIFIED',observedAt:new Date(now()).toISOString()};throw failure;}guard();return{...file,...verified,hash,versionId,size:verified.sizeBytes,reused:true};}
 const form=new FormData();form.append('metadata',new Blob([JSON.stringify({name:`${versionId}__${String(fileName).replace(/[\\/]/g,'-')}`,parents:[parent],appProperties:{rndVersion:versionId,sha256:hash,projectId,artifactId}})],{type:'application/json'}));form.append('file',new Blob([buffer],{type:mimeType||'application/octet-stream'}),fileName);const created=await api('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&fields=id',{method:'POST',body:form},token);guard();const file=await api(`https://www.googleapis.com/drive/v3/files/${created.id}?supportsAllDrives=true&fields=id,name,size,parents,appProperties,webViewLink,trashed`,{},token);guard();if(file.trashed||Number(file.size)!==buffer.length||!file.parents?.includes(parent)||file.appProperties?.sha256!==hash)throw Error(`Drive 원본 검증 실패 · 파일 ID ${created.id}`);guard();let verified;try{verified=await verifyVersion({providerFileId:file.id,versionId,artifactId,sha256:hash,projectId});}catch(error){const failure=Error(`Drive 자료 검증 미완료 · 파일 ID ${file.id} · ${error.message}`);failure.recoveryRecord={projectId,artifactId,versionId,id:file.id,hash,size:buffer.length,status:'UPLOADED_UNVERIFIED',observedAt:new Date(now()).toISOString()};throw failure;}guard();return{...file,...verified,hash,versionId,size:verified.sizeBytes,reused:false};}
 async function upload(input){ready();if(uploadPending)throw Error('자료 업로드가 진행 중입니다 · 완료 후 다시 시도하세요');uploadPending=true;try{return await performUpload(input);}finally{uploadPending=false;}}
 async function verifyVersion({providerFileId,versionId,artifactId,sha256,projectId}){const user=ready();for(const id of [providerFileId,versionId,artifactId,projectId])if(!/^[a-zA-Z0-9_-]{1,128}$/.test(id??''))throw Error('자료 버전 ID 오류');const session=connection,token=session.token;const guard=()=>{if(connection!==session||ready().uid!==user.uid||connection.token!==token)throw Error('CRM/Drive 세션이 변경되었습니다');};const meta=await api(`https://www.googleapis.com/drive/v3/files/${providerFileId}?supportsAllDrives=true&fields=id,name,mimeType,size,parents,owners,driveId,appProperties,webViewLink,trashed`,{},token);guard();if(meta.trashed||!Number.isInteger(Number(meta.size))||Number(meta.size)<=0||Number(meta.size)>100*1024*1024||meta.appProperties?.rndVersion!==versionId||meta.appProperties?.artifactId!==artifactId||meta.appProperties?.projectId!==projectId||meta.appProperties?.sha256!==sha256||(!connection.driveId&&!meta.owners?.some(o=>o.emailAddress===COMPANY))||(connection.driveId&&meta.driveId!==connection.driveId))throw Error('회사 보관본의 소유권·크기·고정 버전 확인 실패');let parents=meta.parents??[];let inRoot=parents.includes(rootFolderId);const seen=new Set();for(let depth=0;!inRoot&&parents.length&&depth<20;depth++){const next=[];for(const parent of parents){if(seen.has(parent))continue;seen.add(parent);guard();const ancestor=await api(`https://www.googleapis.com/drive/v3/files/${parent}?supportsAllDrives=true&fields=parents,trashed`,{},token);if(ancestor.trashed)throw Error('보관 경로가 휴지통에 있습니다');next.push(...ancestor.parents??[]);}parents=next;inRoot=parents.includes(rootFolderId);}if(!inRoot)throw Error('회사 공용 보관 경로를 확인할 수 없습니다');guard();const response=await request(`https://www.googleapis.com/drive/v3/files/${providerFileId}?alt=media&supportsAllDrives=true`,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error(`Drive 내용 확인 실패 (${response.status})`);const digest=crypto.createHash('sha256');let size=0;if(response.body?.getReader){const reader=response.body.getReader();try{for(;;){const chunk=await reader.read();if(chunk.done)break;guard();size+=chunk.value.length;if(size>100*1024*1024)throw Error('자료 확인 용량 제한 초과');digest.update(chunk.value);}}finally{await reader.cancel();}}else{const bytes=Buffer.from(await response.arrayBuffer());size=bytes.length;if(size>100*1024*1024)throw Error('자료 확인 용량 제한 초과');digest.update(bytes);}guard();if(size!==Number(meta.size)||digest.digest('hex')!==sha256)throw Error('원본 내용 해시·크기 불일치: 데이터셋을 동결하지 않았습니다');return{versionId,artifactId,providerFileId,sha256,sizeBytes:size,mimeType:meta.mimeType,url:meta.webViewLink??`https://drive.google.com/file/d/${meta.id}/view`,verifiedAt:new Date(now()).toISOString()};}
 return{connect,upload,verifyVersion,clear:()=>{connection=null;},state:()=>({connected:!!connection&&connection.expiresAt>now()&&connection.uid===auth()?.user?.uid,rootFolderId})};
}
module.exports={createRndDrive,COMPANY,ROOT};
