import {followUpTasks} from './follow-up.mjs';
import {validateFrozenCrmContext} from './crm-context-service.js';
import {sourceKind} from './source-kind.mjs';
import {codeSource,codeSourceLabel} from './code-source.mjs';
import {evidenceLabels} from './evidence-quality.mjs';
import {disclosureAllowed,latestDisclosure} from './disclosure.mjs';
import {createHash} from 'node:crypto';import {validateProject} from './archive.mjs';import {verifyDatasetManifest} from './dataset.mjs';
const id=x=>{if(typeof x!=='string'||!/^[a-zA-Z0-9_-]{1,128}$/.test(x))throw Error('내보내기 엔터티 ID 오류');return x;};
const block=x=>String(x??'미기록').replace(/\r/g,'').split('\n').map(line=>'    '+line).join('\n')+'\n\n';
const field=(label,value)=>label+'\n\n'+block(value);
const link=(folder,value)=>`[${id(value)}](../${folder}/${id(value)}.md)`;
function sourceURL(value){try{const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||[...u.searchParams.keys()].some(k=>/token|secret|password|authorization|credential|signature|^auth$|^key$|^api[_-]?key$/i.test(k)))return null;return u.href;}catch{return null;}}
const json=x=>JSON.stringify(x,null,2);
const planFields=x=>Object.fromEntries(['id','hypothesis','frameworkVersion','question','comparison','population','period','metrics','analysis','success','stop','reviewerUid'].filter(k=>x?.[k]!==undefined).map(k=>[k,x[k]]));
export function buildRndExport(project,{mode='internal'}={}){validateProject(project);id(project.id);if(!['internal','review'].includes(mode))throw Error('내보내기 범위 오류');const r=project.research??{},files={},excluded=[];const allEvidence=r.evidence??[];const evidence=allEvidence.filter(e=>{id(e.id);if(mode==='internal')return true;const ds=(r.datasetSnapshots??[]).find(d=>d.id===e.source?.datasetSnapshotId);const reason=e.status!=='approved'?'NOT_APPROVED':!disclosureAllowed(project,e.id)?'DISCLOSURE_UNCONFIRMED':!ds||!verifyDatasetManifest(ds)||e.source.manifestHash!==ds.manifestHash||e.source.version!==ds.version?'DATASET_UNFROZEN_OR_INVALID':null;if(reason){excluded.push({id:e.id,type:'evidence',reason});return false;}return true;});const evIds=new Set(evidence.map(e=>e.id));const experiments=(r.experiments??[]).filter(e=>mode==='internal'||evidence.some(v=>v.experimentId===e.id));const expIds=new Set(experiments.map(e=>e.id));const metrics=(r.metricResults??[]).filter(m=>mode==='internal'||evidence.some(e=>e.metricResultIds?.includes(m.id)));const metricIds=new Set(metrics.map(m=>m.id));const datasets=(r.datasetSnapshots??[]).filter(ds=>mode==='internal'||evidence.some(e=>e.source?.datasetSnapshotId===ds.id)||metrics.some(m=>m.baselineSnapshotId===ds.id||m.resultSnapshotId===ds.id));const dsIds=new Set(datasets.map(d=>d.id));const decisions=mode==='internal'?r.decisions??[]:[];const hypotheses=mode==='internal'?r.hypotheses??[]:[];
const crmContexts=Object.values(project.crmContexts??{});for(const record of crmContexts){id(record.id);if(mode==='review'){excluded.push({id:record.id,type:'crm-context',reason:'CRM_DISCLOSURE_UNCONFIRMED'});continue;}validateFrozenCrmContext(record,project.id);files[`crm-contexts/${record.id}.md`]='# 고정 CRM 자료\n\n'+field('ID / 프로젝트',`${record.id} / ${record.projectId}`)+field('보관 이유',record.reason)+field('보관 당시 프로젝트 revision',record.sourceRevision)+field('보관자 / 시각',`${record.frozenBy} / ${record.frozenAt}`)+field('고객 선택 ID',record.customerIdsJSON)+field('건물 선택 ID',record.buildingIdsJSON)+field('CRM manifest SHA256',record.manifestHash)+field('고정 수집자료',json(JSON.parse(record.snapshotJSON)))+'내용 검증값은 작성자·출처·승인 여부에 대한 인증 서명이 아닙니다.\n';}
const projectPath=`projects/${project.id}.md`;let page='# BRING R&D 프로젝트\n\n'+field('제목',mode==='internal'?project.title:'BRING R&D 검토 허용 기록')+field('고유 ID',project.id)+field('공유 revision',project.revision)+field('내보내기 범위',mode)+(mode==='internal'?field('현재 TRL / 목표 TRL',`${project.currentTRL??'미평가'} / ${project.targetTRL??'미지정'}`):'');if(mode==='internal'){page+='## 산출물\n\n';for(const item of project.items){id(item.id);page+='### 산출물\n\n'+field('ID / 영역 / 이름',`${item.id} / ${item.group} / ${item.title}`);for(const k of ['status','owner','due','goal','criteria','result','reviewer'])page+=field(k,item[k]);for(const e of item.evidence){const url=sourceURL(e.url);page+=field('근거 버전',e.version)+(url?'원본: <'+url+'>\n\n':'원본 링크: 미기록 또는 안전한 내보내기 불가\n\n');}}page+='## TRL 단계별 계획\n\n';for(const stage of project.trl)page+=field('단계 '+stage.level,json(Object.fromEntries(['goal','criteria','owner','due','result'].map(k=>[k,stage[k]??'']))));page+='## 수정·판정 이력\n\n';for(const h of [...project.history,...project.assessments])page+=block(json(Object.fromEntries(['kind','id','actor','reviewer','reason','at','level','selfReview'].filter(k=>h[k]!==undefined).map(k=>[k,h[k]]))));}
if(mode==='internal'){page+='## 공개 범위 감사 기록\n\n';for(const a of r.disclosureApprovals??[])page+=field('승인·취소 기록',json(Object.fromEntries(['id','targetEvidenceId','priorApprovalId','experimentId','datasetSnapshotId','manifestHash','bundleHash','action','audience','reason','permissionConfirmed','sensitivity','sourceRevision','sequence','approvedBy','at'].filter(k=>a[k]!==undefined).map(k=>[k,a[k]]))));}
page+='## 연결 기록\n\n'+experiments.map(e=>'- '+link('experiments',e.id)).join('\n')+'\n\n'+evidence.map(e=>'- '+link('evidence',e.id)).join('\n')+'\n\n'+decisions.map(e=>'- '+link('decisions',e.id)).join('\n')+'\n\n'+hypotheses.map(e=>'- '+link('hypotheses',e.id)).join('\n')+'\n';page+='\n\n'+metrics.map(m=>'- '+link('metrics',m.id)).join('\n')+'\n\n'+datasets.map(d=>'- '+link('datasets',d.id)).join('\n')+'\n';if(mode==='internal'&&crmContexts.length)page+='\n## 고정 CRM 자료\n\n'+crmContexts.map(record=>'- '+link('crm-contexts',record.id)).join('\n')+'\n';files[projectPath]=page;
for(const e of experiments){let note='# 실험 기록\n\n'+field('ID',e.id)+field('상태 / 계획 revision',`${e.status} / ${e.planVersion}`)+field('계획',json(planFields(e.frozenPlan??e.plan)))+field('결과 / 방향',`${e.result??'미기록'} / ${e.outcome??'미판정'}`);if(e.parentExperimentId)note+=field('이전 계획 ID',e.parentExperimentId)+field('변경 이유',e.changeReason)+field('적용 대상',e.appliesTo);if(e.dataset?.datasetSnapshotId&&dsIds.has(e.dataset.datasetSnapshotId))note+='동결 데이터셋: '+link('datasets',e.dataset.datasetSnapshotId)+'\n\n';else note+='자료 상태: 동결 데이터셋 미연결\n\n';const url=sourceURL(e.dataset?.url);if(url)note+='원본: <'+url+'>\n\n';note+='프로젝트: '+link('projects',project.id)+'\n';files[`experiments/${id(e.id)}.md`]=note;}
for(const e of evidence){let note='# 근거 검토\n\n'+field('ID / 상태',`${e.id} / ${e.status}`)+field('근거 유형',evidenceLabels[e.evidenceType]??'미분류')+field('원출처·측정 범위',e.sourceDescription||'미기록')+field('주장',e.claim)+field('한계·반대 관측',e.limitations)+field('검토자',e.approvedBy??e.reviewerUid)+field('출처 링크 성격',sourceKind(e.source?.url))+field('출처 버전',e.source?.version)+field('동결 manifestHash',e.source?.manifestHash??'미동결');try{const code=codeSource(e.source?.url,e.source?.version);if(code)note+=field('GitHub 코드 근거',codeSourceLabel(code));}catch(error){note+=field('코드 근거 검토 필요',error.message);}if(expIds.has(e.experimentId))note+='실험: '+link('experiments',e.experimentId)+'\n\n';if(dsIds.has(e.source?.datasetSnapshotId))note+='데이터셋: '+link('datasets',e.source.datasetSnapshotId)+'\n\n';const url=sourceURL(e.source?.url);if(url)note+='원본: <'+url+'>\n';for(const mid of e.metricResultIds??[])if(metricIds.has(mid))note+='수치 결과: '+link('metrics',mid)+'\n\n';files[`evidence/${id(e.id)}.md`]=note;}
for(const ds of datasets){id(ds.id);if(!verifyDatasetManifest(ds)){excluded.push({id:ds.id,type:'dataset',reason:'MANIFEST_INVALID'});files[`datasets/${ds.id}.md`]='# 데이터셋 확인 필요\n\n'+field('ID',ds.id)+'동결 manifest 무결성 확인 실패. 원본 보관이 완료되었다고 판단하지 마세요.\n';continue;}let note='# 동결 데이터셋\n\n'+field('ID / 버전',`${ds.id} / ${ds.version}`)+field('manifestHash',ds.manifestHash)+field('계획 revision / 해시',`${ds.planRevision} / ${ds.planHash}`)+field('선정 / 제외 기준',`${ds.selectionRule} / ${ds.exclusions}`)+field('대상 집단',ds.population)+field('독립 단위',ds.unitType)+field('동결자 / 시각',`${ds.frozenBy} / ${ds.frozenAt}`)+field('수집 기간',`${ds.periodStart} ~ ${ds.periodEnd}`)+field('파일 / 행 / 독립 대상 수',`${ds.fileCount} / ${ds.rowCount} / ${ds.sampleUnits}`);if(mode==='internal')note+=field('독립 대상 ID',ds.unitIds.join(', '));for(const ref of ds.versionRefs){note+=field('원본 ID / 고정 버전 / SHA256',`${ref.providerFileId} / ${ref.versionId} / ${ref.sha256}`);const url=sourceURL(ref.url);if(url)note+='원본: <'+url+'>\n\n';}files[`datasets/${ds.id}.md`]=note;}
for(const m of metrics){let note='# 수치 결과 원장\n\n'+field('ID / 지표 / 단위',`${m.id} / ${m.name} / ${m.unit}`)+field('기준값 / 결과값 / 개선율',`${m.baseline} / ${m.result} / ${m.percent??'계산 불가'}`)+field('계산 버전 / 입력 방식',`${m.calculatorVersion} / ${m.inputMethod}`)+field('기준 원본 위치',m.baselineLocator)+field('결과 원본 위치',m.resultLocator)+field('집계 방법 / 한계',`${m.method} / ${m.limitations}`);for(const sid of [m.baselineSnapshotId,m.resultSnapshotId])if(dsIds.has(sid))note+='동결 원본: '+link('datasets',sid)+'\n\n';files[`metrics/${id(m.id)}.md`]=note;}
const followUps=followUpTasks(r.followUpEvents??[]);for(const task of followUps){if(mode==='review'){excluded.push({id:task.taskId,reason:'FOLLOW_UP_DISCLOSURE_UNCONFIRMED'});continue;}let note='# 결정 후속 업무\n\n'+field('ID / 업무 / 상태',`${task.taskId} / ${task.title} / ${task.status}`)+field('담당자 / 검토자 / 기한',`${task.ownerUid} / ${task.reviewerUid} / ${task.due}`)+field('완료 기준',task.criteria)+field('결과',task.result);if(decisions.some(d=>d.id===task.decisionId))note+='사업 결정: '+link('decisions',task.decisionId)+'\n\n';const url=sourceURL(task.resultUrl);if(url)note+='결과 자료: <'+url+'>\n\n';for(const event of (r.followUpEvents??[]).filter(e=>e.taskId===task.taskId).sort((a,b)=>a.sequence-b.sequence))note+=field('이력 / 상태 / 작성자 / 시각',`${event.sequence} / ${event.status} / ${event.actorUid} / ${event.at}`)+field('이유',event.reason)+field('당시 결과',event.result)+field('자기검토 사유',event.selfReviewReason);files[`follow-ups/${id(task.taskId)}.md`]=note;files[projectPath]+='후속 업무: '+link('follow-ups',task.taskId)+'\n\n';}
for(const d of decisions){let note='# 사업 결정\n\n'+field('ID / 결정',`${d.id} / ${d.action}`)+field('이유·후속 행동',d.reason)+field('결정자 / 시각',`${d.decidedBy} / ${d.at}`);for(const eid of d.evidenceIds)if(evIds.has(eid))note+='근거: '+link('evidence',eid)+'\n\n';files[`decisions/${id(d.id)}.md`]=note;}
for(const h of hypotheses){const assessments=(r.hypothesisAssessments??[]).filter(a=>a.hypothesisId===h.id);let note='# 가설\n\n'+field('ID / 코드 / 체계',`${h.id} / ${h.code} / ${h.frameworkVersion}`)+field('명세',h.statement)+field('범위 / 초기 상태',`${h.scope} / ${h.status}`);for(const a of assessments){note+=field('판정 / 검토자 / 시각',`${a.status} / ${a.assessedBy} / ${a.at}`)+field('이유·한계',a.reason);for(const eid of a.evidenceIds)if(evIds.has(eid))note+='검토 근거: '+link('evidence',eid)+'\n\n';}files[`hypotheses/${id(h.id)}.md`]=note;}
files['README.md']='# BRING R&D 기록 묶음\n\n'+`[프로젝트 기록](${projectPath})\n\n`+(mode==='internal'?'회사 내부 기록입니다. 미승인·미동결·민감 여부 미확정 자료가 포함될 수 있습니다.':'검토용 선별 기록입니다. 공개 범위가 확인되지 않은 자료와 미승인·미동결 근거는 제외합니다.')+'\n\n원본 바이너리는 포함하지 않습니다. 전체 파일 백업이나 공식 외부 평가 인증 기록이 아닙니다. 기존 Obsidian Vault를 수정하지 않으며 ZIP을 별도 폴더에 풀어 열 수 있습니다.\n\n자세한 원본 revision·파일 해시·제외 사유는 manifest.json을 확인하세요.\n';
for(const path of Object.keys(files)){if(!path.endsWith('.md')||path==='README.md')continue;files[path]+='\n## 원장 출처\n\n'+field('프로젝트 / 공유 revision',`${project.id} / ${project.revision}`);if(path!==projectPath)files[path]+='프로젝트: '+link('projects',project.id)+'\n';}
const manifest={kind:'BRING_RND_MARKDOWN_EXPORT',version:1,mode,projectId:project.id,projectRevision:project.revision,generatedAt:new Date().toISOString(),metadataOnly:true,originalFilesIncluded:false,includedFollowUps:mode==='internal'?followUps.map(t=>t.taskId):[],includedCrmContexts:mode==='internal'?crmContexts.map(record=>record.id):[],includedEvidence:evidence.map(e=>e.id),includedDatasets:datasets.filter(verifyDatasetManifest).map(d=>d.id),includedMetrics:metrics.map(m=>m.id),disclosureApprovals:mode==='review'?evidence.map(e=>{const a=latestDisclosure(r,e.id);return {id:a.id,targetEvidenceId:e.id,bundleHash:a.bundleHash,approvedBy:a.approvedBy,at:a.at};}):[],excluded,files:Object.entries(files).map(([path,content])=>({path,sizeBytes:Buffer.byteLength(content),sha256:createHash('sha256').update(content).digest('hex')}))};files['manifest.json']=json(manifest)+'\n';return{files,manifest};}
