import {followUpTasks} from './follow-up.mjs';
import {hydrateProject} from './archive.mjs';
export function mountFollowUp(area){
 const panel=document.createElement('section');panel.id='rndFollowUp';panel.innerHTML='<h3>결정 후속 업무</h3><p>사업 결정에 담당자·기한·완료 기준을 연결합니다. 결과 자료를 제출한 뒤 검토자가 완료를 확정합니다.</p><details><summary>후속 업무 만들기</summary><form id="followUpCreateForm"></form></details><details><summary>업무 진행·검토</summary><form id="followUpTransitionForm"></form></details><p id="followUpStatus" role="status"></p><div id="followUpRecords"></div>';area.append(panel);
 const find=id=>panel.querySelector('#'+id),status=find('followUpStatus'),records=find('followUpRecords');let epoch=0;const pending=new Set();window.BringRndFollowUpPending=()=>pending.size>0;
 const labels={todo:'할 일',active:'진행 중',review:'검토 대기',done:'완료',blocked:'막힘',cancelled:'취소'};
 function fields(id,spec){const form=find(id);for(const [name,label,type='text',required=true] of spec){const row=document.createElement('label'),input=document.createElement('input');row.textContent=label;input.name=name;input.type=type;input.required=required;input.maxLength=4000;row.append(input);form.append(row);}const button=document.createElement('button');button.textContent=id==='followUpCreateForm'?'후속 업무 공유 기록':'상태 변경 공유 기록';form.append(button);return form;}
 const create=fields('followUpCreateForm',[['decisionId','사업 결정 ID'],['title','업무 제목'],['ownerUid','담당자 CRM UID'],['reviewerUid','검토자 CRM UID'],['due','기한','date'],['criteria','완료 기준'],['reason','생성 이유']]);
 const change=fields('followUpTransitionForm',[['taskId','후속 업무 ID'],['reason','변경 이유'],['result','결과 요약','text',false],['resultUrl','결과 자료 링크','url',false],['selfReviewReason','본인 업무를 완료 검토하는 이유','text',false]]);
 const select=document.createElement('select');select.name='status';select.setAttribute('aria-label','업무 상태');for(const value of ['active','review','done','blocked','cancelled']){const option=document.createElement('option');option.value=value;option.textContent=labels[value];select.append(option);}change.prepend(select);select.onchange=()=>{change.elements.result.required=change.elements.resultUrl.required=select.value==='review';};
 function render(project){records.replaceChildren();panel.hidden=!project;if(!project)return;for(const task of followUpTasks(project.research?.followUpEvents??[])){const card=document.createElement('article'),heading=document.createElement('strong'),text=document.createElement('p'),button=document.createElement('button');heading.textContent=task.title+' · '+labels[task.status];text.textContent=`${task.taskId} · 결정 ${task.decisionId} · 담당 ${task.ownerUid} · 검토 ${task.reviewerUid} · 기한 ${task.due} · 완료 기준 ${task.criteria} · ${task.result??'결과 제출 전'}`;button.type='button';button.textContent='이 업무 진행';button.disabled=['done','cancelled'].includes(task.status);button.onclick=()=>{change.elements.taskId.value=task.taskId;change.closest('details').open=true;change.elements.taskId.dispatchEvent(new Event('input',{bubbles:true}));};card.append(heading,text,button);const history=document.createElement('details'),summary=document.createElement('summary');summary.textContent='진행 이력';history.append(summary);for(const event of (project.research?.followUpEvents??[]).filter(e=>e.taskId===task.taskId).sort((a,b)=>a.sequence-b.sequence)){const row=document.createElement('p');row.textContent=`${event.sequence} · ${labels[event.status]} · ${event.actorUid} · ${event.at} · ${event.reason}`;history.append(row);}card.append(history);records.append(card);}}
 async function submit(form,type){const started=epoch,source=window.BringRndProject.current(),version=window.BringRndInputVersion(form.id),job=Symbol();try{if(!source?.revision||window.BringRndProject.hasUnsavedChanges())throw Error('프로젝트를 먼저 공유 저장하세요');if(pending.size)throw Error('저장 중입니다');const task={...Object.fromEntries(new FormData(form)),type,eventId:crypto.randomUUID()};if(type==='create')task.taskId=crypto.randomUUID();else{const latest=followUpTasks(source.research?.followUpEvents??[]).find(t=>t.taskId===task.taskId);if(!latest)throw Error('현재 프로젝트의 업무를 선택하세요');task.previousEventId=latest.id;}pending.add(job);status.textContent='후속 업무 공유 저장 중';const saved=hydrateProject(await window.bringCRM.rndWorkflow({projectId:source.id,expectedRevision:source.revision,command:{type:'followUp',task}}));if(started!==epoch)return;const unchanged=window.BringRndInputVersion(form.id)===version;if(unchanged){window.BringRndClearInput(form.id,version);form.reset();if(form===change)select.onchange();}const accepted=window.BringRndProject.acceptSharedResult(source,saved);status.textContent=accepted?'후속 업무 공유 저장 완료':'공유 기록 저장 완료 · 대기 중 입력을 유지했습니다. 최신 공유본과 비교하세요.';}catch(error){if(started===epoch)status.textContent='후속 업무 저장 실패 · '+error.message;}finally{pending.delete(job);}}
 create.onsubmit=e=>{e.preventDefault();submit(create,'create');};change.onsubmit=e=>{e.preventDefault();submit(change,'transition');};
 window.addEventListener('rnd-project-selected',e=>render(e.detail));window.addEventListener('rnd-session-reset',()=>{epoch++;pending.clear();create.reset();change.reset();select.onchange();records.replaceChildren();status.textContent='';panel.hidden=true;});render(window.BringRndProject.current());
}
