import {validateProject} from './archive.mjs';
export function previewImport(current,incoming){
 if(!Array.isArray(current)||!Array.isArray(incoming)||!incoming.length)throw Error('복원할 프로젝트가 없습니다');
 for(const list of [current,incoming]){if(list.some(p=>!p||typeof p.id!=='string'||!p.id)||new Set(list.map(p=>p.id)).size!==list.length)throw Error('중복 또는 누락 프로젝트 ID');for(const p of list)if(!Number.isSafeInteger(p.revision??0)||(p.revision??0)<0)throw Error('프로젝트 revision 오류');}
 incoming.forEach(p=>{validateProject(p);validateResearchLinks(p);});const existing=new Map(current.map(p=>[p.id,p]));const entries=incoming.map(p=>{const old=existing.get(p.id);return{id:p.id,action:old?'KEEP_EXISTING':'ADD_DRAFT',incomingTitle:p.title,incomingRevision:p.revision??0,currentTitle:old?.title??null,currentRevision:old?old.revision??0:null};});
 return{additions:entries.filter(e=>e.action==='ADD_DRAFT').map(e=>e.id),conflicts:entries.filter(e=>e.action==='KEEP_EXISTING').map(e=>e.id),total:incoming.length,entries};
}
export function applyImport(current,incoming){const plan=previewImport(current,incoming);return structuredClone([...current,...incoming.filter(p=>plan.additions.includes(p.id))]);}

export function validateResearchLinks(project){const r=project.research;if(!r)return;const kinds=['experiments','evidence','decisions','hypotheses','hypothesisAssessments','datasetSnapshots','disclosureApprovals','metricResults','followUpEvents','observations'];const maps={};for(const kind of kinds){const list=r[kind]??[];if(!Array.isArray(list))throw Error('연구 기록 목록 형식 오류');maps[kind]=new Map();for(const record of list){if(!record||typeof record.id!=='string'||!record.id||maps[kind].has(record.id))throw Error('연구 기록 ID 누락 또는 중복');if(record.projectId!==undefined&&record.projectId!==project.id)throw Error('다른 프로젝트 연구 기록');maps[kind].set(record.id,record);}}
const link=(kind,id,required=false)=>{if(!id&&!required)return null;const record=maps[kind].get(id);if(!record)throw Error(`연구 참조 오류: ${kind} / ${id??'누락'}`);return record;};
const uniqueRefs=(value,label)=>{if(value===undefined)return [];if(!Array.isArray(value)||value.some(x=>typeof x!=='string'||!x)||new Set(value).size!==value.length)throw Error(label+' 참조 목록 중복·형식 오류');return value;};
for(const exp of maps.experiments.values()){if(exp.parentExperimentId){const parent=link('experiments',exp.parentExperimentId,true);if(parent.id===exp.id||exp.planVersion!==parent.planVersion+1)throw Error('실험 버전 참조 오류');}if(exp.parentExperimentId){const seen=new Set([exp.id]);let ancestor=exp;while(ancestor.parentExperimentId){ancestor=link('experiments',ancestor.parentExperimentId,true);if(seen.has(ancestor.id))throw Error('실험 계보 순환 오류');seen.add(ancestor.id);}if(exp.rootExperimentId!==undefined&&exp.rootExperimentId!==ancestor.id)throw Error('실험 원본 계보 오류');}if(exp.dataset?.datasetSnapshotId){const ds=link('datasetSnapshots',exp.dataset.datasetSnapshotId,true);if(ds.experimentId!==exp.id||ds.manifestHash!==exp.dataset.manifestHash)throw Error('실험 자료 참조 오류');}}
for(const ds of maps.datasetSnapshots.values()){const exp=link('experiments',ds.experimentId,true);if(ds.planRevision!==exp.planVersion)throw Error('데이터셋 계획 참조 오류');}
for(const metric of maps.metricResults.values()){const exp=link('experiments',metric.experimentId,true);for(const prefix of ['baseline','result']){const ds=link('datasetSnapshots',metric[prefix+'SnapshotId'],true);if(ds.experimentId!==exp.id||ds.manifestHash!==metric[prefix+'ManifestHash'])throw Error('수치 자료 참조 오류');}}
for(const e of maps.evidence.values()){link('experiments',e.experimentId);if(e.source?.datasetSnapshotId){const ds=link('datasetSnapshots',e.source.datasetSnapshotId,true);if(ds.experimentId!==e.experimentId||ds.manifestHash!==e.source.manifestHash)throw Error('근거 자료 참조 오류');}const metricIds=uniqueRefs(e.metricResultIds,'근거 수치');if(e.metricResultRefs!==undefined){let refs;try{refs=JSON.parse(e.metricResultRefs);}catch{throw Error('근거 수치 연결 원장 형식 오류');}if(JSON.stringify(refs)!==JSON.stringify(metricIds))throw Error('근거 수치 연결 원장 불일치');}for(const id of metricIds){const m=link('metricResults',id,true);if(m.experimentId!==e.experimentId||m.resultSnapshotId!==e.source?.datasetSnapshotId)throw Error('근거 수치 참조 오류');}}
for(const d of [...maps.decisions.values(),...maps.hypothesisAssessments.values()]){const evidenceIds=uniqueRefs(d.evidenceIds,'검토 근거');for(const id of evidenceIds)link('evidence',id,true);if(d.sources!==undefined){if(!Array.isArray(d.sources)||d.sources.length!==evidenceIds.length||new Set(d.sources.map(source=>source.evidenceId)).size!==evidenceIds.length)throw Error('검토 근거 버전 목록 오류');for(const source of d.sources){const e=link('evidence',source.evidenceId,true);if(!evidenceIds.includes(e.id)||source.version!==e.source?.version)throw Error('검토 근거 고정 버전 불일치');}}if(d.hypothesisId)link('hypotheses',d.hypothesisId,true);}
for(const a of maps.disclosureApprovals.values()){const e=link('evidence',a.targetEvidenceId,true);const ds=link('datasetSnapshots',a.datasetSnapshotId,true);if(e.experimentId!==a.experimentId||ds.manifestHash!==a.manifestHash)throw Error('공개 범위 참조 오류');if(a.priorApprovalId)link('disclosureApprovals',a.priorApprovalId,true);}return true;}
