import {hydrateProject} from './archive.mjs';
export function mountObservations(area){
 const panel=document.createElement('section');panel.id='rndObservations';panel.innerHTML='<h3>현장·센서 관측</h3><p>미측정 값을 0으로 입력하지 마세요. 실제 관측·결측·미점검·관측 불가를 구분해 사유를 남깁니다.</p><details><summary>관측 기록 입력</summary><form id="observationForm"></form></details><p id="observationStatus" role="status"></p><p id="observationCount"></p><div id="observationRecords"></div><button type="button" id="observationPrevious">이전</button><button type="button" id="observationNext">다음</button>';area.append(panel);
 const find=id=>panel.querySelector('#'+id),form=find('observationForm'),status=find('observationStatus'),records=find('observationRecords');let epoch=0,selected=null,page=1;const drafts=new Map(),pending=new Set();const snapshot=()=>Object.fromEntries(new FormData(form));
 const labels={OBSERVED:'실제 관측',MISSING:'결측',NOT_INSPECTED:'미점검',UNOBSERVABLE:'관측 불가'};
 for(const [name,label,type] of [['experimentId','진행 중 실험 ID','text'],['unitId','관측 대상 ID','text'],['name','측정 항목','text'],['unit','측정 단위','text'],['value','실제 관측값 (0 포함)','number'],['reason','관측 설명·결측 또는 미점검 사유','text'],['observedAt','관측 시각 (이 PC의 시간대)','datetime-local']]){const row=document.createElement('label'),input=document.createElement('input');row.textContent=label;input.name=name;input.type=type;input.required=true;input.maxLength=4000;if(type==='number')input.step='any';row.append(input);form.append(row);}
 const state=document.createElement('select');state.name='status';state.setAttribute('aria-label','관측 상태');for(const [value,label] of Object.entries(labels)){const option=document.createElement('option');option.value=value;option.textContent=label;state.append(option);}form.prepend(state);const button=document.createElement('button');button.textContent='관측 공유 기록';form.append(button);
 const update=()=>{form.elements.value.disabled=state.value!=='OBSERVED';form.elements.value.required=state.value==='OBSERVED';};state.onchange=()=>{if(state.value!=='OBSERVED')form.elements.value.value='';update();};update();
 window.BringRndObservationPending=()=>pending.size>0;window.BringRndObservationDraftsPending=()=>[...drafts.entries()].some(([id,values])=>id!==selected&&Object.entries(values).some(([key,value])=>key!=='status'&&!!value));
 function render(project){panel.hidden=!project;records.replaceChildren();const all=[...(project?.research?.observations??[])].sort((a,b)=>b.at.localeCompare(a.at)||a.id.localeCompare(b.id)),pages=Math.max(1,Math.ceil(all.length/50));page=Math.min(page,pages);find('observationCount').textContent=`총 ${all.length}건 · ${page}/${pages}페이지 · 결측을 0으로 집계하지 않습니다`;find('observationPrevious').disabled=page===1;find('observationNext').disabled=page===pages;for(const record of all.slice((page-1)*50,page*50)){const row=document.createElement('article');row.textContent=`${record.name} · ${labels[record.status]} · ${record.status==='OBSERVED'?record.value+' '+record.unit:'값 없음'} · 대상 ${record.unitId} · 실험 ${record.experimentId} v${record.planRevision} · ${record.reason} · 관측 ${record.observedAt} · 작성 ${record.recordedBy}`;records.append(row);}}
 function select(project){const id=project?.id??null;if(id!==selected){if(selected)drafts.set(selected,snapshot());form.reset();window.BringRndClearInput(form.id);selected=id;page=1;const saved=drafts.get(id);if(saved){for(const [key,value] of Object.entries(saved))form.elements[key].value=value;if(Object.entries(saved).some(([key,value])=>key!=='status'&&value))form.dispatchEvent(new Event('input',{bubbles:true}));}update();status.textContent='';}render(project);}
 form.onsubmit=async event=>{event.preventDefault();const source=window.BringRndProject.current(),started=epoch,submitted=snapshot(),job=Symbol();try{if(!source?.revision||window.BringRndProject.hasUnsavedChanges())throw Error('프로젝트를 먼저 공유 저장하세요');if(pending.size)throw Error('저장 중입니다');const observation={...submitted,id:crypto.randomUUID(),observedAt:new Date(submitted.observedAt).toISOString(),value:submitted.status==='OBSERVED'?(submitted.value?.trim()?Number(submitted.value):null):null};pending.add(job);status.textContent='관측 공유 저장 중';const saved=hydrateProject(await window.bringCRM.rndWorkflow({projectId:source.id,expectedRevision:source.revision,command:{type:'observation',observation}}));if(started!==epoch)return;if(selected!==source.id){if(JSON.stringify(drafts.get(source.id))===JSON.stringify(submitted))drafts.set(source.id,{});}else if(JSON.stringify(snapshot())===JSON.stringify(submitted)){window.BringRndClearInput(form.id,window.BringRndInputVersion(form.id));form.reset();update();}const accepted=window.BringRndProject.acceptSharedResult(source,saved);status.textContent=accepted?'관측 공유 저장 완료':'공유 저장 완료 · 대기 중 입력은 유지했습니다. 최신 공유본과 비교하세요.';}catch(error){if(started===epoch)status.textContent='관측 저장 실패 · '+error.message;}finally{pending.delete(job);}};
 find('observationPrevious').onclick=()=>{page--;render(window.BringRndProject.current());};find('observationNext').onclick=()=>{page++;render(window.BringRndProject.current());};window.addEventListener('rnd-project-selected',event=>select(event.detail));window.addEventListener('rnd-session-reset',()=>{epoch++;drafts.clear();pending.clear();selected=null;form.reset();update();status.textContent='';select(null);});select(window.BringRndProject.current());
}
