import {summarizePortfolio} from './portfolio-summary.mjs';
import {createMetadataBackup,readMetadataBackup} from './backup.mjs';
import {indexProjects,searchPage} from './search.mjs';
import {createInputState} from './input-state.mjs';
import {previewImport,applyImport} from './import.mjs';
import {compareDraft,reapplyDraft} from './conflict.mjs';
import {askRndText} from './dialogs.mjs';
import {createProject,updateItem,assessTRL,overview,groups} from './portfolio.mjs';
import {createArchive,readArchive} from './archive.mjs';
const $=id=>(window.BringRndHost?.querySelector('#'+id)??document.getElementById(id));let project=null,selected=null,filter='전체',dirty=false;
const inputForms=createInputState();window.BringRndInputVersion=id=>inputForms.version(id);window.BringRndClearInput=(id,expected)=>inputForms.delete(id,expected);window.BringRndHost.addEventListener('input',e=>{const f=e.target.closest('form');if(f)inputForms.touch(f.id);});const dirtyProjects=new Set();function setDirty(value){dirty=value;if(value)dirtyProjects.add(project.id);else dirtyProjects.delete(project.id);renderPortfolio();}
let sessionEpoch=0;let connection=null;
let stagedEvidence=null;const stagedUploads=new Map();
const pendingUploads=new Map();
const drafts=new Map();
const manager=document.createElement('div');manager.className='actions';manager.innerHTML='<label>프로젝트 선택<select id="projectPicker" aria-label="프로젝트 선택"></select></label><button id="newProject" type="button">새 프로젝트</button><button id="loadProjects" type="button" class="secondary">공유 프로젝트 조회</button>';$('projectTitle').parentElement.before(manager);
const recoveryPanel=document.createElement('details');recoveryPanel.id='rndUploadRecovery';recoveryPanel.innerHTML='<summary>업로드 복구 기록</summary><p>이 PC의 현재 승인 계정 기록입니다. 업로드 당시 확인 정보이며 현재 Drive 원본은 다시 검증해야 합니다.</p><button type="button" id="rndRecoveryLoad">복구 기록 조회</button><div id="rndRecoveryRecords"></div>';manager.append(recoveryPanel);$('rndRecoveryLoad').onclick=async()=>{const epoch=sessionEpoch;try{const records=await window.bringCRM.rndUploadRecovery();if(epoch!==sessionEpoch)return;$('rndRecoveryRecords').replaceChildren();for(const record of records){const p=document.createElement('p');p.textContent=`${record.projectId} / ${record.artifactId} · ${record.versionId} · Drive ${record.providerFileId} · ${record.sizeBytes} bytes · SHA ${record.sha256} · ${record.status==='UPLOADED_UNVERIFIED'?'업로드됨·검증 미완료':'업로드 당시 검증'} ${record.verifiedAt??record.observedAt}`;const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='원본 재검증 후 초안 연결';button.onclick=async()=>{const epoch=sessionEpoch;button.disabled=true;try{if(project?.id!==record.projectId)throw Error('기록의 프로젝트를 먼저 선택하세요');if(!confirm('회사 Drive 원본을 재검증하고 해당 산출물의 근거 입력으로 보관할까요? 초안 반영과 공유 저장은 별도입니다.'))return;const result=await window.bringCRM.rndRestoreUpload({projectId:record.projectId,artifactId:record.artifactId,versionId:record.versionId});if(epoch!==sessionEpoch)return;const evidence={url:result.url,version:result.versionId,versionId:result.versionId,artifactId:record.artifactId,providerFileId:result.providerFileId,sha256:result.sha256,sizeBytes:result.sizeBytes,verifiedAt:result.verifiedAt};stagedUploads.set(record.projectId+':'+record.artifactId,evidence);if(project?.id===record.projectId&&selected===record.artifactId){stagedEvidence=evidence;$('itemForm').elements.evidenceUrl.value=evidence.url;$('itemForm').elements.version.value=evidence.version;}say('복구 원본 재검증 완료 · 해당 산출물에서 초안 반영 후 공유 저장하세요.');}catch(error){if(epoch===sessionEpoch)say(`복구 미완료 · ${error.message}`);}finally{button.disabled=false;}};p.append(button);$('rndRecoveryRecords').append(p);}if(!records.length)$('rndRecoveryRecords').textContent='현재 계정의 이 PC 복구 기록이 없습니다.';}catch(error){if(epoch===sessionEpoch)$('rndRecoveryRecords').textContent=`복구 기록 조회 실패 · ${error.message}`;}};
let reapplyBackup=null;const backupButton=document.createElement('button');backupButton.type='button';backupButton.className='secondary';backupButton.textContent='재적용 전 초안 보관';backupButton.disabled=true;backupButton.onclick=()=>download({kind:'BRING_RND_PROJECT',project:reapplyBackup},`rnd-before-reapply-${reapplyBackup.id}.json`);manager.append(backupButton);
const compareButton=document.createElement('button');compareButton.id='compareProject';compareButton.type='button';compareButton.className='secondary';compareButton.textContent='최신 공유본과 비교';manager.append(compareButton);
compareButton.onclick=async()=>{const epoch=sessionEpoch;try{if(!project||!connection?.store)throw Error('프로젝트와 공유 연결이 필요합니다');const source=structuredClone(project),store=connection.store;const user=window.bringCRM?.authState?(await window.bringCRM.authState()).user:null;if(epoch!==sessionEpoch)return;const latest=store.getProject?await store.getProject(source.id):(await store.listProjects()).find(p=>p.id===source.id);if(epoch!==sessionEpoch)return;if(!latest)throw Error('아직 공유 저장되지 않은 프로젝트입니다');const diffs=compareDraft(source,latest);const dialog=document.createElement('dialog');dialog.className='rnd-text-dialog';const title=document.createElement('h3');title.textContent=`최신 공유본 r${latest.revision}과 초안 비교`;const info=document.createElement('p');info.textContent='적용할 항목을 선택하세요. 상태·근거·판정·승인·연구 이력은 최신 공유본을 유지합니다. 적용은 초안에만 반영됩니다.';dialog.append(title,info);const checks=[];for(const diff of diffs){const label=document.createElement('label');const check=document.createElement('input');check.type='checkbox';check.value=diff.path;checks.push(check);const text=document.createElement('span');text.textContent=`${diff.label}\n공유: ${diff.shared}\n초안: ${diff.draft}`;label.append(check,text);dialog.append(label);}const reason=document.createElement('input');reason.placeholder='비교 후 재적용 이유';reason.setAttribute('aria-label','재적용 이유');dialog.append(reason);const status=document.createElement('p');status.setAttribute('role','status');dialog.append(status);const actions=document.createElement('div');actions.className='actions';for(const [label,type]of [['취소','cancel'],['선택 수정 재적용','apply']]){const button=document.createElement('button');button.type='button';button.textContent=label;button.onclick=()=>{if(type==='cancel'){dialog.close();return;}try{if(epoch!==sessionEpoch)throw Error('로그인 세션 변경 · 비교 적용 중단');if(JSON.stringify(project)!==JSON.stringify(source))throw Error('비교 중 프로젝트가 변경됐습니다. 다시 비교하세요');const next=reapplyDraft(source,latest,checks.filter(x=>x.checked).map(x=>x.value),user?.uid??'현재 사용자',reason.value);reapplyBackup=structuredClone(source);backupButton.disabled=false;project=next;setDirty(true);keep();render();say('선택 수정 재적용 완료 · 최신 revision 기준 초안입니다. 공유 저장하세요.');dialog.close();}catch(error){status.textContent=error.message;}};actions.append(button);}dialog.append(actions);dialog.addEventListener('close',()=>dialog.remove(),{once:true});document.body.append(dialog);dialog.showModal();}catch(error){say(`비교 실패 · ${error.message}`);}};
const searchBox=document.createElement('details');searchBox.id='rndMetadataSearch';searchBox.innerHTML='<summary>프로젝트·연구 자료 검색</summary><p>이 세션에서 조회하거나 작성한 메타데이터를 검색합니다. 최신 자료는 공유 프로젝트 조회 후 확인하세요.</p><label>검색어<input type="search" id="rndSearchQuery" placeholder="이름, 담당자, 가설, 자료 ID"></label><label>자료 종류<select id="rndSearchType"><option value="">전체</option></select></label><p id="rndSearchCount" role="status"></p><div id="rndSearchResults"></div><button type="button" id="rndSearchPrevious">이전</button><button type="button" id="rndSearchNext">다음</button>';manager.append(searchBox);
for(const type of ['프로젝트','산출물','실험','데이터셋','근거','측정 결과','의사결정','가설','가설 판정','공개 범위 검토']){const o=document.createElement('option');o.value=type;o.textContent=type;$('rndSearchType').append(o);}
const portfolioPanel=document.createElement('details');portfolioPanel.id='rndPortfolioOverview';portfolioPanel.innerHTML='<summary>전체 R&D 현황</summary><p>현재 세션 조회본·초안 기준입니다. 준비율은 필수 산출물 승인 비율이며 기술성·사업성을 자동 판정하지 않습니다.</p><p id="rndPortfolioTotals" role="status"></p><div id="rndPortfolioRows"></div>';manager.append(portfolioPanel);
function renderPortfolio(){const values=[...drafts.values()].map(p=>p.id===project?.id?project:p);const s=summarizePortfolio(values,dirtyProjects);$('rndPortfolioTotals').textContent=`기준일 ${s.today} · 프로젝트 ${s.projects}개 · 기한 지남 ${s.overdue}(필수 ${s.overdueRequired}) · 필수 승인 ${s.approved}/${s.required} · 준비율 ${s.percent===null?'—':s.percent.toFixed(1)+'%'} · 막힘 ${s.blocked} · 담당 미지정 ${s.unassigned} · 진행 실험 ${s.activeExperiments} · 근거 검토 대기 ${s.evidenceAwaitingReview} · 미공유 초안 ${s.unsaved}`;$('rndPortfolioRows').replaceChildren();for(const row of s.rows.slice(0,50)){const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent=`${row.title} · 기한 지남 ${row.overdue}(필수 ${row.overdueRequired}) · TRL ${row.currentTRL??'미평가'} · 필수 승인 ${row.approved}/${row.required} · 막힘 ${row.blocked} · 진행 실험 ${row.activeExperiments} · 근거 검토 ${row.evidenceAwaitingReview} · r${row.revision}${row.unsaved?' · 미공유 초안':''}`;button.onclick=()=>{keep();switchProject(drafts.get(row.id));};$('rndPortfolioRows').append(button);}if(s.rows.length>50){const p=document.createElement('p');p.textContent='앞 50개 표시 · 나머지는 프로젝트 검색에서 선택하세요.';$('rndPortfolioRows').append(p);}}
let searchIndex=[],searchCurrent=1;
function renderSearch(){renderPortfolio();searchIndex=indexProjects([...drafts.values()].map(p=>p.id===project?.id?project:p));const result=searchPage(searchIndex,{query:$('rndSearchQuery').value,type:$('rndSearchType').value,page:searchCurrent});searchCurrent=result.page;$('rndSearchCount').textContent=`${result.total}개 · ${result.page}/${result.pages}페이지 · 조회·초안 메타데이터`;$('rndSearchPrevious').disabled=result.page===1;$('rndSearchNext').disabled=result.page===result.pages;$('rndSearchResults').replaceChildren();for(const row of result.rows){const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent=`${row.type} · ${row.label} · ${row.projectTitle} · r${row.revision}${row.status?' · '+row.status:''}`;button.onclick=()=>{keep();switchProject(drafts.get(row.projectId));if(row.type==='산출물'){selected=row.id;edit();}say(`검색 프로젝트 선택 · ${row.type} ${row.id} · 최신 공유 여부를 확인하세요.`);};$('rndSearchResults').append(button);}}
for(const id of ['rndSearchQuery','rndSearchType'])$(id).addEventListener('input',()=>{searchCurrent=1;renderSearch();});$('rndSearchPrevious').onclick=()=>{searchCurrent--;renderSearch();};$('rndSearchNext').onclick=()=>{searchCurrent++;renderSearch();};
function projectOptions(){const picker=$('projectPicker');picker.replaceChildren();for(const p of drafts.values()){const option=document.createElement('option');option.value=p.id;option.textContent=p.title;picker.append(option);}picker.value=project?.id??'';searchIndex=indexProjects(drafts.values());renderSearch();}
function keep(){if(!project)return;drafts.set(project.id,structuredClone(project));projectOptions();}
const archiveButton=document.createElement('button');archiveButton.textContent='메타데이터 백업 · 원본 제외';archiveButton.className='secondary';archiveButton.id='archiveExport';archiveButton.onclick=async()=>{const epoch=sessionEpoch;try{keep();const source=[...drafts.values()];if(!connection?.store?.listVisits)throw Error('기준선 공유 조회 연결이 필요합니다');const visits=await connection.store.listVisits();if(epoch!==sessionEpoch)return;const pending=window.BringRndBaselineDrafts?.()??[];const sharedIds=new Set(visits.map(v=>v.id));const backup=await createMetadataBackup(source,project.id,[...visits,...pending.filter(v=>!sharedIds.has(v.id))]);if(epoch!==sessionEpoch)return;download(backup,'bring-rnd-metadata-backup.json');say('메타데이터 백업 파일 생성 · 해시·목록 및 복원 초안 포함 · Drive 원본 파일은 미포함');}catch(error){say(`백업 생성 실패 · ${error.message}`);}};manager.append(archiveButton);
const archiveLabel=document.createElement('label');archiveLabel.textContent='전체 프로젝트 복원';const archiveInput=document.createElement('input');archiveInput.type='file';archiveInput.accept='.json';archiveInput.id='archiveImport';archiveLabel.append(archiveInput);manager.append(archiveLabel);async function importProjects(incoming,warning=''){keep();const current=[...drafts.values()];const plan=previewImport(current,incoming);if(!confirm(`${warning}\n복원 사전 검증: ${plan.total}개 · 신규 ${plan.additions.length}개 · 동일 ID ${plan.conflicts.length}개는 유지합니다. 신규 프로젝트만 초안에 추가할까요?`))return;for(const p of applyImport(current,incoming))drafts.set(p.id,p);for(const id of plan.additions)dirtyProjects.add(id);if(!project&&plan.additions.length)switchProject(drafts.get(plan.additions[0]));else projectOptions();say(`복원 초안 추가 ${plan.additions.length}개 · 충돌 ${plan.conflicts.length}개 유지 · 공유 저장 전입니다.`);}
archiveInput.onchange=async e=>{const epoch=sessionEpoch;try{const result=await readMetadataBackup(await e.target.files[0].text());if(epoch!==sessionEpoch)return;await importProjects(result.archive.projects,result.warning+(result.visits?.length?' · 기준선 기록은 이 파일에 보관되며 이번 프로젝트 초안 복원에 자동 적용하지 않습니다':''));}catch(error){say(`복원 실패 · ${error.message}`);}e.target.value='';};
function switchProject(p){project=structuredClone(p);selected=project.items[0].id;dirty=dirtyProjects.has(project.id);render();$('roadmapLevel').value='1';$('roadmapLevel').onchange();projectOptions();}
window.addEventListener('rnd-project-saved',e=>{if(e.detail.id===project?.id){project=e.detail;setDirty(false);keep();render();}});
$('newProject').onclick=async()=>{const epoch=sessionEpoch;keep();const title=await askRndText('새 프로젝트 이름');if(epoch!==sessionEpoch||!title?.trim())return;const p=createProject(crypto.randomUUID(),title.trim());drafts.set(p.id,p);switchProject(p);setDirty(true);say('새 프로젝트 초안 생성 · 공유 저장 전입니다.');};
$('projectPicker').onchange=async e=>{const target=e.target.value;keep();try{switchProject(drafts.get(target));say('프로젝트 전환 완료 · 이전 수정은 이번 세션 초안에 유지됩니다.');}catch(error){say(error.message);}};
$('loadProjects').onclick=async()=>{const epoch=sessionEpoch;try{if(!connection?.store)throw Error('연구 저장소 연결 필요');keep();const remote=await connection.store.listProjects();if(epoch!==sessionEpoch)return;let conflicts=0;for(const p of remote){if(drafts.has(p.id)){conflicts++;continue;}drafts.set(p.id,p);}if(!project&&drafts.size)switchProject(drafts.values().next().value);projectOptions();say(`공유 프로젝트 ${remote.length}개 조회 · 세션 초안 ${conflicts}개는 덮어쓰지 않았습니다.`);}catch(error){say(`공유 프로젝트 조회 실패 · ${error.message}`);}};
window.addEventListener('rnd-connection',e=>{connection=e.detail;});
window.dispatchEvent(new Event('rnd-request-connection'));
window.addEventListener('beforeunload',e=>{if(dirtyProjects.size){e.preventDefault();e.returnValue='';}});
const say=text=>$('portfolioStatus').textContent=text;
window.BringRndProject={acceptSharedResult:(source,saved)=>{const local=project?.id===source.id?project:drafts.get(source.id);if(JSON.stringify(local)!==JSON.stringify(source))return false;if(project?.id===source.id&&inputForms.size>(inputForms.version("crmContextForm")>0?1:0))return false;drafts.set(source.id,structuredClone(saved));dirtyProjects.delete(source.id);if(project?.id===source.id){project=structuredClone(saved);dirty=false;render();}projectOptions();return true;},projectIds:()=>[...drafts.keys()],current:()=>structuredClone(project),hasUnsavedChanges:()=>dirty,pendingState:()=>({projects:dirtyProjects.size,forms:inputForms.size,uploads:pendingUploads.size+stagedUploads.size})};
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function render(){renderSearch();for(const node of [...$('projectArea').children]){if(node===manager||node.tagName==='H2'||node.id==='portfolioStatus')continue;node.hidden=!project;}$('trlArea').hidden=!project;archiveButton.disabled=!project;if(!project){$('deliverables').replaceChildren();$('portfolioStatus').textContent='새 프로젝트를 만들거나 공유 프로젝트를 조회해 선택하세요.';return;}const s=overview(project);$('projectTitle').value=project.title;$('portfolioSummary').textContent=`필수 승인 ${s.requiredApproved}/${s.requiredTotal} · 준비율 ${s.percent===null?'—':s.percent.toFixed(1)+'%'} · 선택 ${s.optionalTotal}개 · 전체 승인 ${s.approved}/${s.total} · 막힘 ${s.blocked} · 담당 미지정 ${s.unassigned} · 현재 TRL ${project.currentTRL??'미평가'}`;$('deliverables').replaceChildren();for(const item of project.items.filter(x=>filter==='전체'||x.group===filter)){const button=document.createElement('button');button.className='deliverable secondary';button.textContent=`${item.required===false?'선택':'필수'} · ${item.group} · ${item.title}\n${({todo:'할 일',active:'진행',review:'검토 대기',approved:'승인',blocked:'막힘'})[item.status]} · ${item.owner||'담당 미지정'}`;button.onclick=()=>{selected=item.id;edit();};$('deliverables').append(button);}$('history').replaceChildren();for(const h of [...project.history,...project.assessments].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,20)){const p=document.createElement('p');p.textContent=`${h.at} · ${h.actor} · ${h.reason}${h.selfReview?' · 자기검토':''}`;$('history').append(p);}edit();window.dispatchEvent(new CustomEvent('rnd-project-selected',{detail:structuredClone(project)}));}
const requirementLabel=document.createElement('label');requirementLabel.textContent='산출물 구분';const requirementSelect=document.createElement('select');requirementSelect.name='required';for(const [value,label]of [['true','필수'],['false','선택']]){const option=document.createElement('option');option.value=value;option.textContent=label;requirementSelect.append(option);}requirementLabel.append(requirementSelect);$('itemForm').prepend(requirementLabel);
function edit(){stagedEvidence=null;const item=project.items.find(x=>x.id===selected)??project.items[0];selected=item.id;stagedEvidence=stagedUploads.get(project.id+':'+selected)??item.evidence[0]??null;requirementSelect.value=item.required===false?'false':'true';$('itemTitle').textContent=item.title;for(const key of ['goal','owner','due','criteria','status','result','reviewer'])$('itemForm').elements[key].value=item[key];$('itemForm').elements.evidenceUrl.value=stagedEvidence?.url??'';$('itemForm').elements.version.value=stagedEvidence?.version??'';}
for(const group of ['전체',...groups]){const button=document.createElement('button');button.textContent=group;button.className='secondary';button.onclick=()=>{filter=group;render();};$('groupFilters').append(button);}
$('projectTitle').oninput=()=>inputForms.touch('projectTitle');
$('projectTitle').onchange=e=>{inputForms.delete('projectTitle');project.history.push({kind:'title',actor:'현재 사용자',reason:'프로젝트 제목 수정',before:project.title,after:e.target.value,at:new Date().toISOString()});project.title=e.target.value;setDirty(true);renderSearch();};
$('itemForm').onsubmit=e=>{e.preventDefault();try{const f=new FormData(e.target),patch=Object.fromEntries(['goal','owner','due','criteria','status','result','reviewer'].map(k=>[k,f.get(k)]));patch.required=f.get('required')!=='false';patch.evidence=f.get('evidenceUrl')?[{...(stagedEvidence?.url===f.get('evidenceUrl')?stagedEvidence:{}),url:f.get('evidenceUrl'),version:f.get('version')}]:[];project=updateItem(project,selected,patch,f.get('actor'),f.get('changeReason'));stagedUploads.delete(project.id+':'+selected);inputForms.delete('itemForm');setDirty(true);render();say('초안에 반영했습니다 · 공유 저장 전입니다.');}catch(error){say(error.message);}};
$('portfolioExport').onclick=()=>{download({kind:'BRING_RND_PROJECT',project},`rnd-project-${project.id}.json`);say('프로젝트 초안 파일 내보내기 완료 · 공유 저장은 아닙니다.');};
$('portfolioImport').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.kind!=='BRING_RND_PROJECT')throw Error('지원하지 않는 프로젝트 파일');await importProjects([data.project]);}catch(error){say(`불러오기 실패 · ${error.message}`);}e.target.value='';};
const savingProjects=new Set();
$('portfolioSave').onclick=async()=>{const source=structuredClone(project);try{if(!source)throw Error('프로젝트를 먼저 선택하세요');if(savingProjects.has(source.id))throw Error('이 프로젝트를 저장 중입니다');if(!connection?.store)throw Error('연구 저장소 연결 필요');savingProjects.add(source.id);const saved=await connection.store.saveProject(source);const local=project?.id===source.id?project:drafts.get(source.id);if(JSON.stringify(local)===JSON.stringify(source)){drafts.set(source.id,saved);dirtyProjects.delete(source.id);if(project?.id===source.id){project=saved;dirty=false;render();}projectOptions();say(project?.id===source.id?'프로젝트 공유 저장 완료':`${saved.title} · 공유 저장 완료 · 현재 프로젝트 유지`);}else{say('요청한 버전은 공유 저장했습니다 · 대기 중 추가 수정은 초안에 유지됩니다. 최신 공유본과 비교 후 저장하세요.');}}catch(error){say(`공유 저장 실패 · ${error.message} · 초안은 유지됩니다.`);}finally{if(source)savingProjects.delete(source.id);}};
$('trlForm').onsubmit=e=>{e.preventDefault();try{const f=new FormData(e.target);project=assessTRL(project,Number(f.get('level')),f.get('actor'),f.get('reviewer'),f.get('reason'),[{url:f.get('url'),version:f.get('version')}]);inputForms.delete('trlForm');setDirty(true);render();say('TRL 판정을 초안에 기록했습니다 · 공유 저장 전입니다.');}catch(error){say(error.message);}};
$('roadmapLevel').onchange=()=>{if(!project)return;const stage=project.trl[Number($('roadmapLevel').value)-1];for(const key of ['goal','criteria','owner','due','result'])$('roadmapForm').elements[key].value=stage[key];};
$('roadmapForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),stage=project.trl[Number($('roadmapLevel').value)-1],before=structuredClone(stage);for(const key of ['goal','criteria','owner','due','result'])stage[key]=f.get(key);project.history.push({kind:'trl-plan',id:stage.level,before,after:structuredClone(stage),actor:f.get('actor'),reason:f.get('changeReason'),at:new Date().toISOString()});project.targetTRL=Number($('roadmapLevel').value);inputForms.delete('roadmapForm');setDirty(true);render();say('단계별 개발 계획을 초안에 반영했습니다 · 현재 TRL은 그대로입니다.');};
$('projectUpload').onclick=async()=>{try{if(!connection?.upload)throw Error('Drive 연결 필요');const epoch=sessionEpoch,projectId=project.id,artifactId=selected;const uploadKey=projectId+':'+artifactId;if(!pendingUploads.has(uploadKey))pendingUploads.set(uploadKey,crypto.randomUUID());const result=await connection.upload(undefined,say,{projectId,artifactId,versionId:pendingUploads.get(uploadKey)});if(epoch!==sessionEpoch)throw Error('로그인 세션 변경 · 이전 업로드 정보 적용 중단');const uploadedEvidence={url:result.url,version:result.versionId,versionId:result.versionId,artifactId,providerFileId:result.id,sha256:result.hash,sizeBytes:Number(result.size),verifiedAt:result.verifiedAt};stagedUploads.set(uploadKey,uploadedEvidence);pendingUploads.delete(uploadKey);if(project?.id!==projectId||selected!==artifactId){say(`Drive 원본 확인 완료 · ${result.id} · 업로드한 산출물로 돌아가 반영하세요.`);return;}stagedEvidence=uploadedEvidence;$('itemForm').elements.evidenceUrl.value=result.url;$('itemForm').elements.version.value=result.versionId;pendingUploads.delete(uploadKey);say(`Drive 원본 확인 완료 · ${result.id} · 산출물 반영 후 공유 저장하세요.`);}catch(error){say(`업로드 실패 · ${error.message}`);}};
render();projectOptions();

window.addEventListener('rnd-session-reset',()=>{sessionEpoch++;for(const dialog of document.querySelectorAll('dialog.rnd-text-dialog[open]'))dialog.close('session-reset');$('rndRecoveryRecords').replaceChildren();$('rndSearchQuery').value='';$('rndSearchType').value='';searchCurrent=1;inputForms.clear();for(const f of window.BringRndHost.querySelectorAll('#projectArea form,#trlArea form'))f.reset();for(const input of window.BringRndHost.querySelectorAll('input[type=file]'))input.value='';$('projectTitle').value='';$('portfolioSummary').textContent='';$('history').replaceChildren();project=null;selected=null;dirty=false;drafts.clear();dirtyProjects.clear();pendingUploads.clear();stagedUploads.clear();stagedEvidence=null;reapplyBackup=null;backupButton.disabled=true;projectOptions();render();window.dispatchEvent(new CustomEvent('rnd-project-selected',{detail:null}));});
