const {randomUUID,createHash}=require('node:crypto');
function assertVisitProjectBinding(previous,input){if(previous&&(previous.projectId??null)!==(input.projectId??null))throw Error('기준선의 연결 프로젝트는 일반 저장으로 변경할 수 없습니다');}
function researchFingerprint(value){const normalize=x=>{if(x===null||x===undefined)return null;if(typeof x!=='object')return x;const values=Object.values(x);const keyed=values.length&&values.every(v=>v&&typeof v==='object'&&typeof v.id==='string')?Object.fromEntries(values.map(v=>[v.id,v])):x;const entries=Object.entries(keyed).map(([k,v])=>[k,normalize(v)]).filter(([,v])=>v!==null).sort(([a],[b])=>a.localeCompare(b));return entries.length?Object.fromEntries(entries):null;};return JSON.stringify(normalize(value));}
const key=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(x);
function researchList(x){return Array.isArray(x)?x:Object.values(x??{});}
function rndPatch(previous,value){const patch={};const base=`projects/${value.id}/`;for(const [field,item]of Object.entries(value)){if(['research','history','assessments'].includes(field))continue;patch[base+field]=item;}for(const field of ['history','assessments']){const old=researchList(previous?.[field]);const next=researchList(value[field]);if(next.length<old.length)throw Error('감사 기록은 삭제할 수 없습니다');next.forEach((entry,i)=>{if(i<old.length&&researchFingerprint(entry)!==researchFingerprint(old[i]))throw Error('감사 기록은 수정할 수 없습니다');if(i>=old.length)patch[base+field+'/'+i]=entry;});}if(value.research){for(const field of ['experiments','evidence','decisions','history','hypotheses','hypothesisAssessments','datasetSnapshots','disclosureApprovals','metricResults']){const old=Object.fromEntries(researchList(previous?.research?.[field]).map((e,i)=>[field==='history'?String(i):e.id,e]));const next=Object.fromEntries(researchList(value.research[field]).map((e,i)=>[field==='history'?String(i):e.id,e]));for(const id of Object.keys(old))if(!next[id])throw Error('연구 기록은 삭제할 수 없습니다');for(const [id,entry]of Object.entries(next)){if(!key(id))throw Error('연구 기록 ID 오류');if(researchFingerprint(old[id])!==researchFingerprint(entry))patch[base+'research/'+field+'/'+id]=entry;}}}return patch;}
function createRndRepository({auth,token,databaseUrl,fetch:request=globalThis.fetch,onWriteAttempt}){
 function actor(write=false){const user=auth()?.user;if(!user?.uid||user.mustChangePassword)throw Error('로그인이 필요합니다');if(!['admin','member','viewer'].includes(user.role)||(write&&user.role==='viewer'))throw Error('R&D 변경 권한이 없습니다');return {...user};}
 function unchanged(user){const now=actor();if(now.uid!==user.uid||now.role!==user.role||now.email!==user.email)throw Error('로그인 세션이 변경되었습니다');}
 async function url(collection,id){if(!['projects','visits'].includes(collection)||id!==undefined&&!key(id))throw Error('R&D 대상 ID 오류');const value=await token();return `${databaseUrl}/rndControl/${collection}${id?'/'+id:''}.json?auth=${encodeURIComponent(value)}`;}
 return{
 async get(collection,id){if(!key(id))throw Error('R&D 대상 ID 오류');const user=actor();const endpoint=await url(collection,id);unchanged(user);const response=await request(endpoint,{method:'GET',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error(`R&D 공유 조회 실패 (${response.status})`);const value=await response.json();unchanged(user);if(!value)throw Error('프로젝트를 먼저 공유 저장하세요');if(value.id!==id)throw Error('R&D 기록 ID 불일치');return value;},
 async list(collection){const user=actor();const endpoint=await url(collection);unchanged(user);const response=await request(endpoint,{method:'GET',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error(`R&D 공유 조회 실패 (${response.status})`);const data=await response.json();unchanged(user);return Object.values(data??{});},
 async save(collection,input,{allowResearchChange=false}={}){const user=actor(true);if(!key(input?.id)||!Number.isInteger(input.revision??0)||(input.revision??0)<0)throw Error('R&D 대상 ID·버전 오류');const endpoint=await url(collection,input.id);unchanged(user);const response=await request(endpoint,{method:'GET',headers:{'X-Firebase-ETag':'true'},signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error(`R&D 공유 조회 실패 (${response.status})`);const previous=await response.json();unchanged(user);if((previous?.revision??0)!==(input.revision??0))throw Error('동시편집 충돌: 최신 프로젝트를 다시 불러오세요');if(!allowResearchChange&&researchFingerprint(previous?.research)!==researchFingerprint(input.research))throw Error('연구 판정은 전용 승인 작업으로 변경하세요');if(collection==='visits')assertVisitProjectBinding(previous,input);const etag=response.headers.get('etag');if(!etag)throw Error('원격 버전 확인 실패');const value={...input,operationId:randomUUID(),revision:(input.revision??0)+1,updatedBy:user.uid,updatedAt:new Date().toISOString()};const body=collection==='projects'?rndPatch(previous,value):{['visits/'+value.id]:value};if(onWriteAttempt){await onWriteAttempt(user.uid,{operationId:value.operationId,collection,recordId:value.id,revision:value.revision,contentSHA256:createHash('sha256').update(researchFingerprint(value)).digest('hex'),at:value.updatedAt});unchanged(user);}const writeToken=await token();unchanged(user);let saved;try{saved=await request(`${databaseUrl}/rndControl.json?auth=${encodeURIComponent(writeToken)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});if(saved.ok)await saved.json();}catch(error){unchanged(user);try{const recoveryEndpoint=await url(collection,input.id);unchanged(user);const recovery=await request(recoveryEndpoint,{method:'GET',signal:AbortSignal.timeout(20000)});if(recovery.ok){const observed=await recovery.json();unchanged(user);if(observed?.operationId===value.operationId&&researchFingerprint(observed)===researchFingerprint(value))return value;}}catch(recoveryError){unchanged(user);}throw Error(`저장 결과 확인 불가 · 작업 ${value.operationId} · 최신 기록을 조회하고 입력 초안을 보관하세요`);}if(saved.status===412)throw Error('동시편집 충돌: 먼저 저장된 내용을 덮어쓰지 않았습니다');if(saved.status===403){const latest=await request(endpoint,{method:'GET',signal:AbortSignal.timeout(20000)});unchanged(user);if(latest.ok&&(await latest.json())?.revision!==(input.revision??0))throw Error('동시편집 충돌: 최신 프로젝트를 불러와 비교하세요');}if(!saved.ok)throw Error(`R&D 공유 저장 실패 (${saved.status})`);unchanged(user);return value;}
 };
}
module.exports={assertVisitProjectBinding,createRndRepository,researchFingerprint,rndPatch};
