import {codeSource} from './code-source.mjs';
import {createMetricResult,measuredMetrics} from './metric-result.mjs';
import {evidenceQuality} from './evidence-quality.mjs';
import {recordDisclosure} from './disclosure.mjs';
import {createDatasetSnapshot,verifyDatasetManifest} from './dataset.mjs';
const hypothesisStatements=["분산 소형건물을 공동관리하고 데이터를 활용하면 품질을 유지하면서 인력 대비 관리능력을 높일 수 있다", "지역적 관리 밀도가 높아지면 이동·방문을 포함한 동당 관리원가가 줄어든다", "건물·설비·사건·작업·결과의 구조화가 누락·조회시간·재방문을 줄인다", "필요한 최소 관측으로 추가 확인이 필요한 현장을 선별할 수 있다", "상태·이력을 이용한 조치 추천이 단순 규칙·현행 방식보다 판단과 처리에 도움을 준다", "전체 설치·통신·입력·오경보 대응비를 포함해도 동당 원가와 생산성이 개선된다", "고객이 해당 서비스에 비용을 지불하고 재이용한다", "검증된 구성요소가 다른 건물·시설에도 재사용된다"];
const copy=value=>structuredClone(value);
const required=['id','hypothesis','question','comparison','population','period','metrics','analysis','success','stop','reviewerUid'];
function text(value){return typeof value==='string'&&!!value.trim();}
function original(source){try{return text(source.version)&&['https:','http:'].includes(new URL(source.url).protocol)&&Number.isInteger(source.sampleUnits)&&source.sampleUnits>0;}catch{return false;}}
export function applyResearch(project,command,user){
 if(!user?.uid||!['member','admin'].includes(user.role))throw Error('연구 변경 권한이 없습니다');
 const p=copy(project);p.research??={experiments:[],evidence:[],decisions:[],history:[]};const r=p.research;for(const key of ['experiments','evidence','decisions','history','hypotheses','hypothesisAssessments','datasetSnapshots','disclosureApprovals','metricResults'])r[key]??=[];
 const before=copy(r);const find=()=>{const exp=r.experiments.find(e=>e.id===command.id);if(!exp)throw Error('실험을 찾을 수 없습니다');return exp;};
 if(command.type==='hypothesisTemplate'){if(!/^[a-zA-Z0-9_-]{1,40}$/.test(command.frameworkVersion??'')||!text(command.reviewerUid))throw Error('가설 체계 버전과 지정 검토자가 필요합니다');if(r.hypotheses.some(h=>h.frameworkVersion===command.frameworkVersion))throw Error('이미 적용한 가설 체계입니다');r.hypotheses.push(...hypothesisStatements.map((statement,i)=>({id:`${p.id}-${command.frameworkVersion}-H${i}`,projectId:p.id,frameworkVersion:command.frameworkVersion,code:`H${i}`,statement,scope:i===0?'overall':i===7?'long_term':'core',status:'NOT_TESTED',reviewerUid:command.reviewerUid,createdBy:user.uid})));}
 else if(command.type==='assessHypothesis'){const h=r.hypotheses.find(h=>h.id===command.hypothesisId);if(!h||h.projectId!==p.id)throw Error('현재 프로젝트 가설을 선택하세요');if(user.uid!==h.reviewerUid&&user.role!=='admin')throw Error('지정 가설 검토자만 판정할 수 있습니다');if(!text(command.id)||r.hypothesisAssessments.some(a=>a.id===command.id)||!['SUPPORTED','NOT_SUPPORTED','INCONCLUSIVE'].includes(command.status)||!text(command.reason)||!Array.isArray(command.evidenceIds)||!command.evidenceIds.length)throw Error('가설 판정에는 고유 ID·판정·이유·승인 근거가 필요합니다');const evidence=command.evidenceIds.map(id=>r.evidence.find(e=>e.id===id&&e.status==='approved'));if(evidence.some(e=>!e||!r.experiments.some(exp=>exp.id===e.experimentId&&exp.plan.hypothesis===h.code&&exp.plan.frameworkVersion===h.frameworkVersion)))throw Error('해당 가설의 승인 근거만 연결할 수 있습니다');r.hypothesisAssessments.push({id:command.id,hypothesisId:h.id,projectId:p.id,frameworkVersion:h.frameworkVersion,status:command.status,reason:command.reason,evidenceIds:copy(command.evidenceIds),sources:evidence.map(e=>({evidenceId:e.id,version:e.source.version})),assessedBy:user.uid,at:new Date().toISOString()});}
 else if(['create','createDraft'].includes(command.type)){const plan=command.plan;if(!(command.type==='createDraft'?text(plan?.id):required.every(k=>text(plan?.[k])))||!/^H[0-7]$/.test(plan?.hypothesis))throw Error('실험계획 필수 항목을 확인하세요');if(r.experiments.some(e=>e.id===plan.id))throw Error('중복 실험 ID');const candidates=r.hypotheses.filter(h=>h.code===plan.hypothesis&&(!plan.frameworkVersion||h.frameworkVersion===plan.frameworkVersion));if(r.hypotheses.length&&candidates.length!==1)throw Error('실험의 가설 체계 버전을 지정하세요');const scopedPlan=candidates.length?{...plan,frameworkVersion:candidates[0].frameworkVersion}:plan;r.experiments.push({id:plan.id,plan:copy(scopedPlan),authorUid:user.uid,status:'draft',planVersion:1});}
 else if(command.type==='revisePlan'){const parent=r.experiments.find(e=>e.id===command.parentExperimentId);if(!parent||!['approved','running','closed'].includes(parent.status))throw Error('승인된 원계획을 선택하세요');if(!text(command.id)||r.experiments.some(e=>e.id===command.id))throw Error('새 실험계획 고유 ID가 필요합니다');if(!text(command.reason)||!text(command.appliesTo))throw Error('계획 변경 이유와 적용 대상이 필요합니다');if(r.experiments.some(e=>e.parentExperimentId===parent.id))throw Error('이미 등록한 변경 계획이 있습니다. 해당 버전을 확인하세요');const allowed=['question','comparison','population','period','metrics','analysis','success','stop','reviewerUid'];if(!command.patch||!Object.keys(command.patch).length||Object.keys(command.patch).some(k=>!allowed.includes(k)))throw Error('가설·체계·원계획 ID는 변경할 수 없습니다');const plan={...copy(parent.frozenPlan),...copy(command.patch),id:command.id};if(!required.every(k=>text(plan[k])))throw Error('변경 계획 필수 항목을 확인하세요');r.experiments.push({id:command.id,plan,authorUid:user.uid,status:'draft',planVersion:parent.planVersion+1,parentExperimentId:parent.id,rootExperimentId:parent.rootExperimentId??parent.id,parentPlanVersion:parent.planVersion,changeReason:command.reason.trim(),appliesTo:command.appliesTo.trim()});}
 else if(command.type==='editDraft'){const exp=find();if(exp.status!=='draft'||(exp.authorUid!==user.uid&&user.role!=='admin'))throw Error('초안 작성자/관리자만 보완할 수 있습니다');if(!text(command.reason))throw Error('초안 보완 이유가 필요합니다');const patch=command.patch??{};if(Object.keys(patch).some(k=>!required.includes(k)||['id','hypothesis'].includes(k))||Object.values(patch).some(v=>typeof v!=='string'))throw Error('초안 보완 항목 오류');Object.assign(exp.plan,patch);}
 else if(command.type==='approve'){const exp=find();if(exp.status!=='draft')throw Error('초안 계획만 승인할 수 있습니다');if(!required.every(k=>text(exp.plan?.[k])))throw Error('실험계획 필수 항목을 확인하세요');if(user.uid!==exp.plan.reviewerUid&&user.role!=='admin')throw Error('지정 검토자만 승인할 수 있습니다');if(user.uid===exp.authorUid&&!text(command.selfReviewReason))throw Error('자기검토 이유가 필요합니다');exp.frozenPlan=copy(exp.plan);exp.status='approved';exp.approvedBy=user.uid;exp.selfReview=user.uid===exp.authorUid;exp.selfReviewReason=exp.selfReview?command.selfReviewReason.trim():null;exp.approvedAt=new Date().toISOString();}
 else if(command.type==='start'){const exp=find();if(exp.status!=='approved')throw Error('승인된 계획만 시작할 수 있습니다');exp.status='running';exp.startedAt=new Date().toISOString();}
 else if(command.type==='freezeDataset'){if(r.datasetSnapshots.some(d=>d.id===command.dataset?.id))throw Error('이미 동결한 데이터셋 ID입니다');r.datasetSnapshots.push(createDatasetSnapshot(p,command.dataset,user));}
 else if(command.type==='close'){const exp=find();if(exp.status!=='running')throw Error('진행 중 실험만 종료할 수 있습니다');if(command.datasetSnapshotId){const ds=r.datasetSnapshots.find(d=>d.id===command.datasetSnapshotId);if(!ds||ds.experimentId!==exp.id||ds.planRevision!==exp.planVersion||!verifyDatasetManifest(ds))throw Error('현재 계획의 유효한 동결 데이터셋을 선택하세요');command={...command,dataset:{version:ds.version,url:ds.versionRefs[0].url,sampleUnits:ds.sampleUnits,datasetSnapshotId:ds.id,manifestHash:ds.manifestHash}};}if(!['supported','not_supported','inconclusive','aborted'].includes(command.outcome)||!text(command.result)||!original(command.dataset))throw Error('실험 종료에는 결과·한계·고정 데이터 버전과 독립 표본 수가 필요합니다');exp.status='closed';exp.outcome=command.outcome;exp.result=command.result;exp.dataset=copy(command.dataset);exp.closedAt=new Date().toISOString();}
 else if(command.type==='metricResult'){if(r.metricResults.some(m=>m.id===command.metric?.id))throw Error('중복 수치 결과 ID');r.metricResults.push(createMetricResult(p,command.metric,user));}
 else if(command.type==='evidence'){const exp=r.experiments.find(e=>e.id===command.experimentId);if(!exp||exp.status!=='closed'||!text(command.id)||!text(command.claim)||!text(command.limitations)||!text(command.reviewerUid))throw Error('종료된 실험과 주장·한계·검토자가 필요합니다');if(r.evidence.some(e=>e.id===command.id))throw Error('중복 근거 ID');const ds=r.datasetSnapshots.find(d=>d.id===exp.dataset.datasetSnapshotId);const quality=evidenceQuality(command,!!ds&&verifyDatasetManifest(ds)&&ds.manifestHash===exp.dataset.manifestHash);const claimKind=command.claimKind??'observation';if(!['observation','improvement'].includes(claimKind))throw Error('주장 유형 오류');const metricResultIds=measuredMetrics(r,{...command,claimKind},exp);r.evidence.push({...quality,claimKind,metricResultIds,metricResultRefs:JSON.stringify(metricResultIds),id:command.id,experimentId:exp.id,claim:command.claim,limitations:command.limitations,source:copy(exp.dataset),outcome:exp.outcome,authorUid:user.uid,reviewerUid:command.reviewerUid,status:'review'});}
 else if(command.type==='referenceEvidence'){if(!['literature','simulation','assumption'].includes(command.evidenceType)||!text(command.id)||r.evidence.some(e=>e.id===command.id)||!text(command.claim)||!text(command.limitations)||!text(command.reviewerUid)||!text(command.version))throw Error('참고 근거 유형·고유 ID·주장·한계·검토자·버전이 필요합니다');let url;try{url=new URL(command.url);if(!['http:','https:'].includes(url.protocol))throw Error();}catch{throw Error('유효한 출처 URL이 필요합니다');}codeSource(url.href,command.version);r.evidence.push({...evidenceQuality(command),id:command.id,experimentId:'',claim:command.claim,limitations:command.limitations,source:{version:command.version,url:url.href,sampleUnits:0},outcome:'not_applicable',authorUid:user.uid,reviewerUid:command.reviewerUid,status:'review'});}
 else if(command.type==='approveEvidence'){const e=r.evidence.find(e=>e.id===command.id);if(!e||e.status!=='review'||user.uid!==e.reviewerUid&&user.role!=='admin')throw Error('지정 근거 검토자만 승인할 수 있습니다');if(e.authorUid===user.uid&&!text(command.selfReviewReason))throw Error('자기검토 이유가 필요합니다');e.status='approved';e.approvedBy=user.uid;e.selfReview=e.authorUid===user.uid;e.selfReviewReason=e.selfReview?command.selfReviewReason.trim():null;e.approvedAt=new Date().toISOString();}
 else if(command.type==='disclosure'){r.disclosureApprovals.push(recordDisclosure(p,command,user));}
 else if(command.type==='decision'){if(user.role!=='admin')throw Error('관리자만 사업 결정을 확정할 수 있습니다');if(!text(command.id)||r.decisions.some(d=>d.id===command.id)||!['continue','revise','stop','hold'].includes(command.action)||!text(command.reason)||!Array.isArray(command.evidenceIds)||!command.evidenceIds.length||!command.evidenceIds.every(id=>r.evidence.some(e=>e.id===id&&e.status==='approved')))throw Error('사업 결정에는 승인 근거·결정 이유·고유 ID가 필요합니다');r.decisions.push({id:command.id,action:command.action,reason:command.reason,evidenceIds:copy(command.evidenceIds),decidedBy:user.uid,at:new Date().toISOString()});}
 else throw Error('지원하지 않는 연구 작업');
 const previousCount=before.history.length;r.history.push({...command.type==='editDraft'?{reason:command.reason,beforePlan:before.experiments.find(e=>e.id===command.id).plan,afterPlan:copy(r.experiments.find(e=>e.id===command.id).plan)}:{},type:command.type,targetId:command.id??command.plan?.id??command.frameworkVersion??command.dataset?.id??command.metric?.id,actorUid:user.uid,at:new Date().toISOString(),sequence:previousCount+1});return p;
}
