import {createHash} from 'node:crypto';
import {canonical,createRestoredDatasetSnapshot} from './dataset.mjs';
import {validateProject} from './archive.mjs';
import {validateResearchLinks} from './import.mjs';
const key=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(x),hash=x=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x),digest=x=>createHash('sha256').update(x).digest('hex'),iso=x=>typeof x==='string'&&Number.isFinite(Date.parse(x))&&new Date(x).toISOString()===x;
const fields=['projectId','artifactId','versionId','providerFileId','sha256','sizeBytes'];
/** Main-private project derivation. Caller supplies validated ZIP/mapping and freshly company-Drive-verified refs. No authority or database write. */
export function deriveRestoredProject(source,input){
 const old=structuredClone(source),context=structuredClone(input),fail=()=>{throw Error('복원 프로젝트 원본·연구 연결 오류');},archivalProjectJSON=JSON.stringify(old);
 if(Buffer.byteLength(archivalProjectJSON)>8*1024*1024||!key(context.projectId)||context.projectId===old.id||!key(context.actorUid)||!iso(context.at)||!hash(context.sourceZipSHA256)||!hash(context.mappingSHA256)||!Array.isArray(context.verifiedRefs)||context.verifiedRefs.length>1000)fail();validateProject(old);validateResearchLinks(old);
 const originals=new Map();let nodes=0;
 function walk(value,visit,depth=0,all=false){if(++nodes>100000||depth>64)fail();if(!value||typeof value!=='object')return;if(all||Object.hasOwn(value,'providerFileId'))visit(value);for(const child of Object.values(value))walk(child,visit,depth+1,all);}
 walk(old,value=>{const ref=Object.fromEntries(fields.map(k=>[k,k==='projectId'?value[k]??old.id:value[k]]));if(ref.projectId!==old.id||!fields.slice(0,4).every(k=>key(ref[k]))||!hash(ref.sha256)||!Number.isSafeInteger(ref.sizeBytes)||ref.sizeBytes<1||ref.sizeBytes>100*1024*1024)fail();const prior=originals.get(ref.providerFileId);if(prior&&fields.some(k=>prior[k]!==ref[k]))fail();originals.set(ref.providerFileId,ref);if(originals.size>1000)fail();});
 if(context.verifiedRefs.length!==originals.size)fail();const replacements=new Map(),files=new Set(),versions=new Set(),artifacts=new Map(),artifactSources=new Map(),archivalArtifacts=new Set([...originals.values()].map(x=>x.artifactId)),archivalVersions=new Set([...originals.values()].map(x=>x.versionId));let total=0;
 for(const item of context.verifiedRefs){const original=originals.get(item?.sourceProviderFileId),ref=item?.reference;if(!original||replacements.has(original.providerFileId)||item.sourceProjectId!==old.id||item.sourceArtifactId!==original.artifactId||item.sourceVersionId!==original.versionId||!ref||ref.projectId!==context.projectId||!['artifactId','versionId','providerFileId'].every(k=>key(ref[k]))||ref.sha256!==original.sha256||ref.sizeBytes!==original.sizeBytes||!iso(ref.verifiedAt)||originals.has(ref.providerFileId)||archivalVersions.has(ref.versionId)||archivalArtifacts.has(ref.artifactId)||files.has(ref.providerFileId)||versions.has(ref.versionId)||(artifacts.has(original.artifactId)&&artifacts.get(original.artifactId)!==ref.artifactId)||(artifactSources.has(ref.artifactId)&&artifactSources.get(ref.artifactId)!==original.artifactId))fail();
  if(ref.mimeType!==undefined&&(typeof ref.mimeType!=='string'||ref.mimeType.length>127||! /^[a-zA-Z0-9!#$&^_.+-]+\/[a-zA-Z0-9!#$&^_.+-]+$/.test(ref.mimeType)))fail();total+=ref.sizeBytes;if(total>100*1024*1024)fail();files.add(ref.providerFileId);versions.add(ref.versionId);artifacts.set(original.artifactId,ref.artifactId);artifactSources.set(ref.artifactId,original.artifactId);replacements.set(original.providerFileId,{...item,reference:{...Object.fromEntries(fields.map(k=>[k,ref[k]])),verifiedAt:ref.verifiedAt,url:'https://drive.google.com/file/d/'+ref.providerFileId+'/view',...(ref.mimeType!==undefined?{mimeType:ref.mimeType}:{})}});
 }
 const p=structuredClone(old);p.id=context.projectId;p.revision=0;p.currentTRL=null;p.assessments=[];p.history=[];for(const item of p.items)if(item.status==='approved')item.status='review';if(p.projectId!==undefined){if(p.projectId!==old.id)fail();p.projectId=p.id;}
 if(p.research){p.research.disclosureApprovals=[];p.research.hypothesisAssessments=[];p.research.history=[];for(const kind of ['experiments','evidence','decisions','hypotheses','hypothesisAssessments','metricResults','followUpEvents','observations'])for(const row of p.research[kind]??[]){if(row.projectId!==undefined)row.projectId=p.id;if(kind==='evidence'&&row.status==='approved')row.status='review';if(kind==='evidence'||kind==='experiments'){for(const field of ['approvedBy','approvedAt','selfReview','selfReviewReason'])delete row[field];if(kind==='experiments'&&['approved','running'].includes(row.status))row.status='draft';}}}
 const itemIds=new Map(p.items.map(item=>[item.id,artifacts.get(item.id)??'restored_'+digest(JSON.stringify(['artifact',p.id,old.id,item.id]))]));if(new Set(itemIds.values()).size!==p.items.length)fail();for(const item of p.items)item.id=itemIds.get(item.id);
 nodes=0;walk(p,ref=>{if(Object.hasOwn(ref,'providerFileId')){const item=replacements.get(ref.providerFileId);if(!item)fail();if(Object.hasOwn(ref,'version'))ref.version=item.reference.versionId;for(const field of ['projectId','artifactId','versionId','providerFileId','sha256','sizeBytes','verifiedAt','url','mimeType'])delete ref[field];Object.assign(ref,item.reference);}else if(artifacts.has(ref.artifactId)||itemIds.has(ref.artifactId))ref.artifactId=artifacts.get(ref.artifactId)??itemIds.get(ref.artifactId);if(itemIds.has(ref.itemId))ref.itemId=itemIds.get(ref.itemId);},0,true);
 if(p.research){const datasets=new Map();p.research.datasetSnapshots=(old.research.datasetSnapshots??[]).map(ds=>{const exp=old.research.experiments?.find(x=>x.id===ds.experimentId);if(!exp?.frozenPlan||ds.planHash!==digest(JSON.stringify(canonical(exp.frozenPlan))))fail();const derived=createRestoredDatasetSnapshot(ds,{...context,verifiedRefs:ds.versionRefs.map(ref=>replacements.get(ref.providerFileId))});const liveExp=p.research.experiments.find(x=>x.id===ds.experimentId),livePlanHash=digest(JSON.stringify(canonical(liveExp.frozenPlan)));if(livePlanHash!==ds.planHash){derived.planHash=livePlanHash;derived.restoredFrom.planHash=ds.planHash;const {manifestHash,...body}=derived;derived.manifestHash=digest(JSON.stringify(canonical(body)));}datasets.set(ds.id,derived);return derived;});
  const bind=record=>{if(!record?.datasetSnapshotId)return;const ds=datasets.get(record.datasetSnapshotId);if(!ds)fail();record.manifestHash=ds.manifestHash;record.url=ds.versionRefs[0].url;};
  for(const exp of p.research.experiments??[])bind(exp.dataset);for(const evidence of p.research.evidence??[])bind(evidence.source);for(const metric of p.research.metricResults??[])for(const prefix of ['baseline','result']){const ds=datasets.get(metric[prefix+'SnapshotId']);if(!ds)fail();metric[prefix+'ManifestHash']=ds.manifestHash;}
 }
 p.restoredFrom={kind:'BRING_RND_PROJECT_RESTORATION_PROVENANCE',version:1,projectId:old.id,sourceZipSHA256:context.sourceZipSHA256,mappingSHA256:context.mappingSHA256,archivalProjectSHA256:digest(archivalProjectJSON),archivalProjectJSON,derivedBy:context.actorUid,derivedAt:context.at,originVerified:false,disclosureApprovalTransferred:false,projectApprovalTransferred:false};
 validateProject(p);validateResearchLinks(p);if(Buffer.byteLength(JSON.stringify(p))>20*1024*1024)fail();return{kind:'BRING_RND_DERIVED_RESTORE_PROJECT',version:1,project:p,sourceZipSHA256:context.sourceZipSHA256,mappingSHA256:context.mappingSHA256,databaseWrites:false,cloudWrites:false,restoreReady:false,originVerified:false};
}
