import {createHash} from 'node:crypto';
import {validateVisit,validateVisitLinks} from './baseline.mjs';
const key=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(x),hash=x=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x),digest=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),iso=x=>typeof x==='string'&&Number.isFinite(Date.parse(x))&&new Date(x).toISOString()===x;
/** Main-private baseline derivation from trusted current mapping and freshly verified refs. No authority or write. */
export function deriveRestoredVisits(source,inputMapping,inputContext){
 const rows=structuredClone(source),mapping=structuredClone(inputMapping),context=structuredClone(inputContext),fail=()=>{throw Error('복원 기준선 원본·대상 연결 오류');};
 if(!Array.isArray(rows)||rows.length>10000||Buffer.byteLength(JSON.stringify(rows))>8*1024*1024||mapping?.kind!=='BRING_RND_ORIGINAL_RESTORE_MAPPING'||mapping.version!==1||mapping.canApply!==false||mapping.cloudWrites!==false||mapping.restoreReady!==false||!key(mapping.previewId)||!hash(mapping.sourceZipSHA256)||!hash(mapping.currentSnapshotSHA256)||!key(context.actorUid)||!iso(context.at)||!Array.isArray(context.verifiedRefs)||context.verifiedRefs.length>1000)fail();const{mappingSHA256,...body}=mapping;if(!hash(mappingSHA256)||digest(body)!==mappingSHA256||!Array.isArray(mapping.projects)||!Array.isArray(mapping.visits)||mapping.visits.length!==rows.length)fail();
 const projects=new Map(),projectTargets=new Set();for(const p of mapping.projects){if(!key(p.sourceId)||!key(p.targetId)||projects.has(p.sourceId)||projectTargets.has(p.targetId)||p.sourceProjectId!==p.sourceId||p.targetProjectId!==p.targetId||!hash(p.sourceSHA256))fail();projects.set(p.sourceId,p.targetId);projectTargets.add(p.targetId);}
 const plans=new Map(),targets=new Set();for(const plan of mapping.visits){if(!key(plan.sourceId)||!key(plan.targetId)||plans.has(plan.sourceId)||targets.has(plan.targetId)||!hash(plan.sourceSHA256))fail();plans.set(plan.sourceId,plan);targets.add(plan.targetId);}const ids=new Set();for(const row of rows){if(!key(row?.id)||ids.has(row.id)||!Number.isSafeInteger(row.revision??0)||(row.revision??0)<0)fail();ids.add(row.id);validateVisit(row);const plan=plans.get(row.id),parent=row.projectId??null;if(!plan||plan.sourceSHA256!==digest(row)||plan.sourceProjectId!==parent||plan.targetProjectId!==(parent===null?null:projects.get(parent))||(parent!==null&&!projects.has(parent)))fail();}validateVisitLinks(rows);
 const archivalFiles=new Set(context.verifiedRefs.map(x=>x.sourceProviderFileId)),archivalArtifacts=new Set(context.verifiedRefs.map(x=>x.sourceArtifactId)),archivalVersions=new Set(context.verifiedRefs.map(x=>x.sourceVersionId)),replacements=new Map(),files=new Set(),versions=new Set();for(const item of context.verifiedRefs){const ref=item?.reference;if(!item||!key(item.sourceProviderFileId)||!key(item.sourceProjectId)||!projects.has(item.sourceProjectId)||!key(item.sourceArtifactId)||!key(item.sourceVersionId)||replacements.has(item.sourceProviderFileId)||!ref||!key(ref.projectId)||ref.projectId!==projects.get(item.sourceProjectId)||!['providerFileId','artifactId','versionId'].every(k=>key(ref[k]))||!hash(ref.sha256)||!Number.isSafeInteger(ref.sizeBytes)||ref.sizeBytes<1||ref.sizeBytes>100*1024*1024||!iso(ref.verifiedAt)||archivalFiles.has(ref.providerFileId)||archivalArtifacts.has(ref.artifactId)||archivalVersions.has(ref.versionId)||files.has(ref.providerFileId)||versions.has(ref.versionId))fail();files.add(ref.providerFileId);versions.add(ref.versionId);replacements.set(item.sourceProviderFileId,item);}
 let nodes=0,unverifiedEvidenceLinkCount=0;const usedFiles=new Set();let total=0;
 const visits=rows.map(row=>{const archivalVisitJSON=JSON.stringify(row),plan=plans.get(row.id),v=validateVisit(row);v.id=plan.targetId;v.projectId=plan.targetProjectId;v.revision=0;v.restorationSourceRevision=row.restorationSourceRevision??row.revision??0;if(v.revisit){const parent=plans.get(row.originalVisitId);if(!parent)fail();v.originalVisitId=parent.targetId;}const urls=new Map();
  function walk(value,depth=0){if(++nodes>100000||depth>64)fail();if(!value||typeof value!=='object')return;if(Object.hasOwn(value,'providerFileId')){const item=replacements.get(value.providerFileId),ref=item?.reference,oldProject=value===v?row.projectId:value.projectId??row.projectId;if(!item||item.sourceProjectId!==oldProject||(row.projectId!=null&&oldProject!==row.projectId)||item.sourceArtifactId!==value.artifactId||item.sourceVersionId!==value.versionId||ref.sha256!==value.sha256||ref.sizeBytes!==value.sizeBytes)fail();if(!usedFiles.has(item.sourceProviderFileId)){usedFiles.add(item.sourceProviderFileId);total+=ref.sizeBytes;if(total>100*1024*1024)fail();}const url='https://drive.google.com/file/d/'+ref.providerFileId+'/view';urls.set('https://drive.google.com/file/d/'+item.sourceProviderFileId+'/view',url);if(typeof value.url==='string')urls.set(value.url,url);if(Object.hasOwn(value,'version'))value.version=ref.versionId;for(const k of ['projectId','artifactId','versionId','providerFileId','sha256','sizeBytes','verifiedAt','url','mimeType'])delete value[k];Object.assign(value,Object.fromEntries(['projectId','artifactId','versionId','providerFileId','sha256','sizeBytes','verifiedAt'].map(k=>[k,ref[k]])),{url});}for(const child of Object.values(value))walk(child,depth+1);}
  walk(v);if(urls.has(v.evidenceUrl))v.evidenceUrl=urls.get(v.evidenceUrl);else unverifiedEvidenceLinkCount++;v.restoredFrom={kind:'BRING_RND_VISIT_RESTORATION_PROVENANCE',version:1,sourceId:row.id,sourceProjectId:row.projectId??null,sourceSHA256:digest(row),sourceZipSHA256:mapping.sourceZipSHA256,mappingSHA256,archivalVisitJSON,derivedBy:context.actorUid,derivedAt:context.at,originVerified:false};return validateVisit(v);
 });validateVisitLinks(visits);if(Buffer.byteLength(JSON.stringify(visits))>20*1024*1024)fail();return{kind:'BRING_RND_DERIVED_RESTORE_VISITS',version:1,visits,sourceZipSHA256:mapping.sourceZipSHA256,mappingSHA256,unverifiedEvidenceLinkCount,databaseWrites:false,cloudWrites:false,restoreReady:false,originVerified:false};
}
