const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const validId=value=>typeof value==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(value);
function normalize(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('업로드 복구 기록 형식 오류');if(input.status!==undefined&&!['VERIFIED','UPLOADED_UNVERIFIED'].includes(input.status))throw Error('업로드 복구 상태 오류');const record={projectId:input.projectId,artifactId:input.artifactId,versionId:input.versionId,providerFileId:input.providerFileId??input.id,sha256:input.sha256??input.hash,sizeBytes:Number(input.sizeBytes??input.size),status:input.status==='UPLOADED_UNVERIFIED'?'UPLOADED_UNVERIFIED':'VERIFIED'};
 if(![record.projectId,record.artifactId,record.versionId,record.providerFileId].every(validId)||!/^([a-f0-9]{64})$/.test(record.sha256??'')||!Number.isInteger(record.sizeBytes)||record.sizeBytes<1||record.sizeBytes>100*1024*1024||typeof (record.status==='VERIFIED'?input.verifiedAt:input.observedAt)!=='string'||!Number.isFinite(Date.parse(record.status==='VERIFIED'?input.verifiedAt:input.observedAt)))throw Error('업로드 복구 기록 형식 오류');
 if(record.status==='VERIFIED')record.verifiedAt=input.verifiedAt;else record.observedAt=input.observedAt;record.url='https://drive.google.com/file/d/'+record.providerFileId+'/view';return record;}
function createUploadLedger(directory){const root=path.resolve(directory);let tail=Promise.resolve();const serial=work=>{const result=tail.then(work);tail=result.catch(()=>{});return result;};
 const target=uid=>{if(!validId(uid))throw Error('복구 UID 형식 오류');return path.join(root,uid+'.json');};
 async function read(uid){try{const file=target(uid);if((await fs.stat(file)).size>2*1024*1024)throw Error('업로드 복구 원장 용량 한도');const raw=JSON.parse(await fs.readFile(file,'utf8'));if(raw.kind!=='BRING_RND_UPLOAD_LEDGER'||raw.uid!==uid||!Array.isArray(raw.records)||raw.records.length>1000)throw Error('업로드 복구 원장 오류');const records=raw.records.map(normalize);const keys=records.map(r=>r.projectId+':'+r.artifactId+':'+r.versionId);if(new Set(keys).size!==keys.length)throw Error('업로드 복구 원장 중복 버전 오류');return records;}catch(error){if(error.code==='ENOENT')return [];throw error;}}
 return{list:uid=>serial(()=>read(uid)),record:(uid,input)=>serial(async()=>{const file=target(uid),record=normalize(input),records=await read(uid);const old=records.find(r=>r.projectId===record.projectId&&r.artifactId===record.artifactId&&r.versionId===record.versionId);
 if(old){if(old.providerFileId!==record.providerFileId||old.sha256!==record.sha256||old.sizeBytes!==record.sizeBytes)throw Error('같은 자료 버전의 복구 기록 충돌');if(old.status==='VERIFIED'||record.status!=='VERIFIED')return old;records.splice(records.indexOf(old),1);}
 if(records.length>=1000)throw Error('업로드 복구 기록 한도 · 원장을 검토하세요');records.push(record);await fs.mkdir(root,{recursive:true});const temporary=file+'.'+crypto.randomUUID()+'.partial';try{await fs.writeFile(temporary,JSON.stringify({kind:'BRING_RND_UPLOAD_LEDGER',uid,records}),{flag:'wx',mode:0o600});await fs.rename(temporary,file);}finally{await fs.unlink(temporary).catch(error=>{if(error.code!=='ENOENT')throw error;});}return record;
 })};}
module.exports={createUploadLedger};
