import {categories,colors,validate,connected} from '../upstream/model.mjs';
import {createDOMScope,createMutationGate} from './dom-scope.mjs';
import {template} from './template.mjs';
import {setupEnhancements} from './enhancements.mjs';
import {attachCatalog} from './equipment-catalog.mjs';
export async function mountBuildingAtlas({host,initialPortfolio,savePortfolio,canWrite=false,mode='practice',confirm:ask=async()=>false,download:sendDownload,createViewer:viewerFactory,signal}={}) {
 if(!host?.attachShadow)throw Error('설비지도 호스트가 필요합니다.');
 const gate=createMutationGate({initialPortfolio,savePortfolio,canWrite,mode});
 const root=host.shadowRoot||host.attachShadow({mode:'open'});
 root.innerHTML=template;
 const document=createDOMScope(root,host.ownerDocument),$=id=>document.getElementById(id);
 const style=document.createElement('link');style.rel='stylesheet';style.href=new URL('./theme.css',import.meta.url).href;root.prepend(style);
 const timers=new Set(),urls=new Set();
 const setTimeout=(fn,ms)=>{const id=globalThis.setTimeout(()=>{timers.delete(id);if(!document.signal.aborted)fn();},ms);timers.add(id);return id;};
 const clearTimeout=id=>{globalThis.clearTimeout(id);timers.delete(id);};
 const download=(content,type,name)=>{document.assertActive();if(sendDownload)return sendDownload(content,type,name);const url=URL.createObjectURL(new Blob([content],{type}));urls.add(url);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>{URL.revokeObjectURL(url);urls.delete(url);},1000);};
 function dispose(){if(document.signal.aborted)return;gate.dispose();document.dispose();viewer?.dispose?.();for(const id of timers)globalThis.clearTimeout(id);timers.clear();for(const url of urls)URL.revokeObjectURL(url);urls.clear();signal?.removeEventListener('abort',dispose);root.replaceChildren();}
 signal?.addEventListener('abort',dispose,{once:true});
 const assertWritable=()=>{document.assertActive();if(!canWrite)throw Error('읽기 전용입니다.');};
 const confirm=async text=>{document.assertActive();const ok=await ask(text);document.assertActive();return ok;};

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}};
let portfolio=gate.getPortfolio(),data=portfolio.items.find(i=>i.id===portfolio.activeId).data,category='all',selected=data.records[0]?.id,viewer,editing=null,editingBuilding;
 if(signal?.aborted){dispose();return {dispose};}
let state={floor:'all',transparent:true,explode:false,layers:new Set(categories.map(c=>c.id)),selected};
$('storage').textContent=mode==='practice'?'연습 모드 · 메모리에서만 작업 · 회사 자료에 저장하지 않음':canWrite?'선택한 CRM 건물 · 회사 저장':'선택한 CRM 건물 · 읽기 전용';
function toast(text){if(document.signal.aborted)return;$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4000);}
async function persist(next,expectedId=portfolio.activeId){validate(next);const p=structuredClone(portfolio);const item=p.items.find(i=>i.id===expectedId);if(!item)throw Error('건물이 변경되었습니다.');item.data=next;portfolio=await gate.commit(p,expectedId);data=portfolio.items.find(i=>i.id===portfolio.activeId).data;render();toast(mode==='practice'?'연습 자료를 반영했습니다.':'회사 자료를 저장했습니다.');}
function choose(id){selected=id;state.selected=id;render();}
function render(){if(document.signal.aborted)return;
 $('title').textContent=data.building.name;$('address').textContent=data.building.address;$('stats').textContent=`지하 1층 + 지상 ${data.building.floors}층 · 등록 ${data.records.length}건 · 현장 확인 ${data.records.filter(r=>r.confidence==='현장 확인').length}건`;
 $('floor').innerHTML='<option value="all">전체 층</option>'+Array.from({length:data.building.floors+1},(_,f)=>`<option value="${f}">${f===0?'지하 1층':f+'층'}</option>`).join('');$('floor').value=state.floor;
 $('categories').innerHTML=[{id:'all',name:'전체 기록'},...categories].map(c=>`<button data-category="${c.id}" class="${category===c.id?'active':''}">${c.name}<span>${data.records.filter(r=>c.id==='all'||r.category===c.id).length}</span></button>`).join('');
 $('layers').innerHTML=categories.filter(c=>['building','water','electric','fire','hvac','sensor'].includes(c.id)).map(c=>`<label><input type="checkbox" data-layer="${c.id}" ${state.layers.has(c.id)?'checked':''}><span style="color:#${colors[c.id].toString(16).padStart(6,'0')}"> ● </span>${c.name}</label>`).join('');
 const q=$('search').value.toLowerCase(),rows=data.records.filter(r=>(category==='all'||r.category===category)&&(state.floor==='all'||r.floor===Number(state.floor))&&JSON.stringify(r).toLowerCase().includes(q));
 $('listTitle').textContent=categories.find(c=>c.id===category)?.name||'전체 기록';$('count').textContent=rows.length+'건';
 $('records').innerHTML=rows.length?rows.map(r=>`<button class="record ${r.id===selected?'selected':''}" data-record="${esc(r.id)}"><strong>${esc(r.name)}</strong><small>${r.floor===0?'B1':r.floor+'F'} · ${esc(r.status)} · ${esc(r.confidence)}</small></button>`).join(''):'<p class="muted">등록된 기록이 없습니다. ‘＋ 기록 등록’에서 추가하세요.</p>';
 renderDetail();viewer?.update(data,state);document.emit('atlas-render');applyPermissions();
}
function renderDetail(){const r=data.records.find(r=>r.id===selected);if(!r){$('detail').innerHTML='<h2>설비와 기록을 선택하세요</h2><p class="muted">3D 설비 또는 아래 목록에서 항목을 선택하면 연결 정보와 상세 기록을 확인할 수 있습니다.</p>';return;}
 const field=(k,v)=>`<dt>${esc(k)}</dt><dd>${esc(v||'등록 필요')}</dd>`;
 const photo=safeURL(r.photo),doc=safeURL(r.document);
 $('detail').innerHTML=`<span class="eyebrow">${esc(categories.find(c=>c.id===r.category).name)}</span><h2>${esc(r.name)}</h2><span class="badge">${esc(r.status)}</span><span class="badge">${esc(r.confidence)}</span><div class="buttons"><button id="editRecord" class="primary">정보 수정</button><button id="deleteRecord" class="danger">삭제</button></div>${photo?`<a href="${esc(photo)}" target="_blank" rel="noopener noreferrer">현장 사진 열기 ↗</a>`:''}<dl>${field('위치',`${r.floor===0?'지하 1':r.floor}층 · X ${r.x}m / Z ${r.z}m`)}${Object.entries(r.fields).map(([k,v])=>field(k,v)).join('')}${field('설명·작업 이력',r.notes)}${field('확인 근거',r.source)}${field('확인일',r.verifiedAt)}</dl>${doc?`<a href="${esc(doc)}" target="_blank" rel="noopener noreferrer">문서·도면 열기 ↗</a>`:''}<h2>연결된 설비·기록</h2><p class="muted">등록된 연결 관계입니다. 물리적 흐름·차단 가능 여부는 별도로 현장 확인해야 합니다.</p>${connected(data,r.id).filter(id=>id!==r.id).map(id=>{const x=data.records.find(v=>v.id===id);return `<button class="connection" data-record="${esc(id)}">${esc(x.name)} →</button>`;}).join('')||'<p class="muted">연결 없음</p>'}`;
 $('editRecord').onclick=()=>openRecord(r);$('deleteRecord').onclick=async ()=>{const expectedId=portfolio.activeId;try{if(!await confirm('이 기록을 삭제할까요? 연결도 함께 해제됩니다.'))return;const next=structuredClone(data);next.records=next.records.filter(v=>v.id!==r.id).map(v=>({...v,links:v.links.filter(id=>id!==r.id),...(v.routes?{routes:v.routes.filter(route=>route.targetId!==r.id)}:{})}));await persist(next,expectedId);}catch(e){toast(e.message);}};
}
const input=(name,label,value='',type='text',wide=false)=>`<label class="${wide?'wide':''}">${esc(label)}<input name="${esc(name)}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(value)}"></label>`;
const area=(name,label,value='')=>`<label class="wide">${esc(label)}<textarea name="${name}" rows="3">${esc(value)}</textarea></label>`;
function openRecord(record){assertWritable();editingBuilding=portfolio.activeId;editing=record?.id||'new';const r=record||{name:'',category:category==='all'?'water':category,floor:state.floor==='all'?0:Number(state.floor),x:0,z:0,status:'확인 필요',confidence:'추정',fields:{},links:[]};$('editorTitle').textContent=record?'기록 수정':'새 기록 등록';
 $('formFields').innerHTML=input('name','설비·기록 이름',r.name)+`<label>데이터 영역<select name="category">${categories.map(c=>`<option value="${c.id}" ${c.id===r.category?'selected':''}>${c.name}</option>`).join('')}</select></label>`+input('floor','층 (0 = 지하 1층)',r.floor,'number')+input('x','가로 위치 X (m)',r.x,'number')+input('z','세로 위치 Z (m)',r.z,'number')+`<label>상태<select name="status">${['정상','확인 필요','점검 필요','견적 대기','작업 중','긴급','완료'].map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></label><label>정보 확인 수준<select name="confidence">${['예시','추정','도면 확인','현장 확인'].map(s=>`<option ${s===r.confidence?'selected':''}>${s}</option>`).join('')}</select></label>`+input('verifiedAt','확인일',r.verifiedAt,'date')+input('source','확인 근거 (도면명·사진·담당자)',r.source,'text',true)+input('photo','현장 사진 URL',r.photo,'url',true)+input('document','문서·도면 URL',r.document,'url',true)+`<label class="wide">연결 설비·관련 기록 (Ctrl로 여러 항목 선택)<select name="links" multiple size="4">${data.records.filter(v=>v.id!==r.id).map(v=>`<option value="${esc(v.id)}" ${r.links.includes(v.id)?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><div class="wide muted" id="fieldGuide"></div>`+area('fields','상세 항목 (한 줄에 항목: 값)',Object.entries(r.fields).map(([k,v])=>`${k}: ${v}`).join('\n'))+area('notes','설명·작업 이력·추가 메모',r.notes);
 if(record){const hint=document.createElement('p');hint.className='wide muted';hint.textContent='층·좌표를 변경하면 확인 수준은 추정으로 바뀌고 확인일과 관련 경로의 확인 표시가 해제됩니다. 저장 후 현장에서 다시 확인해주세요.';$('formFields').prepend(hint);}
const guide=()=>{const c=categories.find(c=>c.id===$('form').elements.category.value);$('fieldGuide').textContent='권장 입력: '+c.fields.join(' · ');if(!$('form').elements.fields.value)$('form').elements.fields.value=c.fields.map(k=>k+': ').join('\n');};$('form').elements.category.onchange=guide;guide();attachCatalog($('form'),record,guide,document);$('formError').textContent='';$('editor').showModal();
}
function openBuilding(){assertWritable();editingBuilding=portfolio.activeId;editing='building';$('editorTitle').textContent='건물 설정';const b=data.building;$('formFields').innerHTML=input('name','건물명',b.name)+input('address','주소',b.address)+input('floors','지상 층수 (1~30)',b.floors,'number')+input('width','가로 (m)',b.width,'number')+input('depth','세로 (m)',b.depth,'number')+'<p class="wide muted">현재 모델은 지하 1개 층을 포함합니다. 실제 도면이 없으면 대략적인 치수를 입력하세요. 기존 설비가 새 크기를 벗어나면 위치를 먼저 수정해야 합니다.</p>';$('formError').textContent='';$('editor').showModal();}
$('form').onsubmit=async e=>{e.preventDefault();try{assertWritable();if(editingBuilding!==portfolio.activeId)throw Error('건물이 변경되었습니다.');let nextSelected=selected;const f=new FormData(e.target),next=structuredClone(data);if(editing==='building'){next.building={...next.building,name:f.get('name').trim(),address:f.get('address'),floors:Number(f.get('floors')),width:Number(f.get('width')),depth:Number(f.get('depth'))};}else{const fields={};for(const line of f.get('fields').split('\n')){const i=line.indexOf(':');if(i>0){const k=line.slice(0,i).trim();if(!['__proto__','constructor','prototype'].includes(k))fields[k]=line.slice(i+1).trim();}}const r={...next.records.find(v=>v.id===editing),id:editing==='new'?crypto.randomUUID():editing,name:f.get('name').trim(),category:f.get('category'),shape:f.get('shape')||'',floor:Number(f.get('floor')),x:Number(f.get('x')),z:Number(f.get('z')),status:f.get('status'),confidence:f.get('confidence'),verifiedAt:f.get('verifiedAt'),source:f.get('source'),photo:f.get('photo'),document:f.get('document'),links:f.getAll('links'),notes:f.get('notes'),fields,updatedAt:new Date().toISOString()};if(r.routes)r.routes=r.routes.filter(route=>r.links.includes(route.targetId));const i=next.records.findIndex(v=>v.id===r.id);if(i<0)next.records.push(r);else {const previous=next.records[i];next.records[i]=r;if(['floor','x','z'].some(k=>previous[k]!==r[k])){r.confidence='추정';r.verifiedAt='';const notice='위치 변경 · 현장 재확인 필요';r.source=[r.source,notice].filter(Boolean).join(' / ');for(const record of next.records)for(const route of record.routes||[])if(record.id===r.id||route.targetId===r.id)route.confirmed=false;}}nextSelected=r.id;}await persist(next,editingBuilding);choose(nextSelected);$('editor').close();}catch(e){document.reportError('formError',e);}};
 document.addEventListener('click',e=>{const item=e.target.closest('[data-record]');if(item)choose(item.dataset.record);const cat=e.target.closest('[data-category]');if(cat){category=cat.dataset.category;render();}});
 $('layers').onchange=e=>{const id=e.target.dataset.layer;if(id){e.target.checked?state.layers.add(id):state.layers.delete(id);viewer?.update(data,state);}};
 $('search').oninput=render;$('floor').onchange=e=>{state.floor=e.target.value;render();viewer?.reset();};$('shell').onchange=e=>{state.transparent=e.target.checked;viewer?.update(data,state);};$('explode').onchange=e=>{state.explode=e.target.checked;viewer?.update(data,state);viewer?.reset();};$('reset').onclick=()=>{state.floor='all';render();viewer?.reset();};$('add').onclick=()=>openRecord();$('buildingEdit').onclick=openBuilding;$('close').onclick=()=>$('editor').close();
 $('export').onclick=()=>download(JSON.stringify(data,null,2),'application/json','building-atlas-'+new Date().toISOString().slice(0,10)+'.json');
 $('import').onclick=()=>$('file').click();$('file').onchange=async e=>{try{if(mode==='company')throw Error('회사 자료 가져오기는 CRM의 검토·확인 절차를 이용해주세요.');const file=e.target.files[0];if(!file)return;if(file.size>8e6)throw Error('8MB 이하 JSON 파일을 선택해주세요.');const expectedId=portfolio.activeId,text=await file.text();document.assertActive();const next=validate(JSON.parse(text));if(!await confirm('현재 건물 데이터를 가져온 파일로 교체할까요? 필요한 경우 먼저 백업하세요.'))return;await persist(next,expectedId);state.floor='all';render();viewer?.reset();}catch(e){toast(e.message);}finally{e.target.value='';}};
 async function setPortfolio(p,expectedId=portfolio.activeId){portfolio=await gate.commit(p,expectedId);applyPortfolio();}
 function applyPortfolio(){data=portfolio.items.find(i=>i.id===portfolio.activeId).data;selected=data.records[0]?.id;state.selected=selected;state.floor='all';category='all';$('search').value='';render();viewer?.reset();}
 function selectBuilding(id){gate.select(id);portfolio=gate.getPortfolio();applyPortfolio();}
 const writeSelectors='#buildingEdit,#import,#add,#editRecord,#deleteRecord,#newBuilding,#attachPhoto,#routeEdit,#addHistory,#scheduleInspection,#duplicateAsset,#planSave,#mergePortfolio,#fmImportConfirm,[data-maintenance-schedule],#tourRecord,#planImage,#planRemoveImage,#planUndo,#planClearRoute,#planConfirmed,#planApplyCoordinate,#planCanvas,#planX,#planZ,#portfolioFile,#fmBasicsFile,[data-sample]';
 function applyPermissions(){for(const button of root.querySelectorAll(writeSelectors))if(!canWrite)button.disabled=true;if(mode==='company'){for(const id of ['newBuilding','import'])$(id).hidden=true;$('file').disabled=true;}}
 document.addEventListener('cancel',e=>{if(gate.isBusy())e.preventDefault();},{capture:true});
 document.addEventListener('click',e=>{if(gate.isBusy()&&(e.target.closest('dialog')||e.target.closest(writeSelectors))){e.preventDefault();e.stopImmediatePropagation();toast('저장이 진행 중입니다.');return;}if(!canWrite&&e.target.closest(writeSelectors)){e.preventDefault();e.stopImmediatePropagation();toast('읽기 전용입니다.');}},{capture:true});
 const filters=root.querySelector('.filter-drawer');filters.open=(host.clientWidth||390)>800;
 setupEnhancements({dom:document,mode,canWrite,assertWritable,download,getData:()=>data,getSelected:()=>selected,getViewer:()=>viewer,getState:()=>state,getPortfolio:()=>portfolio,save:persist,toast,choose,render,setPortfolio,selectBuilding});
 render();try{const createViewer=viewerFactory||(await import('./viewer.mjs')).createViewer;document.assertActive();const candidate=await createViewer($('viewport'),choose);if(document.signal.aborted){candidate?.dispose?.();return {dispose};}viewer=candidate;viewer.update(data,state);viewer.reset();}catch(e){viewer?.dispose?.();viewer=undefined;if(!document.signal.aborted)$('fallback').hidden=false;}

 return {dispose};
}
