const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const file=path.join(__dirname,'../src/operations-check-ui.js');const UI=fs.existsSync(file)?require(file):{};
const model={metrics:{registeredBuildings:3,managedBuildings:1,cleaningOnlyBuildings:1,evidenceTasks:1,heldContracts:0},buildings:[{id:'b1',name:'A'}],issues:[{key:'s1:e',id:'s1',source:'serviceRecords',buildingId:'b1',buildingName:'A',title:'작업 A',owner:'직원 A',category:'evidence',reason:'증빙 연결 확인 필요'}]};
function render(m=model,o={}){assert.equal(typeof UI.renderOperationsCheck,'function');return UI.renderOperationsCheck(m,{sync:{status:'connected',receivedAt:'2026-09-13T00:00:00Z',hasSnapshot:true},...o});}
test('missing customer source reports partial even when metric sources are available',()=>{assert.match(render({...model,sourceState:{customers:false,buildings:true}}),/일부 데이터만 확인됨/);});
test('fresh receipt while editing explains deferred original detail refresh',()=>{assert.match(render(model,{sync:{status:'connected',hasSnapshot:true,displayPending:true}}),/최신 자료 수신됨 · 편집 종료 후 상세 화면에 반영/);});
test('renders integrated cards, criteria and original detail target',()=>{const html=render();assert.match(html,/정기관리 건물/);assert.match(html,/집계 기준/);assert.match(html,/data-operations-detail="s1"/);assert.match(html,/data-operations-source="serviceRecords"/);assert.match(html,/마지막 서버 수신/);});
test('loading and errors do not render cached numbers as current',()=>{const html=render(model,{sync:{status:'offline',hasSnapshot:false}});assert.match(html,/서버에서 확인하지 못했습니다/);assert.doesNotMatch(html,/>3<\/strong>/);const old=render(model,{sync:{status:'offline',hasSnapshot:true}});assert.match(old,/최신 확인 실패/);assert.match(old,/>3<\/strong>/);});
test('partial source remains unavailable and filtered empty differs from error',()=>{assert.match(render({...model,metrics:{...model.metrics,managedBuildings:null}}),/일부 데이터만 확인됨/);assert.match(render(model,{owner:'없는 직원'}),/조건에 맞는 확인 항목이 없습니다/);});
test('all untrusted content is escaped and input is unchanged',()=>{const data=structuredClone(model);data.issues[0].title='<img src=x onerror=alert(1)>';data.issues[0].id='" onclick="alert(1)';const before=JSON.stringify(data);const html=render(data);assert.doesNotMatch(html,/<img/);assert.match(html,/&lt;img/);assert.equal(JSON.stringify(data),before);});
