const test=require('node:test'),assert=require('node:assert/strict');
const preview={kind:'BRING_RND_ORIGINAL_RESTORE_PREVIEW',version:1,previewId:'preview',sourceZipSHA256:'a'.repeat(64),currentSnapshotSHA256:'b'.repeat(64),canApply:false,projects:[{id:'p',projectId:'p',sourceSHA256:'c'.repeat(64)}],visits:[{id:'v',projectId:'p',sourceSHA256:'d'.repeat(64)}],importJobs:[],originalPlan:[{providerFileId:'f',projectId:'p',artifactId:'a',versionId:'version',sha256:'e'.repeat(64),sizeBytes:3}]};
test('original restore mapping binds new target IDs and file upload targets to source hashes',()=>{
 const {createOriginalRestoreMapping}=require('../src/rnd-control/original-restore-mapping');const result=createOriginalRestoreMapping(preview,{projects:['p'],visits:['v'],importJobs:[]},{projects:{p:'newp'},visits:{v:'newv'},importJobs:{}});assert.equal(result.visits[0].targetProjectId,'newp');assert.equal(result.originals[0].targetProjectId,'newp');assert.equal(result.projects[0].sourceSHA256,preview.projects[0].sourceSHA256);assert.equal(result.canApply,false);assert.equal(result.cloudWrites,false);assert.match(result.mappingSHA256,/^[a-f0-9]{64}$/);
});
test('original restore mapping denies current collisions, omitted/extra IDs and missing parent mappings',()=>{
 const {createOriginalRestoreMapping}=require('../src/rnd-control/original-restore-mapping');const current={projects:['p'],visits:['v'],importJobs:[]};for(const request of [{projects:{p:'p'},visits:{v:'newv'},importJobs:{}},{projects:{p:'newp'},visits:{},importJobs:{}},{projects:{p:'newp',extra:'x'},visits:{v:'newv'},importJobs:{}}])assert.throws(()=>createOriginalRestoreMapping(preview,current,request));assert.throws(()=>createOriginalRestoreMapping({...preview,visits:[{...preview.visits[0],projectId:'missing'}]},current,{projects:{p:'newp'},visits:{v:'newv'},importJobs:{}}));
});

test('mapping accepts an actual verified original ZIP preview and isolates target collisions',async()=>{
 const {createProject}=await import('../src/rnd-control/portfolio.mjs'),{buildOriginalBackup}=require('../src/rnd-control/original-backup'),{createOriginalRestorePreview}=require('../src/rnd-control/original-restore-preview'),{createOriginalRestoreMapping}=require('../src/rnd-control/original-restore-mapping');const p=createProject('p','Source'),bytes=Buffer.from([255,0,128]),ref={projectId:'p',artifactId:'a',versionId:'v',providerFileId:'f',sizeBytes:3,sha256:require('node:crypto').createHash('sha256').update(bytes).digest('hex')};p.items[0].evidence=[ref];const zip=await buildOriginalBackup({projects:[p],visits:[],importJobs:[],selectedId:'p'},{check:async()=>{},download:async received=>({reference:received,bytes})}),plan=await createOriginalRestorePreview(zip.bytes,{projects:[p],visits:[],importJobs:[]},{check:async()=>{}}),mapping=createOriginalRestoreMapping(plan,{projects:['p'],visits:[],importJobs:[]},{projects:{p:'restored'},visits:{},importJobs:{}});assert.equal(mapping.originals[0].targetProjectId,'restored');assert.equal(mapping.sourceZipSHA256,plan.sourceZipSHA256);assert.equal(mapping.restoreReady,false);
 assert.throws(()=>createOriginalRestoreMapping({...preview,projects:[...preview.projects,{...preview.projects[0],id:'q',projectId:'q'}]},{projects:[],visits:[],importJobs:[]},{projects:{p:'same',q:'same'},visits:{v:'newv'},importJobs:{}}));
});
