const test=require('node:test'),assert=require('node:assert/strict');
const {createCSVPreviewService}=require('../src/rnd-control/csv-preview-service');
const fields=['id','buildingId','date','operator','reason','serviceScope','costBasis','evidenceUrl','totalMinutes','travel','check','work','report','contact','other','labor','transport','materials','outsourcing'];
const data=()=>({bytes:new TextEncoder().encode([fields.join(','),['csv-a','b','2026-09-17','op','inspect','routine','actual','https://example.com','0',...Array(10).fill('0')].join(',')].join('\n')),mapping:Object.fromEntries(fields.map(k=>[k,k])),projectId:'p',units:{minutes:'min',costs:'KRW'},source:{fileName:'visits.csv',ledger:'원장',extractedAt:'2026-09-17T00:00:00.000Z'}});
function fixture(){let actor={uid:'u',email:'u@example.test',role:'member'},generation=1,reads=[];const state={access:async()=>({...actor}),captureSession:()=>generation,isCurrent:binding=>binding===generation,list:async key=>{reads.push(key);return key==='projects'?[{id:'p'}]:[];}};return{state,reads,actor,reset:()=>generation++};}
test('Main CSV preview uses fresh approved shared collections, no renderer snapshots, no writes',async()=>{const f=fixture(),result=await createCSVPreviewService(f.state)(data());assert.equal(result.canApply,true);assert.equal(result.cloudWrites,false);assert.equal(result.actorUid,'u');assert.equal(result.source.projectId,'p');assert.deepEqual(f.reads.sort(),['projects','visits']);for(const key of ['current','projectIds','unknown'])await assert.rejects(()=>createCSVPreviewService(f.state)({...data(),[key]:[]}));});
test('Main CSV preview denies viewer/must-change/disabled approval before reading records',async()=>{for(const patch of [{role:'viewer'},{mustChangePassword:true},{uid:''}]){const f=fixture();Object.assign(f.actor,patch);await assert.rejects(()=>createCSVPreviewService(f.state)(data()));assert.equal(f.reads.length,0);}const f=fixture();f.state.access=async()=>{throw Error('approval disabled');};await assert.rejects(()=>createCSVPreviewService(f.state)(data()),/disabled/);});
test('Main CSV preview rejects account or same-account login generation changes during reads',async()=>{for(const change of [f=>f.actor.email='other@example.test',f=>f.reset()]){const f=fixture();f.state.list=async key=>{change(f);return key==='projects'?[{id:'p'}]:[];};await assert.rejects(()=>createCSVPreviewService(f.state)(data()),/세션/);}});
test('Main CSV preview freezes input before first await and preserves authoritative collision',async()=>{const f=fixture(),input=data(),original=input.bytes.slice();let resume,first=true;f.state.access=()=>{if(!first)return Promise.resolve({...f.actor});first=false;return new Promise(resolve=>{resume=()=>resolve({...f.actor});});};const pending=createCSVPreviewService(f.state)(input);input.bytes.fill(0);input.mapping.reason='operator';input.source.ledger='changed';f.state.access=async()=>({...f.actor});resume();const result=await pending;assert.equal(result.source.ledger,'원장');assert.equal(result.additions[0].data.reason,'inspect');const v=result.additions[0].data;f.state.list=async key=>key==='projects'?[{id:'p'}]:[v];const collision=await createCSVPreviewService(f.state)({...data(),bytes:original});assert.deepEqual(collision.conflicts,['csv-a']);assert.equal(collision.additions.length,0);});
test('Main CSV preview applies CRM secret policy to mapped and unmapped source cells and provenance',async()=>{for(const make of [input=>input.source.ledger='password: very-secret-123',input=>input.bytes=new TextEncoder().encode(new TextDecoder().decode(input.bytes).replace('inspect','password: very-secret-123')),input=>input.bytes=new TextEncoder().encode(new TextDecoder().decode(input.bytes).replace(fields.join(','),fields.join(',')+',password').replace('https://example.com,','https://example.com,')+',very-secret-123')]){const f=fixture(),input=data();make(input);await assert.rejects(()=>createCSVPreviewService(f.state)(input),/비밀번호|출입/);}});

test('Main CSV preview isolates SharedArrayBuffer source before secret scan and collection awaits',async()=>{const f=fixture(),input=data(),text=new TextDecoder().decode(input.bytes),changed=text.replace('inspect','password: 123'),shared=new Uint8Array(new SharedArrayBuffer(new TextEncoder().encode(changed).length));const clean=new TextEncoder().encode(text.replace('inspect','ordinary text'));shared.set(clean);input.bytes=shared;f.state.list=async key=>{shared.fill(0);shared.set(new TextEncoder().encode(changed));return key==='projects'?[{id:'p'}]:[];};const result=await createCSVPreviewService(f.state)(input);assert.equal(result.canApply,true);assert.equal(result.additions[0].data.reason,'ordinary text');});
