const test=require('node:test');const assert=require('node:assert/strict');
const actor={uid:'a',email:'a@example.test',role:'admin'},operationId='11111111-1111-4111-8111-111111111111';const value={projects:{q:{id:'q',operationId}},restoreApprovals:{[operationId]:{id:operationId,actorUid:'a'}}};
function service(fetch,extra={}){const {createAtomicRestoreCommit}=require('../src/rnd-control/restore-commit');return createAtomicRestoreCommit({access:async()=>actor,token:async()=> 'test-token',databaseUrl:'https://test.invalid',compile:()=>({value:structuredClone(value),audit:value.restoreApprovals[operationId],expectedETag:'"snapshot"',operationId}),fetch,...extra});}
test('restore commit uses one conditional PUT and returns verified operation without overwriting after412',async()=>{let writes=0;const commit=service(async(url,options)=>{writes++;assert.match(url,/rndControl\.json/);assert.equal(options.method,'PUT');assert.equal(options.headers['if-match'],'"snapshot"');assert.deepEqual(JSON.parse(options.body),value);return{ok:true,json:async()=>value};});const result=await commit({});assert.equal(writes,1);assert.equal(result.operationId,operationId);let conflicts=0;await assert.rejects(()=>service(async()=>{conflicts++;return{ok:false,status:412};})({}),/충돌/);assert.equal(conflicts,1);});
test('lost restore response is recovered by one full-root read and never a repeated write',async()=>{const methods=[];const result=await service(async(_url,options)=>{methods.push(options.method);if(options.method==='PUT')throw Error('response lost');return{ok:true,json:async()=>value};})({});assert.equal(result.recovered,true);assert.deepEqual(methods,['PUT','GET']);});
test('uncertain restore response with different remote content reports unknown result without retry',async()=>{const methods=[];await assert.rejects(()=>service(async(_url,options)=>{methods.push(options.method);if(options.method==='PUT')throw Error('lost');return{ok:true,json:async()=>({...value,other:'new'})};})({}),/결과 확인 불가/);assert.deepEqual(methods,['PUT','GET']);});
test('restore commit requires fresh administrator and denies session switch before network',async()=>{let calls=0;const fetch=async()=>{calls++;throw Error('must not run');};await assert.rejects(()=>service(fetch,{access:async()=>({...actor,role:'member'})})({}),/관리자/);let current={...actor};await assert.rejects(()=>service(fetch,{access:async()=>({...current}),token:async()=>{current.uid='other';return'token';}})({}),/세션/);assert.equal(calls,0);});

test('invalid success body is verified once by recovery read and permission denial never retries',async()=>{const methods=[];const result=await service(async(_url,o)=>{methods.push(o.method);return{ok:true,json:async()=>o.method==='PUT'?null:value};})({});assert.equal(result.recovered,true);assert.deepEqual(methods,['PUT','GET']);let calls=0;await assert.rejects(()=>service(async()=>{calls++;return{ok:false,status:403};})({}),/403/);assert.equal(calls,1);});
test('session switch after a write response prevents acknowledgement and recovery under another account',async()=>{let current={...actor};const methods=[];await assert.rejects(()=>service(async(_url,o)=>{methods.push(o.method);current.uid='other';return{ok:true,json:async()=>value};},{access:async()=>({...current})})({}),/세션/);assert.deepEqual(methods,['PUT']);});
