const test=require('node:test');const assert=require('node:assert/strict');
test('shared restore preflight uses fresh admin and verified backup, preserves collisions and identifies history',async()=>{
 const {createSharedRestorePreview}=require('../src/rnd-control/shared-restore-preview');const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {createMetadataBackup}=await import('../src/rnd-control/backup.mjs');const p=createProject('p','Shared'),collision=createProject('p','Backup'),q=createProject('q','Historical');q.history.push({kind:'source',actor:'archived',reason:'Original history',at:'2026-09-16T00:00:00.000Z'});const backup=await createMetadataBackup([collision,q],p.id);const before=JSON.stringify([p,backup]);let actor={uid:'admin',email:'admin@example.test',role:'admin'},reads=0;const service=createSharedRestorePreview({access:async()=>({...actor}),list:async collection=>{reads++;return collection==='projects'?[p]:[];}});
 const report=await service({backup});assert.equal(report.canApply,false);assert.equal(report.projects[0].action,'KEEP_EXISTING');assert.equal(report.projects[1].action,'REQUIRES_APPROVED_CREATE');assert.equal(report.projects[1].protectedCounts.projectHistory,1);assert.match(report.projects[0].sharedSHA256,/^[0-9a-f]{64}$/);assert.equal(JSON.stringify([p,backup]),before);assert.equal(reads,2);
 actor.role='member';reads=0;await assert.rejects(()=>service({backup}),/관리자/);assert.equal(reads,0);actor.role='admin';const bad=structuredClone(backup);bad.archive.projects[0].title='changed';await assert.rejects(()=>service({backup:bad}),/해시/);
 const switched=createSharedRestorePreview({access:async()=>({...actor}),list:async()=>{actor.uid='other';return [];}});await assert.rejects(()=>switched({backup}),/세션/);
});

test('shared restore preflight validates visit conflicts and rejects legacy backup or malformed frozen CRM records',async()=>{
 const {createSharedRestorePreview}=require('../src/rnd-control/shared-restore-preview');const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {createMetadataBackup}=await import('../src/rnd-control/backup.mjs');const p=createProject('p','P'),v={id:'v',revision:2,projectId:'p',buildingId:'b',operator:'op',reason:'inspect',serviceScope:'routine',costBasis:'actual',evidenceUrl:'https://example.com/source',date:'2026-09-17',minutes:{travel:0,check:0,work:0,report:0,contact:0,other:0},costs:{labor:0,transport:0,materials:0,outsourcing:0},totalMinutes:0};const backup=await createMetadataBackup([p],p.id,[v]);const service=createSharedRestorePreview({access:async()=>({uid:'admin',email:'a@example.test',role:'admin'}),list:async key=>key==='projects'?[p]:[v]});const report=await service({backup});assert.equal(report.visits[0].action,'KEEP_EXISTING');assert.equal(report.totals.visitConflicts,1);await assert.rejects(()=>service({backup:backup.archive}),/해시 검증/);
 const bad=structuredClone(p);bad.crmContexts={fake:{id:'fake',projectId:p.id}};await assert.rejects(async()=>service({backup:await createMetadataBackup([bad],bad.id)}),/고정 CRM/);
});
