const test=require('node:test'),assert=require('node:assert/strict');
const id='11111111-1111-4111-8111-111111111111';
function fixture(overrides={}){let generation=1,enabled=true,role='admin';const calls=[];const client=require('../src/rnd-control/shared-restore-client').createSharedRestoreClient({enabled:()=>enabled,access:async()=>({uid:'a',email:'a@example.test',role}),captureSession:()=>generation,isCurrent:guard=>generation===guard,token:async()=> 'private-token',baseUrl:'https://asia-southeast1-bring-fm.cloudfunctions.net',now:()=>1000,fetch:async(url,options)=>{calls.push({url,options});return{ok:true,json:async()=>({result:url.endsWith('rndPrepareSharedRestore')?{sessionId:id,expiresAt:601000,projects:{},visits:{},scope:'metadata-only'}:{operationId:id,status:'COMMITTED',audit:{id,actorUid:'a'}}})};},...overrides});return{client,calls,switch:()=>generation++,disable:()=>enabled=false,member:()=>role='member'};}
test('Main restore client prepares then commits only its own server session without exposing tokens',async()=>{const f=fixture();const prepared=await f.client.prepare({backup:{},reviewed:{},reason:'recover'});assert.equal(prepared.sessionId,id);assert.equal(JSON.stringify(prepared).includes('private-token'),false);const result=await f.client.commit({sessionId:id,mutation:{malicious:true}});assert.equal(result.status,'COMMITTED');assert.equal(f.calls.length,2);assert.deepEqual(JSON.parse(f.calls[1].options.body),{data:{sessionId:id}});assert.equal(f.calls[0].options.headers.Authorization,'Bearer private-token');});
test('Main restore client denies disabled feature, ordinary members and unknown approval IDs without HTTP writes',async()=>{for(const change of ['disable','member']){const f=fixture();f[change]();await assert.rejects(()=>f.client.prepare({}),/활성화|관리자/);assert.equal(f.calls.length,0);}const f=fixture();await assert.rejects(()=>f.client.commit({sessionId:id}),/승인/);assert.equal(f.calls.length,0);});
test('Main restore client binds approvals to actual login generation even for same UID',async()=>{const f=fixture();await f.client.prepare({backup:{},reviewed:{},reason:'recover'});f.switch();await assert.rejects(()=>f.client.commit({sessionId:id}),/세션/);assert.equal(f.calls.length,1);});
test('Main restore client never retries uncertain writes and keeps only the same explicit approval',async()=>{let requests=0;const f=fixture({fetch:async url=>{requests++;if(url.endsWith('rndPrepareSharedRestore'))return{ok:true,json:async()=>({result:{sessionId:id,expiresAt:601000,projects:{},visits:{},scope:'metadata-only'}})};throw Error('transport secret-private-token');}});await f.client.prepare({reason:'recover'});await assert.rejects(()=>f.client.commit({sessionId:id}),error=>/자동 재실행하지 않습니다/.test(error.message)&&!error.message.includes('secret-private-token'));assert.equal(requests,2);f.client.clear();await assert.rejects(()=>f.client.commit({sessionId:id}),/승인/);assert.equal(requests,2);});
test('Main restore client blocks expired approvals and public permission errors do not forward raw secrets',async()=>{let time=1000;const f=fixture({now:()=>time});await f.client.prepare({reason:'recover'});time=601000;await assert.rejects(()=>f.client.commit({sessionId:id}),/만료/);assert.equal(f.calls.length,1);const denied=fixture({fetch:async()=>({ok:false,json:async()=>({error:{status:'PERMISSION_DENIED',message:'private-token'}})})});await assert.rejects(()=>denied.client.prepare({reason:'recover'}),error=>/관리자 승인/.test(error.message)&&!error.message.includes('private-token'));});
test('Main restore client refuses switched session after token resolution before HTTP request',async()=>{let resolve;const f=fixture({token:()=>new Promise(done=>{resolve=done;})});const pending=f.client.prepare({reason:'recover'});while(!resolve)await new Promise(done=>setImmediate(done));f.switch();resolve('private-token');await assert.rejects(()=>pending,/세션/);assert.equal(f.calls.length,0);});
test('Main restore client captures reviewed input before waiting for current access',async()=>{let release,first=true;const f=fixture({access:async()=>{if(first){first=false;await new Promise(resolve=>release=resolve);}return{uid:'a',email:'a@example.test',role:'admin'};}});const input={reason:'Original reason',backup:{title:'Original backup'},reviewed:{hash:'original'}};const pending=f.client.prepare(input);while(!release)await new Promise(done=>setImmediate(done));input.reason='New reason';input.backup.title='Changed backup';release();await pending;const sent=JSON.parse(f.calls[0].options.body).data;assert.equal(sent.reason,'Original reason');assert.equal(sent.backup.title,'Original backup');});
