const test=require('node:test'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const bytes=Buffer.from('original'),sha256=createHash('sha256').update(bytes).digest('hex'),h='a'.repeat(64);
function fixture(options={}){const events=[],target={projectId:'p',artifactId:'a',versionId:'v',sha256,sizeBytes:bytes.length},plan={kind:'BRING_RND_ORIGINAL_REUPLOAD_PREPARATION',version:1,previewId:'review',mappingSHA256:h,sourceZipSHA256:h,originals:[{source:{providerFileId:'old'},target,fileName:'measure.csv',mimeType:'text/csv',bytes}],cloudWrites:false,canApply:false};let writes=0,active=true;
 const {createOriginalRestoreUploader}=require('../src/rnd-control/original-restore-uploader');
 const run=createOriginalRestoreUploader({enabled:true,prepare:async()=>({uploadPlan:plan}),check:async()=>{if(!active)throw Error('session changed');},authorize:async()=>({approved:true,actorUid:'u',previewId:'review',mappingSHA256:h,sourceZipSHA256:h}),journal:{begin:async record=>{events.push({type:'begin',...record});return 'attempt';},append:async(id,event)=>{assert.equal(id,'attempt');events.push(event);}},upload:async input=>{writes++;assert.deepEqual(input.bytes,bytes);if(options.fail){const error=Error('network uncertain');if(options.recovery)error.recoveryRecord={...target,id:'orphan',hash:sha256,size:bytes.length,status:'UPLOADED_UNVERIFIED',observedAt:new Date().toISOString()};throw error;}if(options.logout)active=false;return {...target,providerFileId:'new',verifiedAt:new Date().toISOString()};},...options.dependencies});
 return{run,events,writes:()=>writes,plan};}
test('original uploader defaults off and requires a matching trusted approval before any reservation or write',async()=>{const {createOriginalRestoreUploader}=require('../src/rnd-control/original-restore-uploader');await assert.rejects(()=>createOriginalRestoreUploader({})({}),/비활성/);const f=fixture({dependencies:{authorize:async()=>({approved:true,mappingSHA256:'wrong'})}});await assert.rejects(()=>f.run({}),/승인/);assert.equal(f.writes(),0);assert.equal(f.events.length,0);});
test('approved uploader reserves first and preserves verified original receipts without database mutation',async()=>{const f=fixture(),result=await f.run({});assert.equal(f.writes(),1);assert.equal(f.events[0].type,'begin');assert.equal(f.events[1].type,'UPLOAD_STARTED');assert.equal(f.events[2].type,'UPLOAD_VERIFIED');assert.equal(f.events[2].sourceProviderFileId,'old');assert.equal(result.databaseWrites,false);assert.equal(result.receipts[0].providerFileId,'new');assert.equal(f.events.some(e=>Object.hasOwn(e,'bytes')),false);});
test('uncertain upload is recorded and stops batch without automatic retry',async()=>{const f=fixture({fail:true});await assert.rejects(()=>f.run({}),/network uncertain/);assert.equal(f.writes(),1);assert.equal(f.events.at(-1).type,'UPLOAD_UNCERTAIN');});
test('logout after upload still preserves receipt for initiating actor before failing',async()=>{const f=fixture({logout:true});await assert.rejects(()=>f.run({}),/session changed/);assert.equal(f.events.at(-1).type,'UPLOAD_VERIFIED');assert.equal(f.events[0].actorUid,'u');});
test('all originals are preflighted before any upload and changed source bytes are denied',async()=>{const f=fixture();f.plan.originals.push({...f.plan.originals[0],target:{...f.plan.originals[0].target,versionId:'v2'},fileName:'bad.exe'});await assert.rejects(()=>f.run({}),/승인 형식/);assert.equal(f.writes(),0);assert.equal(f.events.length,0);});

test('unverified Drive file ID is preserved only when exact target and byte binding match',async()=>{const f=fixture({fail:true,recovery:true});await assert.rejects(()=>f.run({}),/network uncertain/);assert.equal(f.events.at(-1).providerFileId,'orphan');assert.equal(f.events.at(-1).type,'UPLOAD_UNCERTAIN');});
