const test=require('node:test'),assert=require('node:assert/strict');const h='a'.repeat(64),target={projectId:'new',artifactId:'new_a',versionId:'new_v',sha256:h,sizeBytes:3},source={projectId:'old',artifactId:'a',versionId:'v',providerFileId:'f',sha256:h,sizeBytes:3},started={type:'UPLOAD_STARTED',sourceProviderFileId:'f',...target},verified={...started,type:'UPLOAD_VERIFIED',providerFileId:'new_f',verifiedAt:'2026-09-17T00:00:00.000Z'};
function fixture(change=()=>{}){const plan={previewId:'fresh',mappingSHA256:'b'.repeat(64),sourceZipSHA256:h,originals:[{source,target}],kind:'BRING_RND_ORIGINAL_REUPLOAD_PREPARATION',version:1,cloudWrites:false,canApply:false,restoreReady:false},record={attemptId:h,actorUid:'u',previewId:'old-review',mappingSHA256:'c'.repeat(64),sourceZipSHA256:h,files:[{sourceProviderFileId:'f',target}],events:[started,verified],incomplete:false};let checks=0,calls=0;const options={actorUid:'u',check:async()=>{checks++;},prepare:async()=>({uploadPlan:plan}),journal:{get:async(uid,id)=>{assert.equal(uid,'u');assert.equal(id,h);return record;}},verifyVersion:async ref=>{calls++;assert.equal(ref.projectId,'new');return{...ref,mimeType:'text/csv',verifiedAt:'2026-09-17T01:00:00.000Z',url:'https://evil.test',token:'secret'};}};change({plan,record,options});const {createOriginalRestoreReferenceVerifier}=require('../src/rnd-control/original-restore-reference-verification');return{run:createOriginalRestoreReferenceVerifier(options),calls:()=>calls,checks:()=>checks};}
const request={attemptId:h,previewId:'fresh',targets:{projects:{old:'new'},visits:{},importJobs:{}}};
test('fresh private source and owned journal receipt are reverified against company Drive before reference rebinding',async()=>{const f=fixture(),result=await f.run(request);assert.equal(f.calls(),1);assert.equal(result.verifiedRefs[0].sourceProviderFileId,'f');assert.equal(result.verifiedRefs[0].reference.projectId,'new');assert.equal(result.verifiedRefs[0].reference.verifiedAt,'2026-09-17T01:00:00.000Z');assert.equal(result.verifiedRefs[0].reference.url,'https://drive.google.com/file/d/new_f/view');assert.equal(result.verifiedRefs[0].reference.token,undefined);assert.equal(result.sourceAttemptMappingSHA256,'c'.repeat(64));assert.equal(result.mappingSHA256,'b'.repeat(64));assert.equal(result.cloudWrites,false);});
test('foreign actor, changed ZIP, incomplete and mismatched batch receipts are denied before Drive calls',async()=>{for(const change of [f=>{f.record.actorUid='other';},f=>{f.record.sourceZipSHA256='d'.repeat(64);},f=>{f.record.incomplete=true;},f=>{f.record.events.pop();},f=>{f.record.events[1]={...verified,sha256:'d'.repeat(64)};},f=>{f.record.events=[verified,verified];}]){const f=fixture(change);await assert.rejects(()=>f.run(request),/원본 복원/);assert.equal(f.calls(),0);}});
test('changed Drive bytes and async session changes suppress rebinding results',async()=>{for(const mode of ['hash','session']){let changed=false;const f=fixture(({options})=>{const original=options.verifyVersion;options.verifyVersion=async ref=>{const result=await original(ref);changed=true;return mode==='hash'?{...result,sha256:'d'.repeat(64)}:result;};options.check=async()=>{if(mode==='session'&&changed)throw Error('session changed');};});await assert.rejects(()=>f.run(request));}});

test('production Drive adapter rechecks owned file bytes before deriving a new dataset manifest from recovered receipts',async()=>{
 const {createHash}=require('node:crypto'),{createRndDrive,COMPANY}=require('../src/rnd-control/drive'),{createOriginalRestoreReferenceVerifier}=require('../src/rnd-control/original-restore-reference-verification'),{createDatasetSnapshot,createRestoredDatasetSnapshot,verifyDatasetManifest}=await import('../src/rnd-control/dataset.mjs');const bytes=Buffer.from([255,0,128]),sha256=createHash('sha256').update(bytes).digest('hex'),bound={...target,sha256};let media=0;
 const drive=createRndDrive({rootFolderId:'root',auth:()=>({user:{uid:'u',email:'u@test',role:'admin'}}),fetch:async url=>{if(url.includes('userinfo'))return{ok:true,json:async()=>({email:COMPANY,email_verified:true})};if(url.includes('/files/root?'))return{ok:true,json:async()=>({id:'root',mimeType:'application/vnd.google-apps.folder',capabilities:{canAddChildren:true},owners:[{emailAddress:COMPANY}]})};if(url.includes('alt=media')){media++;let sent=false;return{ok:true,body:{getReader:()=>({read:async()=>sent?{done:true}:(sent=true,{done:false,value:bytes}),cancel:async()=>{}})}};}return{ok:true,json:async()=>({id:'new_f',parents:['root'],size:3,mimeType:'text/csv',owners:[{emailAddress:COMPANY}],appProperties:{projectId:'new',artifactId:'new_a',rndVersion:'new_v',sha256}})};}});await drive.connect('fixture-token');
 const oldRef={...source,sha256,verifiedAt:'2026-09-17T00:00:00.000Z'},dataset=createDatasetSnapshot({id:'old',research:{experiments:[{id:'e',status:'running',planVersion:1,frozenPlan:{metric:'minutes'}}]}},{id:'d',experimentId:'e',version:'v',population:'buildings',selectionRule:'chosen',exclusions:'none',periodStart:'2026-09-01',periodEnd:'2026-09-02',unitType:'building',unitIds:['b'],rowCount:1,versionRefs:[oldRef]},{uid:'old_actor'});
 const plan={kind:'BRING_RND_ORIGINAL_REUPLOAD_PREPARATION',version:1,canApply:false,cloudWrites:false,restoreReady:false,previewId:'fresh',mappingSHA256:'b'.repeat(64),sourceZipSHA256:h,originals:[{source:{...source,sha256},target:bound}]},record={attemptId:h,actorUid:'u',sourceZipSHA256:h,mappingSHA256:'c'.repeat(64),files:[{sourceProviderFileId:'f',target:bound}],events:[{...started,sha256},{...verified,sha256}],incomplete:false};
 const refs=await createOriginalRestoreReferenceVerifier({actorUid:'u',check:async()=>{},prepare:async()=>({uploadPlan:plan}),journal:{get:async()=>record},verifyVersion:ref=>drive.verifyVersion(ref)})(request),derived=createRestoredDatasetSnapshot(dataset,{projectId:'new',actorUid:'u',at:new Date().toISOString(),sourceZipSHA256:h,mappingSHA256:refs.mappingSHA256,verifiedRefs:refs.verifiedRefs});assert.equal(media,1);assert.equal(derived.versionRefs[0].providerFileId,'new_f');assert.equal(verifyDatasetManifest(derived),true);assert.notEqual(derived.manifestHash,dataset.manifestHash);const {createProject}=await import('../src/rnd-control/portfolio.mjs'),{deriveRestoredProject}=await import('../src/rnd-control/restored-project.mjs'),project=createProject('old','Drive recovered project');project.items[0].evidence=[oldRef];project.research={experiments:[{id:'e',status:'closed',planVersion:1,frozenPlan:{metric:'minutes'},dataset:{datasetSnapshotId:'d',manifestHash:dataset.manifestHash,version:dataset.version,url:'https://drive.google.com/file/d/f/view'}}],datasetSnapshots:[dataset]};const restored=deriveRestoredProject(project,{projectId:'new',actorUid:'u',at:new Date().toISOString(),sourceZipSHA256:h,mappingSHA256:refs.mappingSHA256,verifiedRefs:refs.verifiedRefs});assert.equal(restored.project.research.datasetSnapshots[0].versionRefs[0].providerFileId,'new_f');assert.equal(restored.project.research.experiments[0].dataset.manifestHash,restored.project.research.datasetSnapshots[0].manifestHash);assert.equal(restored.databaseWrites,false);
});
