const test=require('node:test');const assert=require('node:assert/strict');
const actor={uid:'author',role:'member'},reviewer={uid:'reviewer',role:'member'};
async function setup(){const model=await import('../src/rnd-control/research.mjs');const p={id:'p',research:{experiments:[],evidence:[],decisions:[],history:[]}};return{model,p};}
const plan={id:'exp-1',hypothesis:'H2',question:'검색시간이 줄어드는가',comparison:'현행 vs 구조화',population:'내부 사용자',period:'2주',metrics:'검색시간',analysis:'대응 비교',success:'사전 기준 충족',stop:'원본 접근 불가',reviewerUid:'reviewer'};
test('experiment cannot start before independent plan approval',async()=>{const{model,p}=await setup();const q=model.applyResearch(p,{type:'create',plan},actor);assert.throws(()=>model.applyResearch(q,{type:'start',id:'exp-1'},actor),/승인/);assert.throws(()=>model.applyResearch(q,{type:'approve',id:'exp-1'},actor),/검토자/);});
test('approved plan snapshot survives execution and closure',async()=>{const{model,p}=await setup();let q=model.applyResearch(p,{type:'create',plan},actor);q=model.applyResearch(q,{type:'approve',id:'exp-1'},reviewer);q=model.applyResearch(q,{type:'start',id:'exp-1'},actor);q=model.applyResearch(q,{type:'close',id:'exp-1',outcome:'inconclusive',result:'표본 부족',dataset:{version:'v1',url:'https://example.com/data',sampleUnits:2}},actor);assert.equal(q.research.experiments[0].status,'closed');assert.deepEqual(q.research.experiments[0].frozenPlan,plan);assert.equal(q.research.experiments[0].outcome,'inconclusive');});
test('viewer cannot change research state',async()=>{const{model,p}=await setup();assert.throws(()=>model.applyResearch(p,{type:'create',plan},{uid:'v',role:'viewer'}),/권한/);});
test('decision must link approved evidence and preserve limitations',async()=>{const{model,p}=await setup();assert.throws(()=>model.applyResearch(p,{type:'decision',id:'d',action:'continue',reason:'검토',evidenceIds:['missing']},{uid:'admin',role:'admin'}),/근거/);});
test('explicit hypothesis template creates eight untested project and framework scoped hypotheses',async()=>{const {model,p}=await setup();const q=model.applyResearch(p,{type:'hypothesisTemplate',frameworkVersion:'bring-v1',reviewerUid:'reviewer'},actor);assert.equal(q.research.hypotheses.length,8);assert.ok(q.research.hypotheses.every(h=>h.status==='NOT_TESTED'&&h.projectId==='p'&&h.frameworkVersion==='bring-v1'));assert.equal(q.research.hypotheses.filter(h=>h.scope==='core').length,6);assert.equal(q.research.hypotheses.at(-1).scope,'long_term');assert.throws(()=>model.applyResearch(q,{type:'hypothesisTemplate',frameworkVersion:'bring-v1',reviewerUid:'reviewer'},actor),/이미/);const other=model.applyResearch({...p,id:'other'},{type:'hypothesisTemplate',frameworkVersion:'bring-v1',reviewerUid:'reviewer'},actor);assert.notEqual(q.research.hypotheses[1].id,other.research.hypotheses[1].id);});
test('hypothesis assessment needs matching approved evidence and designated reviewer',async()=>{const {model,p}=await setup();let q=model.applyResearch(p,{type:'hypothesisTemplate',frameworkVersion:'bring-v1',reviewerUid:'reviewer'},actor);const h=q.research.hypotheses[2];q.research.experiments=[{id:'exp',plan:{hypothesis:'H2',frameworkVersion:'bring-v1'},status:'closed'}];q.research.evidence=[{id:'ev',experimentId:'exp',status:'approved',source:{version:'v1'}}];const command={type:'assessHypothesis',id:'ha1',hypothesisId:h.id,status:'INCONCLUSIVE',reason:'표본 부족',evidenceIds:['ev']};assert.throws(()=>model.applyResearch(q,command,actor),/검토자/);const next=model.applyResearch(q,command,reviewer);assert.equal(next.research.hypotheses[2].status,'NOT_TESTED');assert.equal(next.research.hypothesisAssessments[0].status,'INCONCLUSIVE');assert.deepEqual(next.research.hypothesisAssessments[0].sources,[{evidenceId:'ev',version:'v1'}]);assert.throws(()=>model.applyResearch(q,{...command,hypothesisId:q.research.hypotheses[1].id},reviewer),/가설/);});
test('same hypothesis code in another framework cannot reuse prior framework evidence',async()=>{const {model,p}=await setup();let q=model.applyResearch(p,{type:'hypothesisTemplate',frameworkVersion:'old-v1',reviewerUid:'reviewer'},actor);q=model.applyResearch(q,{type:'hypothesisTemplate',frameworkVersion:'new-v1',reviewerUid:'reviewer'},actor);q.research.experiments=[{id:'exp',plan:{hypothesis:'H2',frameworkVersion:'old-v1'},status:'closed'}];q.research.evidence=[{id:'ev',experimentId:'exp',status:'approved',source:{version:'v1'}}];const h=q.research.hypotheses.find(h=>h.code==='H2'&&h.frameworkVersion==='new-v1');assert.throws(()=>model.applyResearch(q,{type:'assessHypothesis',id:'ha',hypothesisId:h.id,status:'SUPPORTED',reason:'검토',evidenceIds:['ev']},reviewer),/가설/);assert.throws(()=>model.applyResearch(q,{type:'create',plan},actor),/체계 버전/);});
test('plan revision preserves original execution and requires fresh approval',async()=>{const {model,p}=await setup();let q=model.applyResearch(p,{type:'create',plan},actor);q=model.applyResearch(q,{type:'approve',id:plan.id},reviewer);q=model.applyResearch(q,{type:'start',id:plan.id},actor);const original=structuredClone(q.research.experiments[0]);const revised=model.applyResearch(q,{type:'revisePlan',id:'exp-2',parentExperimentId:plan.id,reason:'기간 연장',appliesTo:'다음 수집 대상부터 적용, 이전 데이터 제외',patch:{period:'4주',success:'새 사전 기준'}},actor);assert.deepEqual(revised.research.experiments[0],original);const e=revised.research.experiments[1];assert.equal(e.planVersion,2);assert.equal(e.parentExperimentId,plan.id);assert.equal(e.rootExperimentId,plan.id);assert.equal(e.status,'draft');assert.equal(e.plan.period,'4주');assert.equal(e.frozenPlan,undefined);assert.throws(()=>model.applyResearch(revised,{type:'start',id:e.id},actor),/승인/);const approved=model.applyResearch(revised,{type:'approve',id:e.id},reviewer);assert.equal(approved.research.experiments[1].frozenPlan.success,'새 사전 기준');assert.deepEqual(approved.research.experiments[0],original);});
test('plan revision rejects missing scope, hypothesis changes and duplicate replacement',async()=>{const {model,p}=await setup();let q=model.applyResearch(p,{type:'create',plan},actor);q=model.applyResearch(q,{type:'approve',id:plan.id},reviewer);const c={type:'revisePlan',id:'exp-2',parentExperimentId:plan.id,reason:'변경',appliesTo:'새 대상',patch:{success:'새 기준'}};assert.throws(()=>model.applyResearch(q,{...c,appliesTo:''},actor),/적용/);assert.throws(()=>model.applyResearch(q,{...c,patch:{hypothesis:'H1'}},actor),/가설/);const next=model.applyResearch(q,c,actor);assert.throws(()=>model.applyResearch(next,{...c,id:'exp-3'},actor),/이미/);});

test('incomplete plan draft can be saved and author-completed but cannot be approved',async()=>{const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {applyResearch}=await import('../src/rnd-control/research.mjs');const user={uid:'author',role:'member'};let p=applyResearch(createProject('p','draft'),{type:'createDraft',plan:{id:'d',hypothesis:'H2'}},user);assert.equal(p.research.experiments[0].status,'draft');assert.throws(()=>applyResearch(p,{type:'approve',id:'d'},{uid:'reviewer',role:'admin'}),/필수/);assert.throws(()=>applyResearch(p,{type:'editDraft',id:'d',patch:{question:'q'},reason:'fill'},{uid:'other',role:'member'}),/작성자/);p=applyResearch(p,{type:'editDraft',id:'d',patch:{question:'q'},reason:'fill'},user);assert.equal(p.research.experiments[0].plan.question,'q');assert.equal(p.research.experiments[0].planVersion,1);assert.equal(p.research.history.at(-1).reason,'fill');});
