const test=require('node:test');const assert=require('node:assert/strict');test('import preview rejects malformed stages and preserves colliding drafts',async()=>{const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {previewImport,applyImport}=await import('../src/rnd-control/import.mjs');const p=createProject('p','original');const incoming=createProject('p','file');const q=createProject('q','new');const plan=previewImport([p],[incoming,q]);assert.deepEqual(plan.conflicts,['p']);assert.deepEqual(plan.additions,['q']);const next=applyImport([p],[incoming,q]);assert.equal(next[0].title,'original');assert.equal(next.length,2);next[1].title='edited';assert.equal(q.title,'new');const bad=structuredClone(q);bad.trl[1].level=1;assert.throws(()=>previewImport([p],[bad]));assert.throws(()=>previewImport([p],[q,q]));});

test('research import rejects orphan links, foreign project and duplicate records',async()=>{const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {previewImport}=await import('../src/rnd-control/import.mjs');const p=createProject('p','research');p.research={experiments:[{id:'e',planVersion:1}],evidence:[{id:'v',experimentId:'missing'}]};assert.throws(()=>previewImport([],[p]),/참조/);p.research.evidence[0].experimentId='e';assert.equal(previewImport([],[p]).additions.length,1);p.research.experiments[0].projectId='other';assert.throws(()=>previewImport([],[p]),/프로젝트/);delete p.research.experiments[0].projectId;p.research.evidence.push({...p.research.evidence[0]});assert.throws(()=>previewImport([],[p]),/중복/);});
test('research import protects metric reference ledger, lineage root and reviewer source versions',async()=>{
 const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {previewImport}=await import('../src/rnd-control/import.mjs');
 const p=createProject('p','links');p.research={experiments:[{id:'e',planVersion:1},{id:'e2',planVersion:2,parentExperimentId:'e',rootExperimentId:'wrong'}],evidence:[]};
 assert.throws(()=>previewImport([],[p]),/계보/);p.research.experiments[1].rootExperimentId='e';p.research.evidence=[{id:'v',experimentId:'e',source:{version:'v1'},metricResultIds:[],metricResultRefs:'["removed"]'}];
 assert.throws(()=>previewImport([],[p]),/원장/);p.research.evidence[0].metricResultRefs='[]';p.research.decisions=[{id:'d',evidenceIds:['v'],sources:[{evidenceId:'v',version:'v2'}]}];
 assert.throws(()=>previewImport([],[p]),/고정 버전/);p.research.decisions[0].sources[0].version='v1';assert.equal(previewImport([],[p]).additions.length,1);
 p.research.decisions[0].evidenceIds=['v','v'];assert.throws(()=>previewImport([],[p]),/중복/);
});
