const test=require('node:test');const assert=require('node:assert/strict');const {createRndRepository}=require('../src/rnd-control/repository');
const admin={uid:'a',email:'a@example.test',role:'admin'};
test('restore snapshot reads the entire R&D root once with a required ETag and fresh admin',async()=>{let calls=0;const source={projects:{p:{id:'p'}},visits:{v:{id:'v'}},futureField:{keep:true}};const repo=createRndRepository({auth:()=>({user:admin}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async(url,options)=>{calls++;assert.match(url,/rndControl\.json/);assert.equal(options.method,'GET');assert.equal(options.headers['X-Firebase-ETag'],'true');return{ok:true,headers:{get:()=> '"snapshot"'},json:async()=>source};}});const snapshot=await repo.readRestoreSnapshot();assert.equal(calls,1);assert.equal(snapshot.etag,'"snapshot"');assert.deepEqual(snapshot.value,source);assert.match(snapshot.contentSHA256,/^[0-9a-f]{64}$/);source.futureField.keep=false;assert.equal(snapshot.value.futureField.keep,true);});
test('restore snapshot rejects member, missing ETag and switched sessions',async()=>{const build=(role,fetch)=>createRndRepository({auth:()=>({user:{...admin,role}}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch});await assert.rejects(()=>build('member',async()=>{throw Error('must not read');}).readRestoreSnapshot(),/관리자/);await assert.rejects(()=>build('admin',async()=>({ok:true,headers:{get:()=>null},json:async()=>null})).readRestoreSnapshot(),/버전/);let user=admin;const repo=createRndRepository({auth:()=>({user}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async()=>{user={...admin,uid:'other'};return{ok:true,headers:{get:()=> 'etag'},json:async()=>null};}});await assert.rejects(()=>repo.readRestoreSnapshot(),/세션/);});

test('atomic approval preparation compares both collections from one snapshot and preserves unrelated root data',async()=>{
 const {prepareAtomicRestoreApproval}=require('../src/rnd-control/shared-restore-approval');const {createSharedRestorePreview}=require('../src/rnd-control/shared-restore-preview');const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {createMetadataBackup}=await import('../src/rnd-control/backup.mjs');const p=createProject('p','P'),q=createProject('q','Q');const backup=await createMetadataBackup([p,q],p.id);const root={projects:{p},visits:{},unknown:{keep:true}};const access=async()=>admin;const reviewed=await createSharedRestorePreview({access,list:async key=>Object.values(root[key])})({backup});let reads=0;const result=await prepareAtomicRestoreApproval({backup,reviewed,reason:'Recovery',access,readSnapshot:async()=>{reads++;return{value:root,etag:'"one"',actorUid:admin.uid,contentSHA256:'a'.repeat(64)};}});assert.equal(reads,1);assert.equal(result.snapshotETag,'"one"');assert.equal(result.snapshotSHA256,'a'.repeat(64));assert.deepEqual(result.projects.map(p=>p.id),['q']);assert.equal(result.canApply,false);assert.deepEqual(root.unknown,{keep:true});
});

test('atomic approval preparation rejects an actor switch during snapshot read',async()=>{
 const {prepareAtomicRestoreApproval}=require('../src/rnd-control/shared-restore-approval');let actor={...admin};await assert.rejects(()=>prepareAtomicRestoreApproval({backup:{},reviewed:{},reason:'Recovery',access:async()=>({...actor}),readSnapshot:async()=>{actor.uid='other';return{value:null,etag:'etag',actorUid:admin.uid,contentSHA256:'a'.repeat(64)};}}),/세션/);
});
