const test=require('node:test');const assert=require('node:assert/strict');const {createHash}=require('node:crypto');const {researchFingerprint}=require('../src/rnd-control/repository');
async function fixture(id='q',extra={}){const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {createMetadataBackup}=await import('../src/rnd-control/backup.mjs');const {createSharedRestorePreview}=require('../src/rnd-control/shared-restore-preview');const {prepareAtomicRestoreApproval}=require('../src/rnd-control/shared-restore-approval');const p=createProject('p','Existing'),q=createProject(id,'Archive');q.revision=7;q.history.push({kind:'source',actor:'original',reason:'Audit',at:'2026-09-16T00:00:00.000Z'});const value={projects:{p},visits:{},unknown:{keep:true},...extra};const actor={uid:'a',email:'a@example.test',role:'admin'};const backup=await createMetadataBackup([p,q],p.id);const access=async()=>actor;const reviewed=await createSharedRestorePreview({access,list:async key=>Object.values(value[key])})({backup});const snapshot={value,etag:'"one"',actorUid:'a',contentSHA256:createHash('sha256').update(researchFingerprint(value)).digest('hex')};const plan=await prepareAtomicRestoreApproval({backup,reviewed,reason:'Recover source',access,readSnapshot:async()=>snapshot});return{snapshot,plan,q};}
test('restore mutation preserves complete original root and history with one trusted audit and new record only',async()=>{const {createRestoreMutation}=require('../src/rnd-control/restore-mutation');const {snapshot,plan,q}=await fixture();const before=JSON.stringify([snapshot,plan]);const mutation=createRestoreMutation({snapshot,plan,operationId:'11111111-1111-4111-8111-111111111111',at:'2026-09-17T00:00:00.000Z'});assert.deepEqual(mutation.value.projects.p,snapshot.value.projects.p);assert.deepEqual(mutation.value.unknown,{keep:true});assert.deepEqual(mutation.value.projects.q.history,q.history);assert.equal(mutation.value.projects.q.revision,1);assert.equal(mutation.value.projects.q.updatedBy,'a');assert.equal(mutation.audit.projects.q.sourceRevision,7);assert.equal(mutation.audit.actorUid,'a');assert.equal(mutation.value.restoreApprovals[mutation.audit.id].reason,'Recover source');assert.equal(mutation.expectedETag,'"one"');assert.equal(JSON.stringify([snapshot,plan]),before);});
test('restore mutation rejects tampered plan, stale snapshot and unsafe operation IDs',async()=>{const {createRestoreMutation}=require('../src/rnd-control/restore-mutation');const {snapshot,plan}=await fixture();const input={snapshot,plan,operationId:'11111111-1111-4111-8111-111111111111',at:'2026-09-17T00:00:00.000Z'};await assert.rejects(async()=>createRestoreMutation({...input,plan:{...plan,reason:'forged'}}),/계획.*해시/);await assert.rejects(async()=>createRestoreMutation({...input,snapshot:{...snapshot,value:{...snapshot.value,unknown:{keep:false}}}}),/스냅샷/);await assert.rejects(async()=>createRestoreMutation({...input,operationId:'../bad'}),/작업/);});

test('reserved prototype spelling is restored as an own serialized record without altering collection prototype',async()=>{const {createRestoreMutation}=require('../src/rnd-control/restore-mutation');const {snapshot,plan}=await fixture('__proto__');const result=createRestoreMutation({snapshot,plan,operationId:'11111111-1111-4111-8111-111111111111',at:'2026-09-17T00:00:00.000Z'});assert.equal(Object.hasOwn(result.value.projects,'__proto__'),true);assert.equal(JSON.parse(JSON.stringify(result.value)).projects.__proto__.id,'__proto__');assert.equal(Object.getPrototypeOf(result.value.projects),Object.prototype);});

test('real prepared plan compiles through restore transport with trusted operation identity and preserved source history',async()=>{const {createAtomicRestoreCommit}=require('../src/rnd-control/restore-commit');const {snapshot,plan,q}=await fixture();let body;const commit=createAtomicRestoreCommit({access:async()=>({uid:'a',email:'a@example.test',role:'admin'}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async(_url,o)=>{body=JSON.parse(o.body);assert.equal(o.headers['if-match'],snapshot.etag);return{ok:true,json:async()=>body};}});const out=await commit({snapshot,plan,operationId:'forged',at:'forged'});assert.match(out.operationId,/^[0-9a-f-]{36}$/);assert.equal(body.projects.q.operationId,out.operationId);assert.equal(body.projects.q.restoreApprovalId,out.operationId);assert.deepEqual(body.projects.q.history,q.history);assert.equal(body.restoreApprovals[out.operationId].actorUid,'a');});

test('metadata restore preserves shared CSV audits exactly without replaying visits or changing publication facts',async()=>{const importJobs={'11111111-1111-4111-8111-111111111111':{id:'11111111-1111-4111-8111-111111111111',kind:'BRING_RND_CSV_IMPORT_AUDIT',importJobJSON:'original immutable metadata',publishedAt:'2026-09-16T00:00:00.000Z',publishedByUID:'original',driveReference:{providerFileId:'original-file'}}};const {snapshot,plan}=await fixture('q',{importJobs});const {createRestoreMutation}=require('../src/rnd-control/restore-mutation');const mutation=createRestoreMutation({snapshot,plan,operationId:'22222222-2222-4222-8222-222222222222',at:'2026-09-17T00:00:00.000Z'});assert.equal(JSON.stringify(mutation.value.importJobs),JSON.stringify(importJobs));assert.deepEqual(mutation.value.visits,{});assert.deepEqual(snapshot.value.importJobs,importJobs);});
test('metadata restore refuses malformed shared CSV audit collection',async()=>{const {createRestoreMutation}=require('../src/rnd-control/restore-mutation');for(const importJobs of [[],42,'corrupt']){const {snapshot,plan}=await fixture('q',{importJobs});assert.throws(()=>createRestoreMutation({snapshot,plan,operationId:'22222222-2222-4222-8222-222222222222',at:'2026-09-17T00:00:00.000Z'}),/CSV/);}});
