const test=require('node:test');const assert=require('node:assert/strict');const {createRndRepository}=require('../src/rnd-control/repository');
const project={id:'p',title:'연구',revision:0};
test('unauthenticated and viewer writes refused',async()=>{await assert.rejects(()=>createRndRepository({auth:()=>({})}).save('projects',project),/로그인/);await assert.rejects(()=>createRndRepository({auth:()=>({user:{uid:'u',role:'viewer'}})}).save('projects',project),/권한/);});
test('ETag conflict cannot overwrite newer project',async()=>{let calls=0;const repo=createRndRepository({auth:()=>({user:{uid:'u',role:'member'}}),token:async()=> 'test-token',databaseUrl:'https://test.invalid',fetch:async(_url,options)=>{calls++;if(options.method==='GET')return{ok:true,headers:{get:()=> '"v1"'},json:async()=>null};return{ok:false,status:412};}});await assert.rejects(()=>repo.save('projects',project),/충돌/);assert.equal(calls,2);});
test('save records trusted actor and remote revision',async()=>{let payload;const repo=createRndRepository({auth:()=>({user:{uid:'u',role:'member'}}),token:async()=> 'test-token',databaseUrl:'https://test.invalid',fetch:async(_url,options)=>{if(options.method==='GET')return{ok:true,headers:{get:()=> '"null"'},json:async()=>null};payload=JSON.parse(options.body);payload=Object.fromEntries(Object.entries(payload).map(([k,v])=>[k.split("/").at(-1),v]));return{ok:true,json:async()=>payload};}});const result=await repo.save('projects',{...project,updatedBy:'forged'});assert.equal(result.updatedBy,'u');assert.equal(result.revision,1);});
test('session switch during read prevents write',async()=>{let user={uid:'u',role:'member'};const repo=createRndRepository({auth:()=>({user}),token:async()=> 'test-token',databaseUrl:'https://test.invalid',fetch:async()=>{user={uid:'other',role:'member'};return{ok:true,headers:{get:()=> 'etag'},json:async()=>null};}});await assert.rejects(()=>repo.save('projects',project),/세션/);});
const user={uid:'u',role:'member'};
test('Firebase omitted empty arrays do not block unchanged research save',async()=>{const previous={...project,revision:1,research:{experiments:{0:{id:'e',status:'draft'} }}};let writes=0;const repo=createRndRepository({auth:()=>({user}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async(_,options)=>{if(options.method==='GET')return{ok:true,headers:{get:()=> 'etag'},json:async()=>previous};writes++;return{ok:true,json:async()=>JSON.parse(options.body)};}});await repo.save('projects',{...previous,research:{experiments:[{id:'e',status:'draft'}],evidence:[],decisions:[],history:[]}});assert.equal(writes,1);await assert.rejects(()=>repo.save('projects',{...previous,research:{experiments:[{id:'e',status:'approved'}]}}),/전용 승인/);assert.equal(writes,1);});
test('keyed research records match hydrated arrays and cannot be removed',async()=>{const {researchFingerprint,rndPatch}=require('../src/rnd-control/repository');const r={experiments:{e:{id:'e',status:'draft'}}};assert.equal(researchFingerprint(r),researchFingerprint({experiments:[{id:'e',status:'draft'}],history:[]}));assert.throws(()=>rndPatch({research:r},{id:'p',research:{experiments:[]}}),/삭제/);});
test('server revision rejection reports a concurrent edit without retry overwrite',async()=>{let reads=0,writes=0;const repo=createRndRepository({auth:()=>({user}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async(_,o)=>{if(o.method==='GET'){reads++;return{ok:true,headers:{get:()=> 'etag'},json:async()=>({...project,revision:reads===1?1:2})};}writes++;return{ok:false,status:403};}});await assert.rejects(()=>repo.save('projects',{...project,revision:1}),/충돌/);assert.equal(writes,1);});

test('single record read addresses only selected project and rejects session changes before network',async()=>{let endpoint,calls=0,current={uid:'u',role:'viewer'};const repo=createRndRepository({auth:()=>({user:current}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async(url)=>{calls++;endpoint=url;return{ok:true,json:async()=>project};}});assert.deepEqual(await repo.get('projects','p'),project);assert.match(endpoint,/rndControl\/projects\/p\.json/);assert.equal(calls,1);await assert.rejects(()=>repo.get('projects','../bad'));const switched=createRndRepository({auth:()=>({user:current}),token:async()=>{current={uid:'other',role:'viewer'};return'token';},databaseUrl:'https://test.invalid',fetch:async()=>{throw Error('network must not run');}});await assert.rejects(()=>switched.get('projects','p'),/세션/);});

test('CSV audit reads are isolated GET requests and reject account switch, id mismatch and audit save',async()=>{let actor={uid:'v',role:'viewer',email:'v@example.test'},calls=[];const options={auth:()=>({user:actor}),token:async()=> 'fixture-token',databaseUrl:'https://test.invalid',fetch:async(url,request)=>{calls.push({url,request});return{ok:true,json:async()=>({id:'job',projectId:'p'})};}},repo=createRndRepository(options);assert.deepEqual(await repo.getCSVAudit('job'),{id:'job',projectId:'p'});assert.equal(calls[0].request.method,'GET');assert.match(calls[0].url,/importJobs/);await assert.rejects(()=>repo.getCSVAudit('../escape'));await assert.rejects(()=>repo.save('importJobs',{id:'job',revision:0}));assert.equal(calls.length,1);const switched=createRndRepository({...options,fetch:async()=>{actor={...actor,uid:'other'};return{ok:true,json:async()=>({id:'job'})};}});await assert.rejects(()=>switched.getCSVAudit('job'),/세션/);const mismatch=createRndRepository({...options,fetch:async()=>({ok:true,json:async()=>({id:'other'})})});await assert.rejects(()=>mismatch.getCSVAudit('job'),/ID/);});
