const test=require('node:test'),assert=require('node:assert/strict');
test('portfolio and search project follow-up current state once per task',async()=>{
 const {buildRndExport}=await import('../src/rnd-control/export.mjs');const {createProject}=await import('../src/rnd-control/portfolio.mjs'),{applyResearch}=await import('../src/rnd-control/research.mjs'),{summarizePortfolio}=await import('../src/rnd-control/portfolio-summary.mjs'),{indexProjects,searchPage}=await import('../src/rnd-control/search.mjs');
 let p={...createProject('p','Pilot'),research:{decisions:[{id:'d',action:'hold',reason:'Next pilot',evidenceIds:[],decidedBy:'a',at:new Date().toISOString()}]}};
 p=applyResearch(p,{type:'followUp',task:{type:'create',eventId:'evt1',taskId:'t',decisionId:'d',title:'Field pilot',ownerUid:'owner',reviewerUid:'reviewer',due:'2026-09-01',criteria:'Reviewed report',reason:'Next pilot'}},{uid:'a',role:'admin'});
 p=applyResearch(p,{type:'followUp',task:{type:'transition',eventId:'evt2',taskId:'t',previousEventId:'evt1',status:'active',reason:'Started'}},{uid:'owner',role:'member'});
 const summary=summarizePortfolio([p],new Set(),'2026-09-17');assert.equal(summary.followUpOpen,1);assert.equal(summary.followUpOverdue,1);assert.equal(summary.rows[0].followUpReview,0);
 const result=searchPage(indexProjects([p]),{type:'후속 업무',query:'owner reviewed'});assert.equal(result.total,1);assert.equal(result.rows[0].id,'t');assert.equal(result.rows[0].status,'active');const internal=buildRndExport(p);assert.deepEqual(internal.manifest.includedFollowUps,['t']);assert.match(internal.files['follow-ups/t.md'],/Reviewed report/);assert.match(internal.files['follow-ups/t.md'],/Started/);const review=buildRndExport(p,{mode:'review'});assert.deepEqual(review.manifest.includedFollowUps,[]);assert.ok(review.manifest.excluded.some(e=>e.id==='t'&&e.reason==='FOLLOW_UP_DISCLOSURE_UNCONFIRMED'));assert.ok(!Object.keys(review.files).some(f=>f.startsWith('follow-ups/')));
});
