const test=require('node:test'),assert=require('node:assert/strict');const {createCSVAuditExport}=require('../src/rnd-control/csv-audit-export');
function fixture(){let generation=1,writes=0;const summary={id:'job',projectId:'p',readOnly:true,auditSHA256:'e5fc2675cc91539475ec0fc0fb61054cc31181bd2192374296470a71f58e8fbb',source:{fileName:'<script>alert(1)</script>'}},options={access:async()=>({uid:'u',email:'u@example.test',role:'viewer'}),captureSession:()=>generation,isCurrent:g=>g===generation,readHistory:async()=>summary,chooseFile:async()=>({filePath:'selected.zip'}),save:async(path,bytes,check)=>{await check();writes++;assert.ok(bytes.length>100);}};return{options,summary,reset:()=>generation++,writes:()=>writes};}
test('audit export uses authoritative history with IDs only and allows approved viewer',async()=>{const f=fixture();const out=await createCSVAuditExport(f.options)({projectId:'p',jobId:'job'});assert.equal(out.saved,true);assert.equal(out.originalFilesIncluded,false);assert.equal(f.writes(),1);await assert.rejects(()=>createCSVAuditExport(f.options)({projectId:'p',jobId:'job',summary:f.summary}));});
test('audit export cancellation and session changes write no file',async()=>{for(const mode of ['cancel','session']){const f=fixture();f.options.chooseFile=async()=>{if(mode==='session')f.reset();return mode==='cancel'?{canceled:true}:{filePath:'selected.zip'};};if(mode==='cancel')assert.equal((await createCSVAuditExport(f.options)({projectId:'p',jobId:'job'})).canceled,true);else await assert.rejects(()=>createCSVAuditExport(f.options)({projectId:'p',jobId:'job'}));assert.equal(f.writes(),0);}});
test('audit export rejects changed grants and mismatched history without file write',async()=>{const f=fixture();f.options.readHistory=async()=>({...f.summary,projectId:'other'});await assert.rejects(()=>createCSVAuditExport(f.options)({projectId:'p',jobId:'job'}));assert.equal(f.writes(),0);});
const {createHash}=require('node:crypto');
test('ZIP contains exact JSON and verifiable manifest; static README does not interpolate unsafe source text',async()=>{const f=fixture();let bytes;f.options.save=async(_path,b)=>{bytes=b;};await createCSVAuditExport(f.options)({projectId:'p',jobId:'job'});const files={};let pos=0;while(bytes.readUInt32LE(pos)===0x04034b50){const length=bytes.readUInt32LE(pos+18),nameLength=bytes.readUInt16LE(pos+26),extra=bytes.readUInt16LE(pos+28),name=bytes.subarray(pos+30,pos+30+nameLength).toString(),start=pos+30+nameLength+extra;files[name]=bytes.subarray(start,start+length).toString();pos=start+length;}assert.deepEqual(Object.keys(files),['audit-summary.json','manifest.json','README.md']);assert.deepEqual(JSON.parse(files['audit-summary.json']),f.summary);const manifest=JSON.parse(files['manifest.json']);assert.equal(manifest.summarySHA256,createHash('sha256').update(files['audit-summary.json']).digest('hex'));assert.equal(manifest.restoreBackup,false);assert.equal(files['README.md'].includes('<script>'),false);});
test('approval revoked while save dialog is open prevents file write',async()=>{const f=fixture();let revoked=false;const access=f.options.access;f.options.access=async()=>revoked?{uid:'u',email:'u@example.test',role:'viewer',mustChangePassword:true}:access();f.options.chooseFile=async()=>{revoked=true;return{filePath:'selected.zip'};};await assert.rejects(()=>createCSVAuditExport(f.options)({projectId:'p',jobId:'job'}));assert.equal(f.writes(),0);});
test('only canonical audit hash is exempt; malformed hashes and sensitive text are rejected',async()=>{for(const change of [{auditSHA256:'invalid'},{source:{ledger:'주민등록번호 900101-1234567'}}]){const f=fixture();f.options.readHistory=async()=>({...f.summary,...change});await assert.rejects(()=>createCSVAuditExport(f.options)({projectId:'p',jobId:'job'}));assert.equal(f.writes(),0);}});
