const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const h='a'.repeat(64),target={projectId:'p',artifactId:'a',versionId:'v',sha256:h,sizeBytes:3},request={actorUid:'u',previewId:'review',mappingSHA256:h,sourceZipSHA256:h,files:[{sourceProviderFileId:'source',target}]},started={type:'UPLOAD_STARTED',sourceProviderFileId:'source',...target},complete={...started,type:'UPLOAD_VERIFIED',providerFileId:'new',verifiedAt:'2026-09-17T00:00:00.000Z'};
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'bring-restore-journal-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const {createOriginalRestoreJournal}=require('../src/rnd-control/original-restore-journal');return{root,create:()=>createOriginalRestoreJournal(root)};}
test('restore upload reservation and immutable receipts survive reopening and enforce actor isolation',async t=>{const f=await fixture(t),j=f.create(),id=await j.begin(request);await j.append(id,started);await j.append(id,complete);const records=await f.create().list('u');assert.equal(records.length,1);assert.equal(records[0].attemptId,id);assert.deepEqual(records[0].events,[started,complete]);assert.deepEqual(await f.create().list('other'),[]);await assert.rejects(()=>f.create().begin(request),/중복|이미/);});
test('two independent journal instances cannot reserve or finish one attempt twice',async t=>{const f=await fixture(t),results=await Promise.allSettled([f.create().begin(request),f.create().begin(request)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);const id=results.find(x=>x.status==='fulfilled').value;await f.create().append(id,started);const endings=await Promise.allSettled([f.create().append(id,complete),f.create().append(id,{...complete,type:'UPLOAD_UNCERTAIN',verifiedAt:undefined})]);assert.equal(endings.filter(x=>x.status==='fulfilled').length,1);});
test('journal rejects mismatched targets, terminal before start, extra bytes and unsafe identities',async t=>{const f=await fixture(t),j=f.create(),id=await j.begin(request);await assert.rejects(()=>j.append(id,complete));await assert.rejects(()=>j.append(id,{...started,projectId:'foreign'}));await assert.rejects(()=>j.append(id,{...started,bytes:Buffer.from('secret')}));await assert.rejects(()=>j.begin({...request,actorUid:'../other'}));assert.equal((await j.list('u'))[0].events.length,0);});
test('bounded reservation quota applies across independent writers and counts incomplete attempts',async t=>{const f=await fixture(t),{createOriginalRestoreJournal}=require('../src/rnd-control/original-restore-journal'),a=createOriginalRestoreJournal(f.root,{maxAttempts:1});await a.begin(request);await assert.rejects(()=>createOriginalRestoreJournal(f.root,{maxAttempts:1}).begin({...request,mappingSHA256:'b'.repeat(64)}),/한도/);});

test('unfinished immutable event slots stay visible and cannot be overwritten after reopening',async t=>{const f=await fixture(t),j=f.create(),id=await j.begin(request);await j.append(id,started);const file=path.join(f.root,'attempts',id,'0-started','event.json');await fs.rename(file,file+'.partial');const result=(await f.create().list('u'))[0];assert.equal(result.incomplete,true);assert.deepEqual(result.events,[]);await assert.rejects(()=>f.create().append(id,started),/이미/);});

test('disk event reads reject foreign bindings and injected fields rather than exposing them',async t=>{const f=await fixture(t),j=f.create(),id=await j.begin(request);await j.append(id,started);const file=path.join(f.root,'attempts',id,'0-started','event.json');await fs.writeFile(file,JSON.stringify({...started,bytes:'secret'}));await assert.rejects(()=>f.create().list('u'),/원장/);});

test('real disk journal and upload coordinator retain one exact receipt and deny replay before another write',async t=>{
 const f=await fixture(t),{createOriginalRestoreUploader}=require('../src/rnd-control/original-restore-uploader'),{createHash}=require('node:crypto'),bytes=Buffer.from('abc'),targetBound={...target,sha256:createHash('sha256').update(bytes).digest('hex')};let writes=0;
 const plan={kind:'BRING_RND_ORIGINAL_REUPLOAD_PREPARATION',version:1,previewId:request.previewId,mappingSHA256:h,sourceZipSHA256:h,cloudWrites:false,canApply:false,originals:[{source:{providerFileId:'source'},target:targetBound,fileName:'sample.csv',bytes}]};
 const run=()=>createOriginalRestoreUploader({enabled:true,check:async()=>{},prepare:async()=>({uploadPlan:plan}),authorize:async binding=>({...binding,approved:true,actorUid:'u'}),journal:f.create(),upload:async()=>{writes++;return{...targetBound,providerFileId:'new',verifiedAt:complete.verifiedAt};}})({});
 const result=await run();assert.equal(result.receipts[0].sha256,targetBound.sha256);assert.equal((await f.create().list('u'))[0].events.at(-1).providerFileId,'new');await assert.rejects(run,/중복/);assert.equal(writes,1);
});

test('pre-existing attempt directory junctions are rejected without outside writes',async t=>{
 const f=await fixture(t),outside=await fs.mkdtemp(path.join(os.tmpdir(),'bring-journal-outside-'));t.after(()=>fs.rm(outside,{recursive:true,force:true}));await fs.symlink(outside,path.join(f.root,'attempts'),process.platform==='win32'?'junction':'dir');await assert.rejects(()=>f.create().begin(request),/경로/);assert.deepEqual(await fs.readdir(outside),[]);
});

test('root and actor quota junctions are rejected before private records can escape',async t=>{for(const mode of ['root','quota']){const f=await fixture(t),outside=await fs.mkdtemp(path.join(os.tmpdir(),'bring-journal-link-'));t.after(()=>fs.rm(outside,{recursive:true,force:true}));const {createOriginalRestoreJournal}=require('../src/rnd-control/original-restore-journal');let directory=f.root;if(mode==='root'){directory=path.join(f.root,'linked-root');await fs.symlink(outside,directory,process.platform==='win32'?'junction':'dir');}else{await fs.mkdir(path.join(f.root,'quotas'));await fs.symlink(outside,path.join(f.root,'quotas','u'),process.platform==='win32'?'junction':'dir');}await assert.rejects(()=>createOriginalRestoreJournal(directory).begin(request),/경로/);assert.deepEqual(await fs.readdir(outside),[]);}});
