const test=require('node:test'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');const sha=x=>createHash('sha256').update(x).digest('hex');
async function fixture(){
 const {buildOriginalBackup}=require('../src/rnd-control/original-backup'),{verifyOriginalBackup}=require('../src/rnd-control/original-backup-verification'),{createOriginalRestorePreview}=require('../src/rnd-control/original-restore-preview'),{createOriginalRestoreMapping}=require('../src/rnd-control/original-restore-mapping'),{createProject}=await import('../src/rnd-control/portfolio.mjs');
 const bytes=Buffer.from([255,0,128]),p=createProject('p','Source'),ref={projectId:'p',artifactId:'a',versionId:'v',providerFileId:'f',sha256:sha(bytes),sizeBytes:bytes.length};p.items[0].evidence=[ref,structuredClone(ref)];
 const backup=await buildOriginalBackup({projects:[p],visits:[{id:'visit',projectId:'p',revision:2,buildingId:'b',operator:'o',reason:'r',serviceScope:'s',costBasis:'c',evidenceUrl:'https://example.com',date:'2026-09-17',minutes:{travel:0,check:0,work:0,report:0,contact:0,other:0},costs:{labor:0,transport:0,materials:0,outsourcing:0},totalMinutes:0}],importJobs:[],selectedId:'p',additionalMetadata:{companyNotes:{note:'source note'}}},{check:async()=>{},download:async reference=>({reference,bytes,fileName:"측정.csv",mimeType:"text/csv"})}),source=await verifyOriginalBackup(backup.bytes,{check:async()=>{}}),preview=await createOriginalRestorePreview(backup.bytes,{projects:[p],visits:[],importJobs:[]},{check:async()=>{}}),mapping=createOriginalRestoreMapping(preview,{projects:['p'],visits:[],importJobs:[]},{projects:{p:'restored'},visits:{visit:'restored_visit'},importJobs:{}});
 return{source,mapping,bytes};
}
async function preparedFixture(){const f=await fixture(),{prepareRestoreOriginals}=require('../src/rnd-control/original-restore-originals'),plan=await prepareRestoreOriginals(f,{check:async()=>{}}),at=new Date().toISOString();f.context={actorUid:'admin',at,verification:{kind:'BRING_RND_VERIFIED_RESTORE_REFERENCES',version:1,previewId:f.mapping.previewId,attemptId:'d'.repeat(64),mappingSHA256:f.mapping.mappingSHA256,sourceAttemptMappingSHA256:f.mapping.mappingSHA256,sourceZipSHA256:f.mapping.sourceZipSHA256,cloudWrites:false,databaseWrites:false,restoreReady:false,originVerified:false,verifiedRefs:plan.originals.map(item=>({sourceProjectId:item.source.projectId,sourceArtifactId:item.source.artifactId,sourceVersionId:item.source.versionId,sourceProviderFileId:item.source.providerFileId,reference:{...item.target,providerFileId:'new_file',verifiedAt:at}}))}};return f;}
test('whole preparation derives projects and baseline records from one verified source and bound receipt without exposing bytes or transferring approval',async()=>{const {prepareOriginalRestore}=require('../src/rnd-control/original-restore-preparation'),f=await preparedFixture(),before=JSON.stringify(f.source.metadata),result=await prepareOriginalRestore(f,f.context,{check:async()=>{}});assert.equal(result.metadata.projects[0].id,'restored');assert.equal(result.metadata.visits[0].id,'restored_visit');assert.equal(result.metadata.visits[0].projectId,'restored');assert.equal(result.metadata.selectedId,'restored');assert.deepEqual(result.metadata.importJobs,[]);assert.deepEqual(result.metadata.restoredImportAudits,[]);assert.equal(result.archivalMetadataJSON,before);assert.equal(result.additionalMetadataDisposition,'ARCHIVED_REQUIRES_REVIEW');assert.equal(result.additionalCollectionCount,1);assert.equal(result.databaseWrites,false);assert.equal(result.restoreReady,false);assert.equal(JSON.stringify(f.source.metadata),before);assert.equal(JSON.stringify(result).includes('"bytes"'),false);});
test('whole preparation rejects changed source bytes, foreign mapping receipt and mismatched target binding',async()=>{const {prepareOriginalRestore}=require('../src/rnd-control/original-restore-preparation');for(const change of [f=>{f.source.originals.get('originals/f.bin')[0]=0;},f=>{f.context.verification.mappingSHA256='e'.repeat(64);},f=>{f.context.verification.verifiedRefs[0].reference.artifactId='wrong';},f=>{f.context.verification.verifiedRefs=[];}]){const f=await preparedFixture();change(f);await assert.rejects(()=>prepareOriginalRestore(f,f.context,{check:async()=>{}}));}});
test('whole preparation suppresses results after authority changes during staged derivation',async()=>{const {prepareOriginalRestore}=require('../src/rnd-control/original-restore-preparation'),f=await preparedFixture();let count=0;await assert.rejects(()=>prepareOriginalRestore(f,f.context,{check:async()=>{if(++count===5)throw Error('session changed');}}),/session changed/);});

test('Main reference execution invokes private full preparation only after fresh file verification and returns a bounded summary',async()=>{const {createOriginalRestoreReferenceExecution}=require('../src/rnd-control/original-restore-reference-execution'),{prepareOriginalRestoreSummary}=require('../src/rnd-control/original-restore-preparation'),{prepareRestoreOriginals}=require('../src/rnd-control/original-restore-originals'),f=await preparedFixture(),uploadPlan=await prepareRestoreOriginals(f,{check:async()=>{}}),item=uploadPlan.originals[0],request={attemptId:f.context.verification.attemptId,previewId:f.mapping.previewId,targets:{projects:{p:'restored'},visits:{visit:'restored_visit'},importJobs:{}}};let calls=0,media=0;const run=createOriginalRestoreReferenceExecution({access:async()=>({uid:'admin',email:'admin@test',role:'admin'}),captureSession:()=>1,isCurrent:()=>true,sessions:{mapping:async()=>f.mapping,prepare:async()=>({...f,uploadPlan})},journal:{get:async()=>({attemptId:request.attemptId,actorUid:'admin',mappingSHA256:f.mapping.mappingSHA256,sourceZipSHA256:f.mapping.sourceZipSHA256,incomplete:false,files:[{sourceProviderFileId:'f',target:item.target}],events:[{type:'UPLOAD_STARTED',sourceProviderFileId:'f',...item.target},{type:'UPLOAD_VERIFIED',sourceProviderFileId:'f',...item.target,providerFileId:'new_file'}]})},drive:{state:()=>({status:'READY'}),verifyVersion:async ref=>{media++;return{...ref,verifiedAt:new Date().toISOString()};}},prepareResult:async({prepared,verification,actor},{check})=>{calls++;assert.equal(media,1);return prepareOriginalRestoreSummary({prepared,verification,actor},{check});}});const result=await run(request);assert.equal(calls,1);assert.equal(result.preparation.projectCount,1);assert.equal(result.preparation.visitCount,1);assert.equal(result.preparation.metadata,undefined);assert.equal(result.databaseWrites,false);});
