const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {createCSVJobLedger,csvJobDigest}=require('../src/rnd-control/csv-job-ledger');
const {buildCSVImportAudit,validateCSVImportAudit}=require('../src/rnd-control/csv-import-audit');
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'csv-audit-'));try{const fields=['id','buildingId','date','operator','reason','serviceScope','costBasis','evidenceUrl','totalMinutes','travel','check','work','report','contact','other','labor','transport','materials','outsourcing'];const bytes=new TextEncoder().encode([fields.join(','),['a','b','2026-09-17','o','r','s','c','https://example.com','0',...Array(10).fill('0')].join(',')].join('\n'));const {previewBaselineCSV}=await import('../src/rnd-control/csv-import.mjs');const preview=await previewBaselineCSV({bytes,mapping:Object.fromEntries(fields.map(k=>[k,k])),projectId:'p',projectIds:['p'],current:[],units:{minutes:'min',costs:'KRW'},source:{fileName:'source.csv',ledger:'원장',extractedAt:'2026-09-16T00:00:00.000Z'}});const job=await createCSVJobLedger(root).create('u',{bytes,preview,actorEmail:'u@example.test',skipIds:[]});return{job,projectRevision:1,publisher:{uid:'u',email:'u@example.test',role:'member'},at:'2026-09-17T00:02:00.000Z',driveReference:{projectId:'p',artifactId:'csv-import-original',versionId:job.id,providerFileId:'file',sha256:job.source.sha256,sizeBytes:job.source.sizeBytes,status:'VERIFIED',verifiedAt:'2026-09-17T00:01:00.000Z'}};}finally{await fs.rm(root,{recursive:true,force:true});}}
test('CSV audit freezes source/job/dry-run/rollback and preserves local-only import meaning',async()=>{const f=await fixture(),audit=await buildCSVImportAudit(f);assert.equal(audit.status,'LOCAL_DRAFTS_RECORDED');assert.equal(audit.cloudVisitWrites,false);assert.equal(audit.projectId,'p');assert.equal(audit.id,f.job.id);assert.deepEqual(JSON.parse(audit.importJobJSON),f.job);assert.deepEqual(JSON.parse(audit.rollbackManifestJSON),f.job.rollbackManifest);assert.equal(JSON.parse(audit.dryRunJSON).additions.length,1);assert.equal(audit.sourceSHA256,f.job.source.sha256);assert.equal(audit.driveReference.providerFileId,'file');assert.deepEqual(await validateCSVImportAudit(audit),audit);});
test('CSV audit rejects unverified, mismatched, stale/future Drive source and foreign/viewer publisher',async()=>{const f=await fixture();for(const drive of [{...f.driveReference,status:'UPLOADED_UNVERIFIED',observedAt:f.at},{...f.driveReference,sha256:'b'.repeat(64)},{...f.driveReference,verifiedAt:'2026-09-16T00:00:00.000Z'},{...f.driveReference,verifiedAt:'2026-09-17T00:03:00.000Z'}])await assert.rejects(()=>buildCSVImportAudit({...f,driveReference:drive}));for(const publisher of [{...f.publisher,uid:'other'},{...f.publisher,role:'viewer'},{...f.publisher,email:'other@example.test'}])await assert.rejects(()=>buildCSVImportAudit({...f,publisher}));});
test('CSV audit rejects changed payload with recomputed checksum, unknown fields and source-job tampering',async()=>{const f=await fixture(),audit=await buildCSVImportAudit(f);for(const patch of [{status:'SHARED_VISITS_APPLIED'},{cloudVisitWrites:true},{projectId:'other'},{rollbackManifestJSON:'{}'},{dryRunJSON:'{}'},{extra:'unexpected'}]){const raw={...audit,...patch};delete raw.integritySHA256;raw.integritySHA256=csvJobDigest(raw);await assert.rejects(()=>validateCSVImportAudit(raw));}const job=structuredClone(f.job);job.source.ledger='changed';await assert.rejects(()=>buildCSVImportAudit({...f,job}));});

test('CSV audit captures owned input before async validation and enforces exact fresh-source boundary',async()=>{const f=await fixture(),pending=buildCSVImportAudit(f);f.job.source.ledger='late mutation';f.driveReference.providerFileId='late-file';f.publisher.email='late@example.test';const audit=await pending;assert.equal(JSON.parse(audit.importJobJSON).source.ledger,'원장');assert.equal(audit.driveReference.providerFileId,'file');assert.equal(audit.publishedByEmail,'u@example.test');const g=await fixture();g.at='2026-09-17T00:06:00.000Z';await buildCSVImportAudit(g);await assert.rejects(()=>buildCSVImportAudit({...g,at:'2026-09-17T00:06:00.001Z'}));});
