const test=require('node:test');const assert=require('node:assert/strict');test('R&D approval rejects missing disabled mismatched access and session changes',async()=>{const {createAccessCheck}=require('../src/rnd-control/access');let user={uid:'u',email:'u@test.invalid',role:'member'};let grant={enabled:true,email:user.email,role:user.role};const check=createAccessCheck({auth:()=>({user}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async()=>({ok:true,json:async()=>grant})});assert.equal((await check()).uid,'u');for(const bad of [null,{...grant,enabled:false},{...grant,role:'admin'},{...grant,email:'wrong'}]){const prior=grant;grant=bad;await assert.rejects(check);grant=prior;}const switched=createAccessCheck({auth:()=>({user}),token:async()=>{user={...user,uid:'other'};return'token';},databaseUrl:'https://test.invalid',fetch:async()=>{throw Error('network must not run');}});await assert.rejects(switched,/session/);});

test('admin grant derives role and email from CRM and refuses nonadmin or invalid targets',async()=>{const {createAccessAdmin}=require('../src/rnd-control/access-admin');let user={uid:'admin',email:'admin@test.invalid',role:'admin'},payload;const admin=createAccessAdmin({auth:()=>({user}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async(url,o)=>o.method==='GET'?{ok:true,headers:{get:()=> '"v1"'},json:async()=>({enabled:true,email:'member@test.invalid',role:'member'})}:{ok:true,json:async()=>{payload=JSON.parse(o.body);return payload;}}});const value=await admin.save({uid:'member',enabled:true,reason:'team',role:'admin',expectedETag:'"v1"'});assert.equal(value.role,'member');assert.equal(value.approvedBy,'admin');user={...user,role:'member'};await assert.rejects(()=>admin.save({uid:'member',enabled:true,reason:'team'}));});

test('admin conditional write refuses stale approval without overwrite retry',async()=>{const {createAccessAdmin}=require('../src/rnd-control/access-admin');let writes=0;const service=createAccessAdmin({auth:()=>({user:{uid:'a',email:'a@test.invalid',role:'admin'}}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async(url,o)=>{if(o.method==='GET')return{ok:true,headers:{get:()=> '"old"'},json:async()=>({enabled:true,email:'m@test.invalid',role:'member'})};if(url.includes('rndAccessAudit'))return{ok:true,json:async()=>null};writes++;assert.equal(o.headers['If-Match'],'"old"');return{ok:false,status:412};}});await assert.rejects(()=>service.save({uid:'m',enabled:false,reason:'revoke',expectedETag:'"old"'}),/conflict/);assert.equal(writes,1);});

test('audit write failure stops approval mutation',async()=>{const {createAccessAdmin}=require('../src/rnd-control/access-admin');let approvalWrites=0;const service=createAccessAdmin({auth:()=>({user:{uid:'a',email:'a@test.invalid',role:'admin'}}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async(url,o)=>{if(o.method==='GET')return{ok:true,headers:{get:()=> '"v"'},json:async()=>({enabled:true,email:'m@test.invalid',role:'member'})};if(!url.includes('rndAccessAudit'))approvalWrites++;return{ok:false,status:403};}});await assert.rejects(()=>service.save({uid:'m',enabled:false,reason:'revoke',expectedETag:'"v"'}),/audit/);assert.equal(approvalWrites,0);});

test('admin read links current approval to its audit without claiming unconfirmed attempts committed',async()=>{const {createAccessAdmin}=require('../src/rnd-control/access-admin');const service=createAccessAdmin({auth:()=>({user:{uid:'a',role:'admin'}}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async url=>({ok:true,headers:{get:()=> '"v"'},json:async()=>url.includes('rndAccessAudit')?{id:'event',targetUid:'m',after:{enabled:false,auditId:'event'}}:url.includes('/rndAccess/')?{auditId:'event',enabled:false}:{} })});const value=await service.get('m');assert.equal(value.audit.id,'event');assert.equal(value.auditLink,'current-approval-linked');});

test('lost approval response is verified by readback without another write',async()=>{const {createAccessAdmin}=require('../src/rnd-control/access-admin');let stored=null,writes=0;const service=createAccessAdmin({auth:()=>({user:{uid:'a',email:'a@test.invalid',role:'admin'}}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async(url,o)=>{if(o.method==='GET')return{ok:true,headers:{get:()=> '"v"'},json:async()=>url.includes('/crmCompany/')?{enabled:true,email:'m@test.invalid',role:'member'}:stored};if(url.includes('rndAccessAudit'))return{ok:true,json:async()=>null};writes++;stored=JSON.parse(o.body);throw Error('connection lost after commit');}});const result=await service.save({uid:'m',enabled:false,reason:'revoke',expectedETag:'"v"'});assert.equal(result.enabled,false);assert.equal(result.recoveredByReadback,true);assert.equal(writes,1);});
test('uncommitted lost response stays unconfirmed without another write',async()=>{const {createAccessAdmin}=require('../src/rnd-control/access-admin');let stored=null,writes=0;const service=createAccessAdmin({auth:()=>({user:{uid:'a',email:'a@test.invalid',role:'admin'}}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async(url,o)=>{if(o.method==='GET')return{ok:true,headers:{get:()=> '"v"'},json:async()=>url.includes('/crmCompany/')?{enabled:true,email:'m@test.invalid',role:'member'}:stored};if(url.includes('rndAccessAudit'))return{ok:true,json:async()=>null};writes++;throw Error('connection lost after commit');}});await assert.rejects(()=>service.save({uid:'m',enabled:false,reason:'revoke',expectedETag:'"v"'}),/unconfirmed/);assert.equal(writes,1);});

test('audit inspection leaves orphan request unconfirmed',async()=>{const {createAccessAdmin}=require('../src/rnd-control/access-admin');const service=createAccessAdmin({auth:()=>({user:{uid:'a',role:'admin'}}),token:async()=> 'token',databaseUrl:'https://test.invalid',fetch:async url=>({ok:true,json:async()=>url.includes('rndAccessAudit')?{id:'request',targetUid:'m',after:{enabled:false}}:{enabled:true,auditId:'other'}})});assert.equal((await service.inspect('m','request')).status,'unconfirmed-request');await assert.rejects(()=>service.inspect('m','../bad'));});
