const test=require('node:test'),assert=require('node:assert/strict');
test('binary restore preview verifies ZIP and reports source/project conflicts without applying writes',async()=>{
 const {createOriginalRestorePreview}=require('../src/rnd-control/original-restore-preview'),{createProject}=await import('../src/rnd-control/portfolio.mjs'),{prepareOriginalBackupSnapshot}=require('../src/rnd-control/original-backup-metadata'),{buildOriginalBackup}=require('../src/rnd-control/original-backup');const p=createProject('p','Existing'),q=createProject('q','New');const original=Buffer.from([0,255,128]),ref={projectId:'q',artifactId:'a',versionId:'v',providerFileId:'f',sha256:require('node:crypto').createHash('sha256').update(original).digest('hex'),sizeBytes:3};q.items[0].evidence=[ref];const metadata=await prepareOriginalBackupSnapshot({projects:{p,q},visits:{},importJobs:{}},'p'),zip=await buildOriginalBackup(metadata,{check:async()=>{},download:async received=>({reference:received,bytes:original})});
 const preview=await createOriginalRestorePreview(zip.bytes,{projects:[p],visits:[],importJobs:[]},{check:async()=>{}});assert.equal(preview.canApply,false);assert.equal(preview.projects[0].action,'REQUIRES_NEW_TARGET_ID');assert.equal(preview.projects[1].action,'REQUIRES_APPROVED_CREATE');assert.equal(preview.fullBackup,false);assert.match(preview.sourceZipSHA256,/^[a-f0-9]{64}$/);assert.equal(preview.originVerified,false);assert.equal(preview.originalPlan.length,1);assert.equal(preview.originalPlan[0].action,'REQUIRES_VERIFIED_REUPLOAD');assert.equal(preview.originalPlan[0].sha256,ref.sha256);assert.equal(preview.originalPlan[0].bytes,undefined);assert.deepEqual(Object.keys(preview).filter(k=>['bytes','metadata','originals'].includes(k)),[]);
});
test('binary restore preview rejects corrupted ZIP and invalid current research relationships',async()=>{
 const {createOriginalRestorePreview}=require('../src/rnd-control/original-restore-preview');await assert.rejects(()=>createOriginalRestorePreview(Buffer.from('invalid'),{projects:[],visits:[],importJobs:[]},{check:async()=>{}}));
 const {createProject}=await import('../src/rnd-control/portfolio.mjs'),{buildOriginalBackup}=require('../src/rnd-control/original-backup');const p=createProject('p','Good'),zip=await buildOriginalBackup({projects:[p],selectedId:'p',visits:[],importJobs:[]},{check:async()=>{},download:async()=>{throw Error('no files');}});const bad=structuredClone(p);bad.research={evidence:[{id:'ev',experimentId:'missing'}]};await assert.rejects(()=>createOriginalRestorePreview(zip.bytes,{projects:[bad],visits:[],importJobs:[]},{check:async()=>{}}),/연구 참조/);await assert.rejects(()=>createOriginalRestorePreview(zip.bytes,{projects:[],visits:[],importJobs:[]},{check:async()=>{throw Error('세션');}}),/세션/);

});
