const test=require('node:test'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');const sha=x=>createHash('sha256').update(x).digest('hex');
async function fixture(){
 const {buildOriginalBackup}=require('../src/rnd-control/original-backup'),{verifyOriginalBackup}=require('../src/rnd-control/original-backup-verification'),{createOriginalRestorePreview}=require('../src/rnd-control/original-restore-preview'),{createOriginalRestoreMapping}=require('../src/rnd-control/original-restore-mapping'),{createProject}=await import('../src/rnd-control/portfolio.mjs');
 const bytes=Buffer.from([255,0,128]),p=createProject('p','Source'),ref={projectId:'p',artifactId:'a',versionId:'v',providerFileId:'f',sha256:sha(bytes),sizeBytes:bytes.length};p.items[0].evidence=[ref,structuredClone(ref)];
 const backup=await buildOriginalBackup({projects:[p],visits:[{id:'visit',projectId:'p',revision:2,buildingId:'b',operator:'o',reason:'r',serviceScope:'s',costBasis:'c',evidenceUrl:'https://example.com',date:'2026-09-17',minutes:{travel:0,check:0,work:0,report:0,contact:0,other:0},costs:{labor:0,transport:0,materials:0,outsourcing:0},totalMinutes:0}],importJobs:[],selectedId:'p',additionalMetadata:{companyNotes:{note:'source note'}}},{check:async()=>{},download:async reference=>({reference,bytes,fileName:"측정.csv",mimeType:"text/csv"})}),source=await verifyOriginalBackup(backup.bytes,{check:async()=>{}}),preview=await createOriginalRestorePreview(backup.bytes,{projects:[p],visits:[],importJobs:[]},{check:async()=>{}}),mapping=createOriginalRestoreMapping(preview,{projects:['p'],visits:[],importJobs:[]},{projects:{p:'restored'},visits:{visit:'restored_visit'},importJobs:{}});
 return{source,mapping,bytes};
}
async function preparedFixture(){const f=await fixture(),{prepareRestoreOriginals}=require('../src/rnd-control/original-restore-originals'),plan=await prepareRestoreOriginals(f,{check:async()=>{}}),at=new Date().toISOString();f.context={actorUid:'admin',at,verification:{kind:'BRING_RND_VERIFIED_RESTORE_REFERENCES',version:1,previewId:f.mapping.previewId,attemptId:'d'.repeat(64),mappingSHA256:f.mapping.mappingSHA256,sourceAttemptMappingSHA256:f.mapping.mappingSHA256,sourceZipSHA256:f.mapping.sourceZipSHA256,cloudWrites:false,databaseWrites:false,restoreReady:false,originVerified:false,verifiedRefs:plan.originals.map(item=>({sourceProjectId:item.source.projectId,sourceArtifactId:item.source.artifactId,sourceVersionId:item.source.versionId,sourceProviderFileId:item.source.providerFileId,reference:{...item.target,providerFileId:'new_file',verifiedAt:at}}))}};return f;}
async function mutationFixture(){const {prepareOriginalRestore}=require('../src/rnd-control/original-restore-preparation'),{researchFingerprint}=require('../src/rnd-control/repository'),{createProject}=await import('../src/rnd-control/portfolio.mjs'),f=await preparedFixture(),preparation=await prepareOriginalRestore(f,f.context,{check:async()=>{}}),value={projects:{existing:createProject('existing','Preserved')},visits:{},importJobs:{old:{id:'old',preserved:true}},other:{preserved:true}},snapshot={actorUid:'admin',etag:'current-etag',value,contentSHA256:sha(researchFingerprint(value))},approval={kind:'BRING_RND_ORIGINAL_RESTORE_APPROVAL',version:1,approved:true,actorUid:'admin',operationId:'11111111-1111-4111-8111-111111111111',at:new Date().toISOString(),reason:'reviewed complete restore',preparedSHA256:sha(JSON.stringify(preparation)),snapshotSHA256:snapshot.contentSHA256,additionalMetadataAction:'ARCHIVE_ONLY'};return{snapshot,preparation,approval};}
test('trusted original restore compiler adds all new records atomically and preserves existing CSV audits and unrelated data',async()=>{const {createOriginalRestoreMutation}=require('../src/rnd-control/original-restore-mutation'),f=await mutationFixture(),before=JSON.stringify(f.snapshot),result=await createOriginalRestoreMutation(f);assert.equal(result.value.projects.restored.revision,1);assert.equal(result.value.visits.restored_visit.revision,1);assert.deepEqual(result.value.importJobs,f.snapshot.value.importJobs);assert.deepEqual(result.value.other,f.snapshot.value.other);assert.deepEqual(result.value.projects.existing,f.snapshot.value.projects.existing);assert.equal(result.audit.archivalMetadataJSON,f.preparation.archivalMetadataJSON);assert.equal(result.audit.actorUid,'admin');assert.equal(result.expectedETag,'current-etag');assert.equal(JSON.stringify(f.snapshot),before);});
test('compiler rejects stale root, changed preparation and unapproved or foreign grants',async()=>{const {createOriginalRestoreMutation}=require('../src/rnd-control/original-restore-mutation');for(const change of [f=>{f.snapshot.value.other.changed=true;},f=>{f.preparation.metadata.projects[0].title='changed';},f=>{f.approval.approved=false;},f=>{f.approval.actorUid='other';},f=>{delete f.approval.additionalMetadataAction;}]){const f=await mutationFixture();change(f);await assert.rejects(()=>createOriginalRestoreMutation(f));}});
test('compiler refuses duplicate IDs or operation replay even with an updated current snapshot grant',async()=>{const {createOriginalRestoreMutation}=require('../src/rnd-control/original-restore-mutation'),{researchFingerprint}=require('../src/rnd-control/repository');for(const collision of ['project','visit','operation']){const f=await mutationFixture();if(collision==='project')f.snapshot.value.projects.restored={id:'restored'};else if(collision==='visit')f.snapshot.value.visits.restored_visit={id:'restored_visit'};else f.snapshot.value.restoreApprovals={[f.approval.operationId]:{id:f.approval.operationId}};f.snapshot.contentSHA256=sha(researchFingerprint(f.snapshot.value));f.approval.snapshotSHA256=f.snapshot.contentSHA256;await assert.rejects(()=>createOriginalRestoreMutation(f));}});
test('compiler scans new archival data and reason while preserving unrelated existing credentials',async()=>{const {createOriginalRestoreMutation}=require('../src/rnd-control/original-restore-mutation');const existing=await mutationFixture();existing.snapshot.value.other.password='password: actual-private-123';existing.snapshot.contentSHA256=sha(require('../src/rnd-control/repository').researchFingerprint(existing.snapshot.value));existing.approval.snapshotSHA256=existing.snapshot.contentSHA256;assert.equal((await createOriginalRestoreMutation(existing)).value.other.password,existing.snapshot.value.other.password);for(const location of ['archive','reason']){const f=await mutationFixture();if(location==='archive'){f.preparation.archivalMetadataJSON=JSON.stringify({doorlockcode:1234});f.preparation.archivalMetadataSHA256=sha(f.preparation.archivalMetadataJSON);f.approval.preparedSHA256=sha(JSON.stringify(f.preparation));}else f.approval.reason='출입 비밀번호: 1234';await assert.rejects(()=>createOriginalRestoreMutation(f),{code:'PROHIBITED_SENSITIVE_VALUE'});}});
