const test=require('node:test'),assert=require('node:assert/strict');
class Node{constructor(tag){this.tag=tag;this.children=[];this.textContent='';this.disabled=false;}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x;}setAttribute(){}remove(){}}
const h='a'.repeat(64),preview={kind:'BRING_RND_ORIGINAL_RESTORE_PREVIEW',previewId:'review',canApply:false,projects:[{id:'p',action:'REQUIRES_NEW_TARGET_ID'}],visits:[],importJobs:[],originalPlan:[{providerFileId:'f',action:'REQUIRES_VERIFIED_REUPLOAD'}],sourceZipSHA256:h,unverifiedLinkCount:0};
async function fixture(t,verify){const previous={document:global.document,window:global.window},events=new EventTarget();global.document={createElement:tag=>new Node(tag)};global.window=events;t.after(()=>Object.assign(global,previous));const host=new Node('host'),{mountOriginalRestoreReview}=await import('../src/rnd-control/original-restore-review-ui.mjs');let sent;const dispose=mountOriginalRestoreReview(host,{rndReviewOriginalRestore:async()=>preview,rndMapOriginalRestore:async()=>({kind:'BRING_RND_ORIGINAL_RESTORE_MAPPING',previewId:'review',canApply:false,cloudWrites:false,mappingSHA256:h}),rndVerifyOriginalRestore:async request=>{sent=request;return verify(request);}}),find=id=>{const walk=n=>n.id===id?n:n.children.map(walk).find(Boolean);return walk(host);};await find('rndOriginalRestoreLoad').onclick();return{find,events,dispose,sent:()=>sent};}
function receipt(r){return{kind:'BRING_RND_VERIFIED_RESTORE_REFERENCES',version:1,attemptId:h,previewId:'review',mappingSHA256:h,sourceAttemptMappingSHA256:h,sourceZipSHA256:h,cloudWrites:false,databaseWrites:false,restoreReady:false,originVerified:false,verifiedRefs:[{sourceProviderFileId:'f',sourceProjectId:'p',sourceArtifactId:'a',sourceVersionId:'v',reference:{projectId:r.targets.projects.p,providerFileId:'new_f',artifactId:'na',versionId:'nv',sha256:h,sizeBytes:3,verifiedAt:'2026-09-17T00:00:00.000Z',url:'https://drive.google.com/file/d/new_f/view'}}]};}
test('CRM reverify requires a current mapping and valid attempt ID, sends IDs only and distinguishes DB restore',async t=>{const f=await fixture(t,async r=>receipt(r));assert.ok(f.find('rndOriginalRestoreVerify'),'reference verification button required');assert.equal(f.find('rndOriginalRestoreVerify').disabled,true);await f.find('rndOriginalRestoreMap').onclick();f.find('rndOriginalRestoreAttempt').value=h;f.find('rndOriginalRestoreAttempt').oninput();assert.equal(f.find('rndOriginalRestoreVerify').disabled,false);await f.find('rndOriginalRestoreVerify').onclick();assert.deepEqual(Object.keys(f.sent()).sort(),['attemptId','previewId','targets']);assert.match(f.find('rndOriginalRestoreVerifyStatus').textContent,/원본 1개.*공유 복원/);f.dispose();});
test('CRM reverify rejects receipt bound to a different mapping',async t=>{const f=await fixture(t,async r=>({...receipt(r),mappingSHA256:'b'.repeat(64)}));await f.find('rndOriginalRestoreMap').onclick();f.find('rndOriginalRestoreAttempt').value=h;f.find('rndOriginalRestoreAttempt').oninput();await f.find('rndOriginalRestoreVerify').onclick();assert.match(f.find('rndOriginalRestoreVerifyStatus').textContent,/미완료/);f.dispose();});
test('pending reverify locks controls and session reset suppresses delayed receipt',async t=>{let resolve;const f=await fixture(t,()=>new Promise(r=>resolve=r));await f.find('rndOriginalRestoreMap').onclick();f.find('rndOriginalRestoreAttempt').value=h;f.find('rndOriginalRestoreAttempt').oninput();const pending=f.find('rndOriginalRestoreVerify').onclick();assert.equal(f.find('rndOriginalRestoreAttempt').disabled,true);assert.equal(f.find('rndOriginalRestoreLoad').disabled,true);f.events.dispatchEvent(new Event('rnd-session-reset'));resolve(receipt(f.sent()));await pending;assert.equal(f.find('rndOriginalRestoreVerifyStatus').textContent,'');assert.equal(f.find('rndOriginalRestoreAttempt').value,'');f.dispose();});

test('CRM displays bounded full preparation counts and rejects a summary bound to another mapping',async t=>{for(const changed of [false,true]){const f=await fixture(t,async r=>({...receipt(r),preparation:{kind:'BRING_RND_ORIGINAL_RESTORE_PREPARATION_SUMMARY',version:1,previewId:r.previewId,attemptId:r.attemptId,sourceZipSHA256:h,mappingSHA256:changed?'b'.repeat(64):h,metadataSHA256:h,archivalMetadataSHA256:h,projectCount:1,visitCount:0,auditCount:0,additionalCollectionCount:0,additionalMetadataDisposition:'NONE',unverifiedEvidenceLinkCount:0,databaseWrites:false,cloudWrites:false,restoreReady:false,originVerified:false}}));await f.find('rndOriginalRestoreMap').onclick();f.find('rndOriginalRestoreAttempt').value=h;f.find('rndOriginalRestoreAttempt').oninput();await f.find('rndOriginalRestoreVerify').onclick();assert.match(f.find('rndOriginalRestoreVerifyStatus').textContent,changed?/미완료/:/프로젝트 1개.*기준선 0개.*감사 0개/);f.dispose();}});
