const test=require('node:test'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');const digest=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
test('restore mapping session uses private preview and denies changed login, expired review and changed company data',async()=>{
 const {createOriginalRestoreSessions}=require('../src/rnd-control/original-restore-sessions');let generation=1,time=0,value={projects:{}};const actor={uid:'u',email:'u@test',role:'admin'},preview={previewId:'review',sharedETag:'e',sharedRootSHA256:digest(value),sharedEmptyRoot:false};
 const store=createOriginalRestoreSessions({access:async()=>actor,isCurrent:g=>g===generation,readSnapshot:async()=>({value,etag:'e',emptyRoot:false}),now:()=>time,map:(saved,ids,targets)=>({previewId:saved.previewId,targets})});const register=()=>store.add({preview,actor,binding:generation,currentIds:{projects:[],visits:[],importJobs:[]}});register();assert.equal((await store.mapping({previewId:'review',targets:{projects:{},visits:{},importJobs:{}}})).previewId,'review');await assert.rejects(()=>store.mapping({previewId:'review',targets:{},preview:{}}));generation++;await assert.rejects(()=>store.mapping({previewId:'review',targets:{}}),/세션/);register();time=600001;await assert.rejects(()=>store.mapping({previewId:'review',targets:{}}),/만료/);time=0;register();value={projects:{new:{id:'new'}}};await assert.rejects(()=>store.mapping({previewId:'review',targets:{}}),/공유 자료/);
});

test('cleared private review cannot return delayed mapping result',async()=>{
 const {createOriginalRestoreSessions}=require('../src/rnd-control/original-restore-sessions');let release;const value={},actor={uid:'u',email:'u@test',role:'admin'},store=createOriginalRestoreSessions({access:async()=>actor,isCurrent:()=>true,readSnapshot:()=>new Promise(resolve=>release=()=>resolve({etag:'e',value,emptyRoot:false})),map:()=>({canApply:false})});store.add({preview:{previewId:'p',sharedETag:'e',sharedRootSHA256:digest(value),sharedEmptyRoot:false},actor,binding:1,currentIds:{projects:[],visits:[],importJobs:[]}});const pending=store.mapping({previewId:'p',targets:{}});await new Promise(resolve=>setImmediate(resolve));store.clear();release();await assert.rejects(()=>pending,/만료/);
});
