const test=require('node:test');const assert=require('node:assert/strict');
test('approval preparation rejects a changed shared project and binds immutable source history without writes',async()=>{
 const {createSharedRestorePreview}=require('../src/rnd-control/shared-restore-preview');const {prepareSharedRestoreApproval}=require('../src/rnd-control/shared-restore-approval');const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {createMetadataBackup}=await import('../src/rnd-control/backup.mjs');const p=createProject('p','Shared'),q=createProject('q','Archived');q.history.push({kind:'source',actor:'original',reason:'Prior audit',at:'2026-09-16T00:00:00.000Z'});const backup=await createMetadataBackup([p,q],p.id);let current=p;const preview=createSharedRestorePreview({access:async()=>({uid:'admin',email:'a@example.test',role:'admin'}),list:async key=>key==='projects'?[current]:[]});const reviewed=await preview({backup});const before=JSON.stringify(backup);const plan=await prepareSharedRestoreApproval({backup,reviewed,preview,reason:'Recover reviewed archive'});assert.equal(plan.canApply,false);assert.deepEqual(plan.projects.map(p=>p.id),['q']);assert.deepEqual(plan.projects[0].history,q.history);assert.equal(JSON.stringify(backup),before);assert.match(plan.planSHA256,/^[0-9a-f]{64}$/);current={...p,title:'Changed without revision'};await assert.rejects(()=>prepareSharedRestoreApproval({backup,reviewed,preview,reason:'Recover archive'}),/변경/);
});
test('approval preparation rejects forged actor, altered backup binding and missing reason',async()=>{
 const {createSharedRestorePreview}=require('../src/rnd-control/shared-restore-preview');const {prepareSharedRestoreApproval}=require('../src/rnd-control/shared-restore-approval');const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {createMetadataBackup}=await import('../src/rnd-control/backup.mjs');const p=createProject('p','P');const backup=await createMetadataBackup([p],p.id);const preview=createSharedRestorePreview({access:async()=>({uid:'admin',email:'a@example.test',role:'admin'}),list:async()=>[]});const reviewed=await preview({backup});await assert.rejects(()=>prepareSharedRestoreApproval({backup,reviewed,preview,reason:''}),/사유/);await assert.rejects(()=>prepareSharedRestoreApproval({backup,reviewed:{...reviewed,actorUid:'other'},preview,reason:'restore'}),/변경/);await assert.rejects(()=>prepareSharedRestoreApproval({backup,reviewed:{...reviewed,backupArchiveSHA256:'0'.repeat(64)},preview,reason:'restore'}),/변경/);
});

test('approval refuses a new visit bound to a colliding project even when preflight is unchanged',async()=>{
 const {createSharedRestorePreview}=require('../src/rnd-control/shared-restore-preview');const {prepareSharedRestoreApproval}=require('../src/rnd-control/shared-restore-approval');const {createProject}=await import('../src/rnd-control/portfolio.mjs');const {createMetadataBackup}=await import('../src/rnd-control/backup.mjs');const p=createProject('p','P'),v={id:'v',revision:0,projectId:'p',buildingId:'b',operator:'op',reason:'inspect',serviceScope:'routine',costBasis:'actual',evidenceUrl:'https://example.com/source',date:'2026-09-17',minutes:{travel:0,check:0,work:0,report:0,contact:0,other:0},costs:{labor:0,transport:0,materials:0,outsourcing:0},totalMinutes:0};const backup=await createMetadataBackup([p],p.id,[v]);const preview=createSharedRestorePreview({access:async()=>({uid:'admin',email:'a@example.test',role:'admin'}),list:async key=>key==='projects'?[p]:[]});const reviewed=await preview({backup});await assert.rejects(()=>prepareSharedRestoreApproval({backup,reviewed,preview,reason:'Restore visit'}),/프로젝트.*충돌/);
});
